```{r Firth - Estimates - Horizontal}

Firth_Estimate_Grid_H <- wrap_plots(Estimate_Plots,
                                  ncol = 3,
                                  nrow = 2,         
                                  guides = "collect")   +
  plot_annotation(title = "Firth-Penalized Logistic Regression\nEstimates (Log Odds)", 
                  theme = theme(plot.title.position = "plot",
                  plot.title = element_text(face = "bold",
                                            size = 16, 
                                            hjust = 0))) &
  theme(legend.position = "bottom", 
        legend.justification = c("center", "bottom"),        
        legend.box = "horizontal",      
        legend.direction = "horizontal", 
        plot.margin = margin(t = 5, r = 20, b = 5, l = 5))

ggsave(Firth_Estimate_Grid_H,
       filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_Estimates_2x3.jpeg",
       width = 14, height = 10, dpi = 300)

Firth_Estimate_Grid_H

```

```{r Firth - Estimates - Vertical}

Plot_x_label_Est <- ggplot() +
  labs(x = "Estimates (Log Odds)") +
  theme_void() +
  theme(axis.title.x  = element_text(face = "bold", size = 12),
        plot.margin   = margin(t = 0, r = 0, b = 0, l = 10))

Firth_Estimate_Grid_V <- wrap_plots(
  wrap_plots(Estimate_Plots, ncol = 3, nrow = 2, guides = "collect"),
  Plot_x_label_Est,
  ncol = 1,
  heights = c(10, 1),    
  guides = "collect") +
  plot_annotation(title = "Firth-Penalized Logistic Regression", 
                  theme = theme(plot.title.position = "plot",
                  plot.title = element_text(face = "bold",
                                            size = 16, 
                                            hjust = 0))) &
  theme(legend.position = "right")

ggsave(Firth_Estimate_Grid_V,
  filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_Estimates_3x2.jpeg",
  width = 14, height = 10, dpi = 300)

Firth_Estimate_Grid_V

```

```{r}

Firth_OR_Grid_H <- wrap_plots(OR_Plots,
                                  ncol = 3,
                                  nrow = 2,         
                                  guides = "collect")   +
  plot_annotation(title = "Firth-Penalized Logistic Regression\nOdds Ratio", 
                  theme = theme(plot.title.position = "plot",
                  plot.title = element_text(face = "bold",
                                            size = 16, 
                                            hjust = 0))) &
  theme(legend.position = "bottom", 
        legend.justification = c("center", "bottom"),        
        legend.box = "horizontal",      
        legend.direction = "horizontal", 
        plot.margin = margin(t = 5, r = 20, b = 5, l = 5))

ggsave(Firth_OR_Grid_H,
  filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_OR_2x3.jpeg",
  width = 14, height = 10, dpi = 300)

Firth_OR_Grid_H

```


```{r}

Plot_x_label_OR <- ggplot() +
  labs(x = "Odds Ratio") +
  theme_void() +
  theme(axis.title.x  = element_text(face = "bold", size = 12),
        plot.margin   = margin(t = 0, r = 0, b = 0, l = 10))

Firth_OR_Grid_V <- wrap_plots(
  wrap_plots(OR_Plots, ncol = 2, nrow = 3, guides = "collect"),
  Plot_x_label_OR,
  ncol = 1,
  heights = c(10, 1),    
  guides = "collect") +
  plot_annotation(title = "Firth-Penalized Logistic Regression", 
                  theme = theme(plot.title.position = "plot",
                  plot.title = element_text(face = "bold",
                                            size = 16, 
                                            hjust = 0))) &
  theme(legend.position = "right")

ggsave(Firth_OR_Grid_V,
  filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_OR_3x2.jpeg",
  width = 14, height = 10, dpi = 300)

Firth_OR_Grid_V

```
