```{r Libraries}

## Load the libraries ##
library(tidyverse)
library(ggtext)
library(ggplot2)
library(ggrepel)
library(writexl)

Pallete <- c("coral1", "deeppink3", "midnightblue", "cyan3", "mediumspringgreen", "yellow3")

```

```{r Load the data}

FCR_Values <- read_csv(file = "~/SLE/Glycans/Output_Data/Glycans_logfc.csv")
Test_Results <- read_csv(file = "~/SLE/Glycans/Output_Data/Glycans_test_results.csv")

```


```{r Prep for the volcanos}

FCR_Values_clean <- FCR_Values %>% 
  inner_join(Test_Results %>% select(Marker, p.value, FDR), by = "Marker") %>% 
  mutate(p_value_log10 = -log10(p.value), 
         FDR_log10 = -log10(FDR), 
         Significance = if_else(p.value < 0.05, "Significant", "Not Significant"), 
         Significance_FDR = if_else(FDR < 0.05, "Significant", "Not Significant"), 
         Marker = str_remove(Marker, "^[^_]+_"), 
         Origin = recode(Origin, Serum = "Serum<br>proteome", .default = Origin)) 

Top_Glycans_nadj <- FCR_Values_clean %>%
  arrange(p.value) %>% 
  head(25)

Top_Glycans_FDR <- FCR_Values_clean %>%
  arrange(FDR) %>% 
  head(25)

Sign_Glycans_FDR_total <- FCR_Values_clean %>% 
  filter(FDR < 0.05)

y_breaks_nadj <- pretty(range(FCR_Values_clean$p_value_log10), n = 3)
y_breaks_FDR <- pretty(range(FCR_Values_clean$FDR_log10), n = 3)

# write_csv(FCR_Values_clean, file = "~/SLE/Glycans/Output_Data/Figure_1_logFC/Glycans_logFC.csv")
# write_xlsx(x = FCR_Values_clean, 
#            path = "~/SLE/Glycans/Output_Data/Figure_1_logFC/Figure_1_Glycans_volcano.xlsx")

```

```{r Volcano visualisation}

Volcano_nadj <- ggplot(FCR_Values_clean, aes(x = log2FC, y = p_value_log10)) +
    geom_point(aes(color = Origin, alpha = Significance), size = 2) +
    scale_alpha_manual(values = c("Significant" = 1.0, 
                                  "Not Significant" = 0.3), 
                                  guide = "none") +
  scale_colour_manual(values = Pallete) +
  scale_x_continuous(limits = c(-1, 1), 
                     breaks = seq(-1, 1, by = 0.5), 
                     expand = c(0, 0)) +
  scale_y_continuous(limits = c(min(y_breaks_nadj), max(y_breaks_nadj)), 
                     breaks = y_breaks_nadj, 
                     expand = c(0, 0)) +  
  labs(title = "Glycan expression change over a 12 month period", 
         x = "Fold Change (log<sub>2</sub>FC)", 
         y = "P value (-log<sub>10</sub>)", 
         caption = paste0("<b>P value:</b> Not adjusted
         <br><b>Number of significant markers:</b> ", 
         FCR_Values_clean %>% 
           filter(p.value < 0.05) %>% 
           nrow(), "</br>")) + 
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +  
  geom_vline(xintercept = 0, linetype = "dashed", color = "black") +  
  theme_minimal(base_size = 14, base_family = "sans") +
  theme(plot.title = element_markdown(hjust = 0.5, face = "bold", size = 14),
        legend.title = element_blank(), 
        legend.text = element_markdown(face = "bold"),
        axis.title.x = element_markdown(face = "bold"), 
        axis.title.y = element_markdown(face = "bold"), 
        plot.caption.position = "plot", 
        plot.caption = element_markdown(hjust = 0.9, vjust = 1),
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_blank()) +
  geom_text_repel(data = Top_Glycans_nadj, aes(label = Marker), 
                  size = 3, 
                  force = 2,
                  box.padding = 0.3, 
                  point.padding = 0.1, 
                  segment.color = NA, 
                  max.overlaps = Inf, 
                  min.segment.length = 0)

Volcano_FDR <- ggplot(FCR_Values_clean, aes(x = log2FC, y = FDR_log10)) +
    geom_point(aes(color = Origin, alpha = Significance_FDR), size = 2) +
    scale_alpha_manual(values = c("Significant" = 1.0, 
                                  "Not Significant" = 0.3), 
                                  guide = "none") +
  scale_colour_manual(values = Pallete) +
  scale_x_continuous(limits = c(-1, 1), 
                     breaks = seq(-1, 1, by = 0.5), 
                     expand = c(0, 0)) +
  scale_y_continuous(limits = c(min(y_breaks_FDR), max(y_breaks_FDR)), 
                     breaks = y_breaks_FDR, 
                     expand = c(0, 0)) +  
    labs(title = "Glycan expression change over a 12 month period", 
         x = "Fold Change (log<sub>2</sub>FC)", 
         y = "P value (-log<sub>10</sub>)", 
         caption = paste0("<b>P value:</b> FDR adjusted
         <br><b>Number of significant markers:</b> ", 
         FCR_Values_clean %>% 
           filter(FDR < 0.05) %>% 
           nrow(), "</br>")) +   
    geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +  
    geom_vline(xintercept = 0, linetype = "dashed", color = "black") +  
    theme_minimal(base_size = 12, base_family = "sans") +
    theme(plot.title = element_markdown(hjust = 0.5, face = "bold", size = 14),
          legend.title = element_blank(), 
          legend.text = element_markdown(face = "bold"),
          axis.title.x = element_markdown(face = "bold"), 
          axis.title.y = element_markdown(face = "bold"), 
          plot.caption.position = "plot", 
          plot.caption = element_markdown(hjust = 0.9, vjust = 1),
          panel.grid.major = element_line(color = "grey90"),
          panel.grid.minor = element_blank()) +
  geom_text_repel(data = Sign_Glycans_FDR_total, aes(label = Marker), 
                  size = 3, 
                  force = 2,
                  box.padding = 0.3, 
                  point.padding = 0.1, 
                  segment.color = NA, 
                  max.overlaps = Inf, 
                  min.segment.length = 0)

# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_1_Volcano/Volcano_nadj.jpeg"),
#        plot = Volcano_nadj, width = 10, height = 8, dpi = 300, device = "jpeg")
# 
# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_1_Volcano/Volcano_FDR_all_glycans_font12.jpeg"),
#        plot = Volcano_FDR, width = 10, height = 8, dpi = 300, device = "jpeg")

```