```{r Libraries}

## Load the libraries ##
library(tidyverse)
library(readxl)
library(purrr)
library(broom)
library(ggtext)
library(ggplot2)
library(broom.helpers)
library(writexl)
library(patchwork)
library(grid)

```

```{r Load the data}

Marker_DF <- read_csv(file = "~/SLE/Glycans/Output_Data/Glycans_marker_data_total.csv") %>% 
  rename(Marker_Value = "Value") 

Comp_DF <- read_csv(file = "~/SLE/Glycans/Output_Data/Comparator_values_long.csv") %>% 
  rename(Comp_Value = "Value") 

Comparisons <- tribble(~Time_1, ~Time_2, ~Label, 
                       "T0", "T0", "Baseline vs Baseline", 
                       "T12", "T12", "Month 12 vs Month 12",
                       "T0", "T12", "Baseline vs Month 12")

Comparator_Levels <- c("AI", "CI", "eGFR", "UPCR", "SLEDAI-2K")

```


```{r Marker - Comparator correlations}

Run_Cors <- function(Time_1, Time_2, Label) {
  joined <- Marker_DF %>%
    filter(Time_point == Time_1) %>%
    select(ID, Marker, Marker_Value) %>%
    inner_join(Comp_DF %>% 
                 filter(Time_point == Time_2) %>% 
                 select(ID, Comparator, Comp_Value),
               by = "ID", relationship = "many-to-many")
  
  joined %>%
    group_by(Marker, Comparator) %>%
    summarize(broom::tidy(cor.test(Marker_Value, Comp_Value, 
                                   method = "spearman", 
                                   exact = FALSE)),
              .groups = "drop") %>%
    mutate(Comparison = Label)
}

Correlation_Results_Total <- Comparisons %>%
  pmap_dfr(~ Run_Cors(..1, ..2, ..3)) 

Correlation_Results_Clean <-  Correlation_Results_Total %>% 
  group_by(Comparison) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr"), 
         Significance = case_when(p.value < 0.05 ~ "*"), 
         Origin = sub("_.*$", "", Marker), 
         Comparator = factor(Comparator, levels = Comparator_Levels), 
         Comparison = factor(Comparison, levels = c("Baseline vs Baseline", "Month 12 vs Month 12", "Baseline vs Month 12"))) %>% 
  rename(Correlation = "estimate")
  
# write_csv(Correlation_Results_Clean, 
#           file = "~/SLE/Glycans/Output_Data/Figure_2_Clinical_Cors/Glycan_Clinical_Correlations.csv")

```

```{r Correlations visualisation}

## Load the file in case you dont want to run the analysis ##
Correlation_Results_Clean <- read_csv(file = "~/SLE/Glycans/Output_Data/Glycan_Comp_Correlations.csv")

## Visualise the heatmap ##
Main_plot <- ggplot(Correlation_Results_Clean, aes(x = Comparator, y = Marker, fill = Correlation)) +
  geom_tile(color = "white", width = 1, height = 1) +
  scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                       midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                       guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                              title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
  facet_grid(Origin ~ Comparison, scales = "free_y", space = "free_y", 
             labeller = labeller(Origin = function(x) 
               ifelse(x == "Serum", "Serum<br>Proteome", x))) +
  # geom_text(aes(label = round(Correlation, 2)), size = 3) +
  geom_text(aes(label = Significance, vjust = 0, hjust = 0.5, fontface = "bold")) +
  scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), expand = c(0,0)) +
  scale_x_discrete(labels = function(x) {
    x <- gsub("_", " ", x)
    x <- gsub("Extra Renal", "Extra<br>Renal", x)
    x <- gsub("Renal Impairment", "Renal<br>Impairment", x)
    x }, expand = c(0,0)) +
  labs(title = "Heatmap of marker correlations compared to clicinal indices", x = NULL, y = NULL, 
       # caption = paste0("Correlation coefficient used: <b>Spearman</b> ")
       ) +
  theme_minimal(base_size = 12, base_family = "sans") +
  theme(strip.placement = "outside",
        strip.text.y.right = element_markdown(angle = 0, hjust = 0.5, vjust = 0.5, face  = "bold"),
        axis.text.x = element_markdown(angle = 0, hjust = 0.5, 
                                       # face = "bold", 
                                       colour = "black"), 
        axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
        panel.grid  = element_blank(), 
        panel.spacing = unit(1, "lines"), 
        plot.caption.position = "plot", 
        plot.caption = element_markdown(hjust = 0.9, vjust = 1),
        plot.title = element_text(face = "bold"))

# ggsave(Main_plot,
#        filename = "~/SLE/Glycans/Plots_2/Figure_2_Correlations_Total/Correlations_total.jpeg",
#        width = 15, height = 25, dpi = 300)

## Removed from caption: <br>P value: <b>Not adjusted</b> ##

```

```{r Correlation plots by Origin}
# 
# Correlation_Results_Clean_Sign <- Correlation_Results_Clean %>%
#   group_by(Marker) %>% 
#   filter(any(Significance == "*")) %>% 
#   ungroup()
# 
# Cor_Range <- Correlation_Results_Clean_Sign %>% 
#   summarise(min_corr = min(Correlation, na.rm = TRUE), 
#             max_corr = max(Correlation, na.rm = TRUE))
# 
# Sub_Correlation_plots <- function(orig) {
# 
#   max_len <- max(nchar(Correlation_Results_Clean_Sign$Marker))
#   
#   Cor_df_current <- Correlation_Results_Clean_Sign %>% 
#     filter(Origin == orig)
# 
#   Current_Title <- if (orig == "Serum") {"Serum proteome"} 
#   else { orig }
#   
#   n_markers <- Cor_df_current %>% 
#     distinct(Marker) %>% 
#     nrow()
#   
#   n_comp <- Cor_df_current %>% 
#     distinct(Comparator) %>% 
#     nrow()
#   
#   Main_plot_current <- ggplot(Cor_df_current, aes(x = Comparator, y = Marker, fill = Correlation)) +
#     geom_tile(color = "white", width = 1, height = 1) +
#     scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
#                          limits = c(Cor_Range$min_corr, Cor_Range$max_corr), 
#                          midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
#                          guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
#                                                 title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
#     facet_wrap(~Comparison, nrow = 1) +
#     geom_text(aes(label = Significance, vjust = 0.5, hjust = 0.5, fontface = "bold")) +
#     scale_y_discrete(labels = function(x) { 
#       labs <- gsub("^[^_]*_", "", x) 
#       padded <- str_pad(labs, width = max_len, side = "left", pad = "\u00A0")
#       padded}, expand = c(0,0)) +
#     scale_x_discrete(labels = function(x) {
#       x <- gsub("_", " ", x)
#       x <- gsub("Extra Renal", "Extra<br>Renal", x)
#       x <- gsub("Renal Impairment", "Renal<br>Impairment", x)
#       x }, expand = c(0,0)) +
#     labs(title = paste0("Heatmap of marker correlations compared to clicinal indices
#                         <br>Origin: ", Current_Title), x = NULL, y = NULL,
#          # caption = paste0("Correlation coefficient used: <b>Spearman</b> ")
#          ) +
#     theme_minimal(base_size = 12, base_family = "sans") +
#     theme(strip.placement = "outside",
#           strip.text.y.left = element_blank(),
#           strip.text.x.top = element_text(size = 11, face = "bold", colour = "black"),
#           axis.text.x = element_markdown(size = 11, angle = 0, hjust = 0.5, 
#                                          # face = "bold", 
#                                          colour = "black", 
#                                          margin = margin(t = 10, unit = "pt")), 
#           axis.text.y = element_text(size = 11, face = "bold", colour = "black", margin = margin(r = 10, unit = "pt"), hjust = 1),
#           panel.grid  = element_blank(), 
#           panel.spacing = unit(1, "lines"), 
#           plot.title = element_markdown(face = "bold", lineheight = 1.2),
#           aspect.ratio = n_markers/n_comp * 0.3,
#           plot.caption.position = "plot", 
#           plot.caption = element_markdown(size = 10, hjust = 0.9, vjust = 1),
#           plot.margin = margin(10, 10, 10, 10, "pt")) + 
#     coord_fixed()
# 
#   plot_height <- max(n_markers * 0.3, 4)
#   
#   # ggsave(Main_plot_current,
#   #      filename = paste0("~/SLE/Glycans/Plots_2/Figure_2_Correlations_Total/Correlations_", orig,".jpeg"),
#   #      width = 15,
#   #      height = 10,
#   #      dpi = 300)
#   
#   Main_plot_current
# }
# 
# plots_by_origin <- map(unique(Correlation_Results_Clean$Origin), Sub_Correlation_plots)

## Removed from caption: <br>P value: <b>Not adjusted</b> ##
```

```{r Correlations visualisation - Significant only}

Main_plot <- ggplot(Correlation_Results_Clean_Sign, aes(x = Comparator, y = Marker, fill = Correlation)) +
  geom_tile(color = "white", width = 1, height = 1) +
  scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                       midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                       guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                              title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
  facet_grid(Origin ~ Comparison, scales = "free_y", space = "free_y", 
             labeller = labeller(Origin = function(x) 
               ifelse(x == "Serum", "Serum<br>proteome", x))) +
  # geom_text(aes(label = round(Correlation, 2)), size = 3) +
  geom_text(aes(label = Significance, vjust = 0.5, hjust = 0.5, fontface = "bold")) +
  scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), expand = c(0,0)) +
  scale_x_discrete(labels = function(x) {
    x <- gsub("_", " ", x)
    x <- gsub("Extra Renal", "Extra<br>Renal", x)
    x <- gsub("Renal Impairment", "Renal<br>Impairment", x)
    x }, expand = c(0,0)) +
  labs(title = "Heatmap of marker correlations compared to clicinal indices", x = NULL, y = NULL
       # caption = paste0("Correlation coefficient used: <b>Spearman</b> 
       # <br>P value: <b>Not adjusted</b>")
       ) +
  theme_minimal(base_size = 12, base_family = "sans") +
  theme(strip.placement = "outside",
        strip.text.y.right = element_markdown(size = 11, angle = 0, hjust = 0, vjust = 0.5, face  = "bold", margin = margin(l = 10)),
        axis.text.x = element_markdown(angle = 0, hjust = 0.5, size = 11,
                                       # face = "bold", 
                                       colour = "black"), 
        axis.text.y = element_text(size = 11, face = "bold", colour = "black"),
        panel.grid  = element_blank(), 
        panel.spacing = unit(1, "lines"), 
        plot.caption.position = "plot", 
        plot.caption = element_markdown(hjust = 0.9, vjust = 1),
        plot.title = element_text(face = "bold"))

# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_2_Correlations_Total/Correlations_significant_A4.jpeg",
#        plot = Main_plot, width = 210, height = 297, units = "mm", scale = 2, dpi = 300)

```


```{r Correlation plots by Origin but combine them}

Correlation_Results_Clean_Sign <- Correlation_Results_Clean %>%
  group_by(Marker) %>% 
  filter(any(Significance == "*")) %>% 
  ungroup()

Cor_Range <- Correlation_Results_Clean_Sign %>% 
  summarise(min_corr = min(Correlation, na.rm = TRUE), 
            max_corr = max(Correlation, na.rm = TRUE))

Correlation_Results_Clean_Sign <- Correlation_Results_Clean_Sign %>% 
  separate(col = Marker, into = c("Origin", "Marker"), sep = "_", extra = "merge", fill = "right") 

max_len <- Correlation_Results_Clean_Sign %>%
  pull(Marker) %>%
  nchar() %>%
  max(na.rm = TRUE)

Correlation_Results_Clean_Sign <- Correlation_Results_Clean_Sign %>% 
  mutate(Marker = str_pad(Marker, width = max_len, side = "left", pad = "\u00A0")) 

Sub_Correlation_plots_2 <- function(orig) {

  max_len <- max(nchar(Correlation_Results_Clean_Sign$Marker))
  
  Cor_df_current <- Correlation_Results_Clean_Sign %>% 
    filter(Origin == orig)

  Current_Title <- if (orig == "Serum") {"Serum proteome"} 
  else { orig }
  
  n_markers <- Cor_df_current %>% 
    distinct(Marker) %>% 
    nrow()
  
  n_comp <- Cor_df_current %>% 
    distinct(Comparator) %>% 
    nrow()
  
  Main_plot_current <- ggplot(Cor_df_current, aes(x = Comparator, y = Marker, fill = Correlation)) +
    geom_tile(color = "white", width = 1, height = 1) +
    scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                         limits = c(Cor_Range$min_corr, Cor_Range$max_corr), 
                         midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                         guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                                title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
    facet_wrap(~Comparison, nrow = 1) +
    geom_text(aes(label = Significance, vjust = 0.5, hjust = 0.5, fontface = "bold")) +
    scale_y_discrete(expand = c(0,0)) +
    scale_x_discrete(expand = c(0,0)) +
    labs(title = paste0("Origin: ", Current_Title), x = NULL, y = NULL,
         # caption = paste0("Correlation coefficient used: <b>Spearman</b> ")
         ) +
    theme_minimal(base_size = 12, base_family = "sans") +
    theme(strip.placement = "outside",
          strip.text.y.left = element_blank(),
          strip.text.x.top = element_text(size = 11, face = "bold", colour = "black"),
          axis.text.x = element_markdown(size = 9, angle = 0, hjust = 0.5, 
                                         # face = "bold", 
                                         colour = "black", 
                                         margin = margin(t = 10, unit = "pt")), 
          axis.text.y = element_text(size = 11, face = "bold", colour = "black", margin = margin(r = 10, unit = "pt"), hjust = 1),
          panel.grid  = element_blank(), 
          panel.spacing = unit(1, "lines"), 
          plot.title = element_markdown(face = "bold", lineheight = 1.2),
          aspect.ratio = n_markers/n_comp * 0.3,
          plot.caption.position = "plot", 
          plot.caption = element_markdown(size = 10, hjust = 0.9, vjust = 1),
          plot.margin = margin(10, 10, 10, 10, "pt")) + 
    coord_fixed()

  plot_height <- max(n_markers * 0.3, 4)
  
  Main_plot_current
}

## Removed from caption: <br>P value: <b>Not adjusted</b> ##
```

```{r}

plots_by_origin <- map(origins, Sub_Correlation_plots_2)

origins <- Correlation_Results_Clean_Sign %>% 
  distinct(Origin) %>% 
  pull(Origin)

order_idx <- c(1, 6, 3, 4, 2, 5)
plots_reorder <- plots_by_origin[order_idx]

## Pull them out into named objects ##
p1 <- plots_reorder[[1]]  # origin 1
p6 <- plots_reorder[[2]]  # origin 6
p3 <- plots_reorder[[3]]  # origin 3
p4 <- plots_reorder[[4]]  # origin 4
p2 <- plots_reorder[[5]]  # origin 2
p5 <- plots_reorder[[6]]  # origin 5

m_top <- margin(t = 0, r = 5, b = 5, l = 5)
m_mid <- margin(t = 5, r = 5, b = 5, l = 5)  
m_bottom <- margin(t = 5, r = 5, b = 0, l = 5)

p1 <- p1 + theme(plot.title.position = "panel", plot.margin = m_top)
p2 <- p2 + theme(plot.title.position = "panel", plot.margin = m_mid)
p3 <- p3 + theme(plot.title.position = "panel", plot.margin = m_bottom)
p4 <- p4 + theme(plot.title.position = "panel", plot.margin = m_top)
p5 <- p5 + theme(plot.title.position = "panel", plot.margin = m_mid)
p6 <- p6 + theme(plot.title.position = "panel", plot.margin = m_bottom)

# 1) compute row‐counts for p1 and p2:
n1 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[1]) %>%     # or whatever origin gives p1
  distinct(Marker) %>% nrow()

n2 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[2]) %>%     # origin for p2
  distinct(Marker) %>% nrow()

n3 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[3]) %>%     # origin for p2
  distinct(Marker) %>% nrow()

n4 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[4]) %>%     # or whatever origin gives p1
  distinct(Marker) %>% nrow()

n5 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[5]) %>%     # origin for p2
  distinct(Marker) %>% nrow()

n6 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[6]) %>%     # origin for p2
  distinct(Marker) %>% nrow()


```



```{r}

library(patchwork)
library(grid)  

# assume p1…p6 and n1…n6 are already defined

left_col  <- wrap_plots(p1, p2, p3, ncol = 1, heights = c(n1, n2, n3))

right_col <- wrap_plots(p4, p5, p6, ncol = 1, heights = c(n4, n5, n6)) 

final_plot <- wrap_plots(
  
  # wrap_plots(p1, p2, p3, ncol = 1, heights = c(n1, n2, n3)),
  # wrap_plots(p4, p5, p6, ncol = 1, heights = c(n4, n5, n6)),
  
  left_col, 
  right_col,
  
  ncol = 2,
  # heights = c(n1, n2, n3),
  guides = "collect") +
  plot_annotation(
    
    tag_levels = "A",   
  theme = theme(
    plot.title = element_text(face = "bold", size = 23),
    plot.title.position = "plot", 
    plot.title.hjust = 0.5,       
    plot.tag = element_text(face = "bold", colour = "black", size = 30))) &
  theme(
    legend.position = "right",
    legend.title = element_text(face = "bold"),
    legend.key.width = unit(2, "lines"),
    legend.key.height = unit(4, "lines"),    
    legend.spacing.y = unit(0.5, "lines"))

final_plot_final <- final_plot +
  plot_annotation(title = "Heatmap of marker correlations compared to clicinal indices") & 
  theme(plot.tag = element_text(color = "black", face = "bold", size = 30))

# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_2_Correlations_Total/Cor_per_origin_combined.jpeg",
#        plot = final_plot_final, width = 30, height = 18, dpi = 300)

```
