```{r Libraries}

## Load the libraries ##
library(tidyverse)
library(readxl)
library(purrr)
library(broom)
library(ggtext)
library(patchwork)

```

```{r Load the data}

AGP_Data <- read_xlsx("~/SLE/Glycans/Data/LN_AGP_glycopeptide-data.xlsx")
C3_Data <- read_xlsx("~/SLE/Glycans/Data/LN_C3_glycopeptide_data.xlsx")
Serum_Data <- read_xlsx("~/SLE/Glycans/Data/LN_serum_glycome_data.xlsx")
Decreased_data <- read_xlsx("~/SLE/Glycans/Data/decreased.xlsx")
Increased_data <- read_xlsx("~/SLE/Glycans/Data/increased.xlsx")
IgG_FAB_Data <- read_xlsx("~/SLE/Glycans/Data/LN_total_IgG_Fab_data.xlsx")
IgG_FC_Data <- read_xlsx("~/SLE/Glycans/Data/LN_total_IgG_Fc_data.xlsx")
IgG_Meta <- read_xlsx("~/SLE/Glycans/Data/LN_total_IgG_glycomedata.xlsx")


```


```{r Prep slightly}

Comparators <- c("AI", "CI", "S-creatinine", "eGFR", "UPCR", "albumin", "extra-renal", "Renal Impairment")

Comparator_Values <- Increased_data %>%
  rename(ID = `Patient number`, Time_point = `Time point`) %>%
  select(ID, Time_point, any_of(Comparators)) %>%
  rename(SLEDAI2K = `Renal Impairment`,
         SLEDAI2K_extra = `extra-renal`,
         S_creatinine = `S-creatinine`) %>%
  mutate(Identification = paste0(ID, " ", Time_point)) %>%
  select(-c(ID, Time_point)) %>%
  select(Identification, everything()) %>%
  column_to_rownames("Identification") %>%
  mutate(AI = as.numeric(AI),
         CI = as.numeric(CI))

```

```{r Make dtaaframes long}

Dataframes <- list(AGP = AGP_Data, 
                   C3 = C3_Data, 
                   Serum = Serum_Data,
                   Fab = IgG_FAB_Data, 
                   Fc = IgG_FC_Data)

Process_DFs <- function(df){
  df %>% 
    select(-c(Sample, `ID_St Luc`)) %>% 
    rename(ID = `Patient number`, Time_point = `Time point`) %>% 
    mutate(across(.cols = -c(ID, Time_point), .fns  = as.numeric)) %>% 
    pivot_longer(cols = -c(ID, Time_point), names_to   = "Marker", values_to  = "Value")
}

Long_Dataframes <- map(Dataframes, Process_DFs)

```

```{r Get the direction of each marker}

Directions_List <- imap(Long_Dataframes, ~ {
  df <- .x
  prefix <- .y
  
  df %>% 
    mutate(Marker_Timepoint = paste0(Marker, Time_point)) %>%
    group_by(Marker_Timepoint) %>%
    summarise(Mean = mean(Value, na.rm = TRUE), .groups = "drop") %>%
    extract(col = Marker_Timepoint, 
          into = c("Marker", "Timepoint"), 
          regex = "(.+)(T0|T12)$") %>% 
    pivot_wider(names_from = "Timepoint", values_from = "Mean") %>% 
    mutate(Direction = case_when(T12 > T0 ~ "Increase", 
                                 T12 < T0 ~ "Decrease", 
                                 TRUE ~ NA), 
           Marker = paste0(prefix, "_", Marker),
           Origin = prefix) %>% 
    select(Marker, Direction, Origin)
})

Directions <- bind_rows(Directions_List)

```

```{r Perform the tests}

Paired_Tests <- function(df){ df %>% 
  pivot_wider(names_from = "Time_point", values_from = "Value", names_prefix = "Value_") %>% 
  group_by(Marker) %>% 
  summarise(Pairs = n_distinct(ID),
            Test = list(wilcox.test(Value_T12, 
                                    Value_T0, 
                                    paired = TRUE, 
                                    exact = FALSE)), 
                        .groups = "drop") %>% 
  mutate(Results = map(Test, broom::tidy)) %>% 
  unnest(Results) %>% 
  select(Marker, Pairs, statistic, p.value, method)
}

Test_Results <- imap(Long_Dataframes, ~Paired_Tests(.x) %>% 
                       mutate(Marker = paste0(.y, "_", Marker)))

Test_Results <- bind_rows(Test_Results, .id = "Origin")

```

```{r Combine the direction with the tests}

Results_Total <- Test_Results %>% inner_join(Directions, by = c("Origin", "Marker"))

Dataframes_Final <- imap(
  Long_Dataframes, ~ .x %>% 
      mutate(Marker = paste0(.y, "_", Marker), 
             Origin = .y)) %>% 
  bind_rows(., .id = "Origin") %>% 
  select(ID, Origin, everything())

Results_Sign <- Results_Total %>% 
  filter(p.value < 0.05)

Dataframes_Final_Sign <- Dataframes_Final %>% 
  filter(Marker %in% Results_Sign$Marker)

```

```{r Correlation analysis}

Dataframes_Final_Sign_Wide <- Dataframes_Final_Sign %>% 
  mutate(ID = paste0(ID, " ", Time_point)) %>% 
  select(-c(Time_point, Origin)) %>% 
  pivot_wider(id_cols = ID, names_from = "Marker", values_from = "Value") %>% 
  column_to_rownames(var = "ID")

# Correlations <- cor(Dataframes_Final_Sign_Wide, 
#                     Comparator_Values, 
#                     method = "spearman", 
#                     use = "pairwise.complete.obs") %>% 
#   as.data.frame() %>%
#   rownames_to_column(var = "Marker") %>% 
#   pivot_longer(cols = -Marker, 
#                names_to = "Variable", 
#                values_to = "Correlation") %>% 
#   mutate(Origin = sub("_.*$", "", Marker)) %>% 
#   inner_join(Directions, by = c("Marker", "Origin"))


DFs_Combined <- cbind(Dataframes_Final_Sign_Wide, Comparator_Values)

Correlations <- expand_grid(Marker = colnames(Dataframes_Final_Sign_Wide), 
              Variable = colnames(Comparator_Values)) %>% 
  mutate(test = map2(Marker, Variable, ~ cor.test(DFs_Combined[[.x]], DFs_Combined[[.y]], 
                                                  method = "spearman", exact  = FALSE)),
         rho     = map_dbl(test, "estimate"), 
         p.value = map_dbl(test, "p.value", )) %>%
  mutate(P_adjust = p.adjust(p.value, method = "BH")) %>% 
  select(-test) %>% 
  mutate(Origin = sub("_.*$", "", Marker)) %>% 
  inner_join(Directions, by = c("Marker", "Origin")) %>% 
  rename(Correlation = "rho") %>% 
  mutate(Significance = case_when(p.value < 0.05 ~ "*"))


```

```{r Correlations visualisation}

Main_plot <- ggplot(Correlations, aes(x = Variable, y = Marker, fill = Correlation)) +
  geom_tile(color = "white", width = 1, height = 1) +
  scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                       midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                       guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                              title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
  facet_grid(Origin ~., scales = "free_y", space = "free_y", switch = "x") +
  # geom_text(aes(label = round(Correlation, 2)), size = 3) +
  geom_text(aes(label = Significance, vjust = 0.5, hjust = 0.5, fontface = "bold")) +
  scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), expand = c(0,0)) +
  scale_x_discrete(labels = function(x) {
    x <- gsub("_", " ", x)
    x <- gsub("SLEDAI2K extra", "SLEDAI2K<br>extra", x)
    x }, expand = c(0,0)) +
  labs(title = "Heatmap of Glycan Correlations", x = NULL, y = NULL) +
  theme_minimal(base_size = 12) +
  theme(strip.placement = "outside",
        strip.text.y.right = element_blank(),
        axis.text.x = element_markdown(angle = 0, hjust = 0.5, face = "bold", colour = "black"), 
        axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
        panel.grid  = element_blank(), 
        panel.spacing = unit(1, "lines"), 
        plot.title = element_text(face = "bold"))

Dir_plot <- Correlations %>%
  distinct(Origin, Marker, Direction) %>% 
  ggplot(., aes(x = 1, y = Marker, fill = Direction)) +
  geom_tile(color = "white", width = 1, height = 1) +
  facet_grid(Origin ~ ., scales = "free_y", space  = "free_y", switch = "x") +
  scale_fill_manual(values = c("Increase" = "mediumspringgreen",
                               "Decrease" = "purple", 
                               "No change"  = "grey80"), 
                    guide = guide_legend(order = 2, title.position = "top", 
                                         title = "T12 vs T0", title.theme = element_markdown(face = "bold", size = 12), 
                                         title.hjust = 0, label.position = "right", 
                                         keywidth = unit(0.5, "cm"), keyheight = unit(0.4, "cm"))) +
  scale_y_discrete(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  theme_void() +
  theme(strip.text.y.right = element_text(angle = 0, hjust = 0, vjust = 0.5, face  = "bold", margin = margin(l = 10)),
        plot.margin = margin(0, 0, 0, 0), 
        panel.spacing.x = unit(0, "lines"),
        panel.spacing = unit(1, "lines"))

Combined_Plot <- Main_plot + Dir_plot +
  plot_layout(widths = c(0.95, 0.05), 
              # widths = c(length(unique(Correlations$Variable)), 1), 
              guides = "collect") +   
  plot_annotation(theme = theme(plot.margin = margin(0, 0, 0, 0))) &
  theme(legend.box = "vertical", 
        legend.position = "right",
        legend.title.position = "bottom")

# ggsave(Combined_Plot, filename = "~/SLE/Glycans/Plots/Glycans_Correlations.jpeg", width = 10, height = 16, dpi = 300)

```


```{r Delta calculation and correlation}

Dataframes_Delta <- Dataframes_Final %>% 
  group_by(ID, Marker) %>% 
  mutate(Delta = order_by(Time_point, Value - lag(Value))) %>%
  mutate(Delta = ifelse(is.na(Delta), 0, Delta)) %>% 
  filter(Time_point == "T12") %>% 
  select(-c(Time_point, Value, Origin)) %>% 
  pivot_wider(id_cols = ID, names_from = Marker, values_from = Delta) %>% 
  column_to_rownames(var = "ID")

Comparator_Values_Delta <- Increased_data %>%
  rename(ID = `Patient number`, Time_point = `Time point`) %>%
  select(ID, Time_point, any_of(Comparators)) %>%
  rename(SLEDAI2K = `Renal Impairment`,
         SLEDAI2K_extra = `extra-renal`,
         S_creatinine = `S-creatinine`) %>%
  mutate(AI = as.numeric(AI),
         CI = as.numeric(CI)) %>% 
  pivot_longer(cols = -c(ID, Time_point), names_to = "Marker", values_to = "Value") %>% 
  group_by(ID, Marker) %>% 
  mutate(Delta = order_by(Time_point, Value - lag(Value))) %>%
  mutate(Delta = ifelse(is.na(Delta), 0, Delta)) %>% 
  filter(Time_point == "T12") %>% 
  select(ID, Marker, Delta) %>% 
  pivot_wider(id_cols = "ID", names_from = "Marker", values_from = "Delta") %>% 
  column_to_rownames(var = "ID")

DFs_Delta_Combined <- cbind(Dataframes_Delta, Comparator_Values_Delta) 

Correlations_Delta <- expand_grid(Marker = colnames(Dataframes_Delta), 
              Variable = colnames(Comparator_Values_Delta)) %>% 
  mutate(test = map2(Marker, Variable, ~ cor.test(DFs_Delta_Combined[[.x]], DFs_Delta_Combined[[.y]], 
                                                  method = "spearman", exact  = FALSE)),
         rho     = map_dbl(test, "estimate"), 
         p.value = map_dbl(test, "p.value", )) %>%
  mutate(P_adjust = p.adjust(p.value, method = "BH")) %>% 
  select(-test) %>% 
  mutate(Origin = sub("_.*$", "", Marker)) %>% 
  inner_join(Directions, by = c("Marker", "Origin")) %>% 
  rename(Correlation = "rho") %>% 
  mutate(Significance = case_when(p.value < 0.05 ~ "*"))


```

```{r Correlations visualisation for the Deltas}

Main_plot_Delta <- ggplot(Correlations_Delta, aes(x = Variable, y = Marker, fill = Correlation)) +
  geom_tile(color = "white", width = 1, height = 1) +
  scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                       midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                       guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                              title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
  facet_grid(Origin ~., scales = "free_y", space = "free_y", switch = "x") +
  # geom_text(aes(label = round(Correlation, 2)), size = 3) +
  geom_text(aes(label = Significance, vjust = 0.8, hjust = 0.5, fontface = "bold")) +
  scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), expand = c(0,0)) +
  scale_x_discrete(labels = function(x) {
    x <- gsub("_", " ", x)
    x <- gsub("SLEDAI2K extra", "SLEDAI2K<br>extra", x)
    x }, expand = c(0,0)) +
  labs(title = "Heatmap of Glycan Deltas Correlations", x = NULL, y = NULL) +
  theme_minimal(base_size = 12) +
  theme(strip.placement = "outside",
        strip.text.y.right = element_blank(),
        axis.text.x = element_markdown(angle = 0, hjust = 0.5, face = "bold", colour = "black"), 
        axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
        panel.grid  = element_blank(), 
        panel.spacing = unit(1, "lines"), 
        plot.title = element_text(face = "bold"))

Dir_plot_Delta <- Correlations_Delta %>%
  distinct(Origin, Marker, Direction) %>% 
  ggplot(., aes(x = 1, y = Marker, fill = Direction)) +
  geom_tile(color = "white", width = 1, height = 1) +
  facet_grid(Origin ~ ., scales = "free_y", space  = "free_y", switch = "x") +
  scale_fill_manual(values = c("Increase" = "mediumspringgreen",
                               "Decrease" = "purple", 
                               "No change"  = "grey80"), 
                    guide = guide_legend(order = 2, title.position = "top", 
                                         title = "T12 vs T0", title.theme = element_markdown(face = "bold", size = 12), 
                                         title.hjust = 0, label.position = "right", 
                                         keywidth = unit(0.5, "cm"), keyheight = unit(0.4, "cm"))) +
  scale_y_discrete(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  theme_void() +
  theme(strip.text.y.right = element_text(angle = 0, hjust = 0, vjust = 0.5, face  = "bold", margin = margin(l = 10)),
        plot.margin = margin(0, 0, 0, 0), 
        panel.spacing.x = unit(0, "lines"),
        panel.spacing = unit(1, "lines"))

Combined_Delta <- Main_plot_Delta + Dir_plot_Delta +
  plot_layout(widths = c(0.95, 0.05), 
              # widths = c(length(unique(Correlations$Variable)), 1), 
              guides = "collect") +   
  plot_annotation(theme = theme(plot.margin = margin(0, 0, 0, 0))) &
  theme(legend.box = "vertical", 
        legend.position = "right",
        legend.title.position = "bottom")

# ggsave(Combined_Delta, filename = "~/SLE/Glycans/Plots/Glycans_Correlations_Delta.jpeg", width = 10, height = 24, dpi = 300)

```




```{r}

DFs_for_GLMs <- DFs_Combined %>% 
  rownames_to_column(var = "Patients") %>% 
  extract(Patients, into = c("ID", "Timepoint"), 
          regex = "Patient\\s+(\\d+)\\s+(T\\d+)", remove = TRUE) %>% 
  mutate(ID = as.integer(ID), 
         Timepoint = factor(Timepoint, levels = c("T0", "T12"))) %>% 
  drop_na()

sapply(DFs_for_GLMs, function(x) sum(is.na(x)))

SLEDAI2K_model <- glm(SLEDAI2K ~ ., data = DFs_for_GLMs %>% select(-c(ID, Timepoint)), family = binomial)
summary(SLEDAI2K_model)

broom::tidy(SLEDAI2K_model) %>%
  mutate(OR = exp(estimate),
         lower = exp(estimate - 1.96 * std.error),
         upper = exp(estimate + 1.96 * std.error))
  
```

```{r}

table(DFs_for_GLMs$SLEDAI2K)

library(caret)
nzv <- nearZeroVar(DFs_for_GLMs %>% select(-ID, -Timepoint, -SLEDAI2K),
                   saveMetrics=TRUE)
nzv[nzv$zeroVar | nzv$nzv, ]

```

```{r}

Comparators_clean <- colnames(Comparator_Values)

Top_Markers <- Correlations %>% 
  filter(Variable == "SLEDAI2K") %>% 
  arrange(desc(abs(Correlation))) %>% 
  slice_head(n = 3) %>% 
  pull(Marker)
  
Top_Markers_Origin <- Correlations %>% 
  filter(Variable == "SLEDAI2K") %>% 
  group_by(Origin) %>% 
  arrange(desc(abs(Correlation))) %>% 
  slice_head(n = 5) %>% 
  summarise(Markers = list(Marker)) %>% 
  ungroup() %>% 
  deframe()

SLEDAI2K_model_sub <- glm(paste("SLEDAI2K ~ ", paste(Top_Markers, collapse = " + ")), 
                          data = DFs_for_GLMs %>% select(-c(ID, Timepoint)), family = binomial)

summary(SLEDAI2K_model_sub)

broom::tidy(SLEDAI2K_model_sub) %>%
  mutate(OR = exp(estimate),
         lower = exp(estimate - 1.96 * std.error),
         upper = exp(estimate + 1.96 * std.error))







```

```{r}

## Get the names of the Markers for the comparisons ##
Candidates <- setdiff(names(DFs_for_GLMs), c("ID", "Timepoint", "SLEDAI2K"))

## GLMs for each of the Markers compared to SLEDAI2K ##
univ_results <- map_df(Candidates, function(var){
  
  ## Build the SLEDAI2K ~ variable formulas ##
  fmla <- reformulate(var, response = "SLEDAI2K")
  
  ## Fit the model ##
  m <- glm(fmla, data = DFs_for_GLMs, family = binomial)
  
  ## Extract the predictor row, add OR and CIs
  broom::tidy(m)[2, ] %>%
    transmute(Marker = var, estimate, std.error, statistic, p.value, 
              OR = exp(estimate), 
              lower = exp(estimate - 1.96 * std.error),
              upper = exp(estimate + 1.96 * std.error))
})

## Adjust p values (Might not be necessary) ##
# univ_results <- univ_results %>%
#   mutate(p.adj = p.adjust(p.value, method = "BH"))

## Get the significant glms ##
Univ_sign_p <- univ_results %>% filter(p.value < 0.05)
Univ_sign_OR <- univ_results %>% arrange(desc(abs(log(OR))))


```



