---
title: "Glycans_new"
output: html_document
---

```{r Libraries, }

## Load the libraries ##
library(tidyverse)
library(readxl)
library(purrr)
library(broom)
library(ggtext)
library(patchwork)
library(caret)
library(jtools)
library(ggplot2)
library(rlang)
library(logistf) ## Firth’s logistf() ##
library(glmnet) ## Penalised regression ##
library(broom.helpers)
library(scales)
library(patchwork)
library(grid)
library(scales)
library(writexl)
library(RColorBrewer)
library(ggrepel)

Pallete <- c("coral1", "deeppink3", "midnightblue", "cyan3", "mediumspringgreen", "yellow3")

```

```{r Load the data}

AGP_Data <- read_xlsx("~/SLE/Glycans/Data/LN_AGP_glycopeptide-data.xlsx")
C3_Data <- read_xlsx("~/SLE/Glycans/Data/LN_C3_glycopeptide_data.xlsx")
Serum_Data <- read_xlsx("~/SLE/Glycans/Data/LN_serum_glycome_data.xlsx")
Decreased_data <- read_xlsx("~/SLE/Glycans/Data/decreased.xlsx")
Increased_data <- read_xlsx("~/SLE/Glycans/Data/increased.xlsx")
IgG_FAB_Data <- read_xlsx("~/SLE/Glycans/Data/LN_total_IgG_Fab_data.xlsx")
IgG_FC_Data <- read_xlsx("~/SLE/Glycans/Data/LN_total_IgG_Fc_data.xlsx")
IgG_Meta <- read_xlsx("~/SLE/Glycans/Data/LN_total_IgG_glycomedata.xlsx")
Glycan_Outcomes <- read_xlsx("~/SLE/Glycans/Data/Glycans_Outcomes.xlsx")

```

```{r Prep slightly}

Comparators <- c("AI", "CI", "S-creatinine", "eGFR", "UPCR", "albumin", "total", "extra-renal", "Renal Impairment", "Clinical")

Select_Comparators <- c("AI", "CI", "eGFR", "UPCR", "total")

Comparator_Levels <- c("AI", "CI", "eGFR", "UPCR", "SLEDAI-2K")

# Renal_Impairment = `Renal Impairment`,
#          Extra_Renal = `extra-renal`,
#          S_creatinine = `S-creatinine`, 
#          Clinical_Response = Clinical, 

Comparator_Values <- Increased_data %>%
  rename(ID = `Patient number`, Time_point = `Time point`) %>%
  select(ID, Time_point, any_of(Select_Comparators)) %>%
  rename('SLEDAI-2K' = total) %>%
  # mutate(Identification = paste0(ID, " ", Time_point)) %>%
  # select(-c(ID, Time_point)) %>%
  select(ID, Time_point, everything()) %>%
  # column_to_rownames("Identification") %>%
  mutate(across(.cols = -c(ID, Time_point), .fns = as.numeric))

Comparator_Values_Long <- Increased_data %>%
  rename(ID = `Patient number`, Time_point = `Time point`) %>%
  select(ID, Time_point, any_of(Select_Comparators)) %>%
  rename('SLEDAI-2K' = total) %>%
  mutate(across(.cols = -c(ID, Time_point), .fns = as.numeric)) %>% 
  pivot_longer(cols = -c(ID, Time_point), names_to = "Comparator", values_to = "Value") %>% 
  mutate(Comparator = factor(Comparator, levels = Comparator_Levels))

```

```{r Make dtaaframes long}

Dataframes <- list(AGP = AGP_Data, 
                   C3 = C3_Data, 
                   Serum = Serum_Data,
                   Fab = IgG_FAB_Data, 
                   Fc = IgG_FC_Data, 
                   IgG = IgG_Meta)

Process_DFs <- function(df){
  df %>% 
    select(-c(Sample, `ID_St Luc`)) %>% 
    rename(ID = `Patient number`, Time_point = `Time point`) %>% 
    mutate(across(.cols = -c(ID, Time_point), .fns = as.numeric)) %>% 
    pivot_longer(cols = -c(ID, Time_point), names_to = "Marker", values_to  = "Value")
}

Long_Dataframes <- map(Dataframes, Process_DFs)
```

```{r Calculate the log2FC ratios}

FCR_list <- imap(Long_Dataframes, ~ {
  df <- .x
  prefix <- .y
  
  df %>% 
    pivot_wider(names_from = Time_point, values_from = Value) %>% 
    group_by(Marker) %>% 
    summarise(mean_T0 = mean(T0, na.rm = TRUE), 
              mean_T12 = mean(T12, na.rm = TRUE)) %>%  
    mutate(log2FC = log2(mean_T12/mean_T0), 
           Marker = paste0(prefix, "_", Marker),
           Origin = prefix) %>% 
    select(Origin, Marker, everything())
})

FCR_Values <- bind_rows(FCR_list)

```

```{r Get the direction of each marker}

Directions_List <- imap(Long_Dataframes, ~ {
  df <- .x
  prefix <- .y
  
  df %>% 
    mutate(Marker_Timepoint = paste0(Marker, Time_point)) %>%
    group_by(Marker_Timepoint) %>%
    summarise(Mean = mean(Value, na.rm = TRUE), .groups = "drop") %>%
    extract(col = Marker_Timepoint, 
          into = c("Marker", "Timepoint"), 
          regex = "(.+)(T0|T12)$") %>% 
    pivot_wider(names_from = "Timepoint", values_from = "Mean") %>% 
    mutate(Direction = case_when(T12 > T0 ~ "Increase", 
                                 T12 < T0 ~ "Decrease", 
                                 TRUE ~ NA), 
           Marker = paste0(prefix, "_", Marker),
           Origin = prefix) %>% 
    select(Marker, Direction, Origin)
})

Directions <- bind_rows(Directions_List)

```

```{r Perform the tests}

Paired_Tests <- function(df){ df %>% 
  pivot_wider(names_from = "Time_point", values_from = "Value", names_prefix = "Value_") %>% 
  group_by(Marker) %>% 
  summarise(Pairs = n_distinct(ID),
            Test = list(wilcox.test(Value_T12, 
                                    Value_T0, 
                                    paired = TRUE, 
                                    exact = FALSE)), 
                        .groups = "drop") %>% 
  mutate(Results = map(Test, broom::tidy)) %>% 
  unnest(Results) %>% 
  select(Marker, Pairs, statistic, p.value, method) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr"))
}

Test_Results <- imap(Long_Dataframes, ~Paired_Tests(.x) %>% 
                       mutate(Marker = paste0(.y, "_", Marker)))

Test_Results <- bind_rows(Test_Results, .id = "Origin")

```

```{r Prep for the volcanos}

FCR_Values <- FCR_Values %>% 
  inner_join(Test_Results %>% select(Marker, p.value, FDR), by = "Marker") %>% 
  mutate(p_value_log10 = -log10(p.value), 
         FDR_log10 = -log10(FDR), 
         Significance = if_else(p.value < 0.05, "Significant", "Not Significant"), 
         Significance_FDR = if_else(FDR < 0.05, "Significant", "Not Significant"), 
         Marker = str_remove(Marker, "^[^_]+_")) 

Top_Glycans_nadj <- FCR_Values %>%
  arrange(p.value) %>% 
  head(25)

Top_Glycans_FDR <- FCR_Values %>%
  arrange(FDR) %>% 
  head(25)

y_breaks_nadj <- pretty(range(FCR_Values$p_value_log10), n = 3)
y_breaks_FDR <- pretty(range(FCR_Values$FDR_log10), n = 3)


```

```{r Volcano visualisation}

Volcano_nadj <- ggplot(FCR_Values, aes(x = log2FC, y = p_value_log10)) +
    geom_point(aes(color = Origin, alpha = Significance), size = 2) +
    scale_alpha_manual(values = c("Significant" = 1.0, 
                                  "Not Significant" = 0.3), 
                                  guide = "none") +
  scale_colour_manual(values = Pallete) +
  scale_x_continuous(limits = c(-1, 1), 
                     breaks = seq(-1, 1, by = 0.5), 
                     expand = c(0, 0)) +
  scale_y_continuous(limits = c(min(y_breaks_nadj), max(y_breaks_nadj)), 
                     breaks = y_breaks_nadj, 
                     expand = c(0, 0)) +  
  labs(title = "Glycan expression change over a 12 month period", 
         x = "Fold Change (log<sub>2</sub>FC)", 
         y = "P value (-log<sub>10</sub>)", 
         caption = paste0("P value: <b>Not adjusted</b>
         <br>Number of significant markers: <b>", 
         FCR_Values %>% 
           filter(p.value < 0.05) %>% 
           nrow(), "</b></br>")) + 
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +  
  geom_vline(xintercept = 0, linetype = "dashed", color = "black") +  
  theme_minimal(base_size = 14) +
  theme(plot.title = element_markdown(hjust = 0.5, face = "bold", size = 14),
        legend.title = element_blank(), 
        axis.title.x = element_markdown(face = "bold"), 
        axis.title.y = element_markdown(face = "bold"), 
        plot.caption.position = "plot", 
        plot.caption = element_markdown(hjust = 0.9, vjust = 1),
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_blank()) +
  geom_text_repel(data = Top_Glycans_nadj, aes(label = Marker), 
                  size = 3, 
                  force = 2,
                  box.padding = 0.3, 
                  point.padding = 0.1, 
                  segment.color = NA, 
                  max.overlaps = Inf, 
                  min.segment.length = 0)


Volcano_FDR <- ggplot(FCR_Values, aes(x = log2FC, y = FDR_log10)) +
    geom_point(aes(color = Origin, alpha = Significance_FDR), size = 2) +
    scale_alpha_manual(values = c("Significant" = 1.0, 
                                  "Not Significant" = 0.3), 
                                  guide = "none") +
  scale_colour_manual(values = Pallete) +
  scale_x_continuous(limits = c(-1, 1), 
                     breaks = seq(-1, 1, by = 0.5), 
                     expand = c(0, 0)) +
  scale_y_continuous(limits = c(min(y_breaks_FDR), max(y_breaks_FDR)), 
                     breaks = y_breaks_FDR, 
                     expand = c(0, 0)) +  
    labs(title = "Glycan expression change over a 12 month period", 
         x = "Fold Change (log<sub>2</sub>FC)", 
         y = "P value (-log<sub>10</sub>)", 
         caption = paste0("P value: <b>FDR adjusted</b>
         <br>Number of significant markers: <b>", 
         FCR_Values %>% 
           filter(FDR < 0.05) %>% 
           nrow(), "</b></br>")) + 
    geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +  
    geom_vline(xintercept = 0, linetype = "dashed", color = "black") +  
    theme_minimal(base_size = 14) +
    theme(plot.title = element_markdown(hjust = 0.5, face = "bold", size = 14),
          legend.title = element_blank(), 
          axis.title.x = element_markdown(face = "bold"), 
          axis.title.y = element_markdown(face = "bold"), 
          plot.caption.position = "plot", 
          plot.caption = element_markdown(hjust = 0.9, vjust = 1),
          panel.grid.major = element_line(color = "grey90"),
          panel.grid.minor = element_blank()) +
  geom_text_repel(data = Top_Glycans_FDR, aes(label = Marker), 
                  size = 3, 
                  force = 2,
                  box.padding = 0.3, 
                  point.padding = 0.1, 
                  segment.color = NA, 
                  max.overlaps = Inf, 
                  min.segment.length = 0)

# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_1_Volcano/Volcano_nadj.jpeg"),
#        plot = Volcano_nadj, width = 10, height = 8, dpi = 300, device = "jpeg")
# 
# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_1_Volcano/Volcano_FDR.jpeg"),
#        plot = Volcano_FDR, width = 10, height = 8, dpi = 300, device = "jpeg")


```

```{r Combine the direction with the tests}

Results_Total <- Test_Results %>% inner_join(Directions, by = c("Origin", "Marker"))

Dataframes_Final <- imap(
  Long_Dataframes, ~ .x %>% 
      mutate(Marker = paste0(.y, "_", Marker), 
             Origin = .y)) %>% 
  bind_rows(., .id = "Origin") %>% 
  select(ID, Origin, everything())

Results_Sign <- Results_Total %>% 
  filter(p.value < 0.05)

Dataframes_Final_Sign <- Dataframes_Final %>% 
  filter(Marker %in% Results_Sign$Marker)

```

```{r Correlation analysis - Total}

Dataframes_Final_Wide <- Dataframes_Final %>%
  select(-c(Origin)) %>%
  pivot_wider(id_cols = c(ID, Time_point), names_from = "Marker", values_from = "Value") 

DFs_Combined <- Dataframes_Final_Wide %>% 
  inner_join(Comparator_Values, by = c("ID", "Time_point")) %>% 
  mutate(ID = paste0(ID, " ", Time_point)) %>% 
  column_to_rownames(var = "ID") %>% 
  select(-Time_point)

Comparator_Values_clean <- Comparator_Values %>% 
  mutate(ID = paste0(ID, " ", Time_point)) %>% 
  column_to_rownames(var = "ID") %>% 
  select(-Time_point)

Dataframes_Final_Wide_clean <- Dataframes_Final_Wide %>% 
  mutate(ID = paste0(ID, " ", Time_point)) %>% 
  column_to_rownames(var = "ID") %>% 
  select(-Time_point)

Correlations <- expand_grid(Marker = colnames(Dataframes_Final_Wide_clean), 
                            Variable = colnames(Comparator_Values_clean)) %>% 
  mutate(test = map2(Marker, Variable, ~ cor.test(DFs_Combined[[.x]], 
                                                  DFs_Combined[[.y]], 
                                                  method = "spearman", 
                                                  exact  = FALSE)),
         rho = map_dbl(test, "estimate"), 
         p.value = map_dbl(test, "p.value", )) %>%
  mutate(P_adjust = p.adjust(p.value, method = "fdr")) %>% 
  select(-test) %>% 
  mutate(Origin = sub("_.*$", "", Marker)) %>% 
  inner_join(Directions, by = c("Marker", "Origin")) %>% 
  rename(Correlation = "rho") %>% 
  mutate(Significance = case_when(p.value < 0.05 ~ "*"))

Marker_DF <- Dataframes_Final %>% 
  rename(Marker_Value = "Value") 

Comp_DF <- Comparator_Values_Long %>% 
  rename(Comp_Value = "Value")

Comparisons <- tribble(~Time_1, ~Time_2, ~Label, 
                       "T0", "T0", "Baseline vs Baseline", 
                       "T12", "T12", "Month 12 vs Month 12",
                       "T0", "T12", "Baseline vs Month 12")

```

```{r}

Run_Cors <- function(Time_1, Time_2, Label) {
  # filter & join
  joined <- Marker_DF %>%
    filter(Time_point == Time_1) %>%
    select(ID, Marker, Marker_Value) %>%
    inner_join(Comp_DF %>% 
                 filter(Time_point == Time_2) %>% 
                 select(ID, Comparator, Comp_Value),
               by = "ID", relationship = "many-to-many")
  
  joined %>%
    group_by(Marker, Comparator) %>%
    summarize(broom::tidy(cor.test(Marker_Value, Comp_Value, 
                                   method = "spearman", 
                                   exact = FALSE)),
              .groups = "drop") %>%
    mutate(Comparison = Label)
}

Correlation_Results_Total <- Comparisons %>%
  pmap_dfr(~ Run_Cors(..1, ..2, ..3)) 

Correlation_Results_Clean <-  Correlation_Results_Total %>% 
  group_by(Comparison) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr"), 
         Significance = case_when(p.value < 0.05 ~ "*"), 
         Origin = sub("_.*$", "", Marker), 
         Comparator = factor(Comparator, levels = Comparator_Levels), 
         Comparison = factor(Comparison, levels = c("Baseline vs Baseline", "Month 12 vs Month 12", "Baseline vs Month 12"))) %>% 
  rename(Correlation = "estimate") %>% 
  inner_join(Directions, by = c("Marker", "Origin"))
  

```

```{r Correlations visualisation}

Main_plot <- ggplot(Correlation_Results_Clean, aes(x = Comparator, y = Marker, fill = Correlation)) +
  geom_tile(color = "white", width = 1, height = 1) +
  scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                       midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                       guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                              title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
  facet_grid(Origin ~ Comparison, scales = "free_y", space = "free_y") +
  # geom_text(aes(label = round(Correlation, 2)), size = 3) +
  geom_text(aes(label = Significance, vjust = 0, hjust = 0.5, fontface = "bold")) +
  scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), expand = c(0,0)) +
  scale_x_discrete(labels = function(x) {
    x <- gsub("_", " ", x)
    x <- gsub("Extra Renal", "Extra<br>Renal", x)
    x <- gsub("Renal Impairment", "Renal<br>Impairment", x)
    x }, expand = c(0,0)) +
  labs(title = "Heatmap of Glycan Correlations", x = NULL, y = NULL, 
       caption = paste0("Correlation coefficient used: <b>Spearman</b> 
         <br>P value: <b>Not adjusted</b>")) +
  theme_minimal(base_size = 12) +
  theme(strip.placement = "outside",
        strip.text.y.right = element_text(angle = 0, hjust = 0.5, vjust = 0.5, face  = "bold"),
        axis.text.x = element_markdown(angle = 0, hjust = 0.5, face = "bold", colour = "black"), 
        axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
        panel.grid  = element_blank(), 
        panel.spacing = unit(1, "lines"), 
        plot.caption.position = "plot", 
        plot.caption = element_markdown(hjust = 0.9, vjust = 1),
        plot.title = element_text(face = "bold"))

# Dir_plot <- Correlation_Results_Clean %>%
#   distinct(Origin, Marker, Direction) %>% 
#   ggplot(., aes(x = 1, y = Marker, fill = Direction)) +
#   geom_tile(color = "white", width = 1, height = 1) +
#   facet_grid(Origin ~ ., scales = "free_y", space  = "free_y", switch = "x") +
#   scale_fill_manual(values = c("Increase" = "mediumspringgreen",
#                                "Decrease" = "purple", 
#                                "No change"  = "grey80"), 
#                     guide = guide_legend(order = 2, title.position = "top", 
#                                          title = "Month 12 <br>vs Baseline", title.theme = element_markdown(face = "bold", size = 12), 
#                                          title.hjust = 0, label.position = "right", 
#                                          keywidth = unit(0.5, "cm"), keyheight = unit(0.4, "cm"))) +
#   scale_y_discrete(expand = c(0,0)) +
#   scale_x_continuous(expand = c(0,0)) +
#   theme_void() +
#   theme(strip.text.y.right = element_text(angle = 0, hjust = 0, vjust = 0.5, face  = "bold", margin = margin(l = 10)),
#         plot.margin = margin(0, 0, 0, 0), 
#         panel.spacing.x = unit(0, "lines"),
#         panel.spacing = unit(1, "lines"), 
#         legend.title = element_markdown(face = "bold"))
# 
# Combined_Plot <- Main_plot + Dir_plot +
#   plot_layout(widths = c(0.95, 0.05), 
#               # widths = c(length(unique(Correlations$Variable)), 1), 
#               guides = "collect") +   
#   plot_annotation(theme = theme(plot.margin = margin(0, 0, 0, 0))) &
#   theme(legend.box = "vertical", 
#         legend.position = "right",
#         legend.title.position = "bottom")

# ggsave(Main_plot,
#        filename = "~/SLE/Glycans/Plots_2/Figure_2_Correlations_Total/Correlations_total.jpeg",
#        width = 15, height = 25, dpi = 300)

```

```{r Correlation plots by Origin}

Correlation_Results_Clean_Sign <- Correlation_Results_Clean %>%
  group_by(Marker) %>% 
  filter(any(Significance == "*")) %>% 
  ungroup()

Sub_Correlation_plots <- function(orig) {

  Cor_df_current <- Correlation_Results_Clean_Sign %>% 
    filter(Origin == orig)
  
  n_markers <- Cor_df_current %>% 
    distinct(Marker) %>% 
    nrow()
  
  n_comp <- Cor_df_current %>% 
    distinct(Comparator) %>% 
    nrow()
  
  Main_plot_current <- ggplot(Cor_df_current, aes(x = Comparator, y = Marker, fill = Correlation)) +
    geom_tile(color = "white", width = 1, height = 1) +
    scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                         midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                         guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                                title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
    facet_wrap(~Comparison, nrow = 1) +
    # geom_text(aes(label = round(Correlation, 2)), size = 3) +
    geom_text(aes(label = Significance, vjust = 0.5, hjust = 0.5, fontface = "bold")) +
    scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), expand = c(0,0)) +
    scale_x_discrete(labels = function(x) {
      x <- gsub("_", " ", x)
      x <- gsub("Extra Renal", "Extra<br>Renal", x)
      x <- gsub("Renal Impairment", "Renal<br>Impairment", x)
      x }, expand = c(0,0)) +
    labs(title = paste0("Heatmap of Glycan Correlations<br>Origin: ", orig), x = NULL, y = NULL,
         caption = paste0("Correlation coefficient used: <b>Spearman</b> 
         <br>P value: <b>Not adjusted</b>")) +
    theme_minimal(base_size = 12) +
    theme(strip.placement = "outside",
          strip.text.y.left = element_blank(),
          axis.text.x = element_markdown(angle = 0, hjust = 0.5, face = "bold", colour = "black"), 
          axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
          panel.grid  = element_blank(), 
          panel.spacing = unit(1, "lines"), 
          plot.title = element_markdown(face = "bold", lineheight = 1.2),
          aspect.ratio = n_markers/n_comp * 0.3,  
          plot.caption.position = "plot", 
          plot.caption = element_markdown(hjust = 0.9, vjust = 1),
          plot.margin = margin(5, 5, 5, 5, "pt"))
  
  # Dir_plot_current <- Cor_dfMarkerDir_plot_current <- Cor_df_current %>%
  #   distinct(Origin, Marker, Direction) %>% 
  #   ggplot(., aes(x = 1, y = Marker, fill = Direction)) +
  #   geom_tile(color = "white", width = 1, height = 1) +
  #   scale_fill_manual(values = c("Increase" = "mediumspringgreen",
  #                                "Decrease" = "purple", 
  #                                "No change"  = "grey80"), 
  #                     guide = guide_legend(order = 2, title.position = "top", 
  #                                          title = "Month 12 <br>vs Baseline", title.theme = element_markdown(face = "bold", size = 12), 
  #                                          title.hjust = 0, label.position = "right", 
  #                                          keywidth = unit(0.5, "cm"), keyheight = unit(0.4, "cm"))) +
  #   scale_y_discrete(expand = c(0,0)) +
  #   scale_x_continuous(expand = c(0,0)) +
  #   theme_void() +
  #   theme(strip.text.y.right = element_text(angle = 0, hjust = 0, vjust = 0.5, face  = "bold", margin = margin(l = 10)),
  #         plot.margin = margin(0, 0, 0, 0), 
  #         panel.spacing.x = unit(0, "lines"),
  #         panel.spacing = unit(1, "lines"), 
  #         legend.title = element_markdown(face = "bold"))
  # 
  # Combined_Plot_current <- Main_plot_current + Dir_plot_current +
  #   plot_layout(widths = c(0.95, 0.05), 
  #               # widths = c(length(unique(Correlations$Variable)), 1), 
  #               guides = "collect") +   
  #   plot_annotation(theme = theme(plot.margin = margin(0, 0, 0, 0))) &
  #   theme(legend.box = "vertical", 
  #         legend.position = "right",
  #         legend.title.position = "bottom")

  plot_height <- max(n_markers * 0.3, 4)
  
  # ggsave(Main_plot_current,
  #      filename = paste0("~/SLE/Glycans/Plots_2/Figure_2_Correlations_Total/Correlations_", orig,".jpeg"),
  #      width = 15, 
  #      height = plot_height,
  #      dpi = 300)
}

plots_by_origin <- map(unique(Correlation_Results_Clean$Origin), Sub_Correlation_plots)

```

```{r Correlations visualisation - Significant only}

Main_plot <- ggplot(Correlation_Results_Clean_Sign, aes(x = Comparator, y = Marker, fill = Correlation)) +
  geom_tile(color = "white", width = 1, height = 1) +
  scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                       midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                       guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                              title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
  facet_grid(Origin ~ Comparison, scales = "free_y", space = "free_y") +
  # geom_text(aes(label = round(Correlation, 2)), size = 3) +
  geom_text(aes(label = Significance, vjust = 0.5, hjust = 0.5, fontface = "bold")) +
  scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), expand = c(0,0)) +
  scale_x_discrete(labels = function(x) {
    x <- gsub("_", " ", x)
    x <- gsub("Extra Renal", "Extra<br>Renal", x)
    x <- gsub("Renal Impairment", "Renal<br>Impairment", x)
    x }, expand = c(0,0)) +
  labs(title = "Heatmap of Glycan Correlations", x = NULL, y = NULL,
       caption = paste0("Correlation coefficient used: <b>Spearman</b> 
       <br>P value: <b>Not adjusted</b>")) +
  theme_minimal(base_size = 12) +
  theme(strip.placement = "outside",
        strip.text.y.right = element_text(angle = 0, hjust = 0, vjust = 0.5, face  = "bold", margin = margin(l = 10)),
        axis.text.x = element_markdown(angle = 0, hjust = 0.5, face = "bold", colour = "black"), 
        axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
        panel.grid  = element_blank(), 
        panel.spacing = unit(1, "lines"), 
        plot.caption.position = "plot", 
        plot.caption = element_markdown(hjust = 0.9, vjust = 1),
        plot.title = element_text(face = "bold"))

# Dir_plot <- Correlation_Results_Clean_Sign %>%
#   distinct(Origin, Marker, Direction) %>% 
#   ggplot(., aes(x = 1, y = Marker, fill = Direction)) +
#   geom_tile(color = "white", width = 1, height = 1) +
#   facet_grid(Origin ~ ., scales = "free_y", space  = "free_y", switch = "x") +
#   scale_fill_manual(values = c("Increase" = "mediumspringgreen",
#                                "Decrease" = "purple", 
#                                "No change"  = "grey80"), 
#                     guide = guide_legend(order = 2, title.position = "top", 
#                                          title = "Month 12 <br>vs Baseline", title.theme = element_markdown(face = "bold", size = 12), 
#                                          title.hjust = 0, label.position = "right", 
#                                          keywidth = unit(0.5, "cm"), keyheight = unit(0.4, "cm"))) +
#   scale_y_discrete(expand = c(0,0)) +
#   scale_x_continuous(expand = c(0,0)) +
#   theme_void() +
#   theme(strip.text.y.right = element_text(angle = 0, hjust = 0, vjust = 0.5, face  = "bold", margin = margin(l = 10)),
#         plot.margin = margin(0, 0, 0, 0), 
#         panel.spacing.x = unit(0, "lines"),
#         panel.spacing = unit(1, "lines"), 
#         legend.title = element_markdown(face = "bold"))
# 
# Combined_Plot <- Main_plot + Dir_plot +
#   plot_layout(widths = c(0.95, 0.05), 
#               # widths = c(length(unique(Correlations$Variable)), 1), 
#               guides = "collect") +   
#   plot_annotation(theme = theme(plot.margin = margin(0, 0, 0, 0))) &
#   theme(legend.box = "vertical", 
#         legend.position = "right",
#         legend.title.position = "bottom")

# ggsave(Main_plot,
#        filename = "~/SLE/Glycans/Plots_2/Figure_2_Correlations_Total/Correlations_significant.jpeg",
#        width = 15, height = 25, dpi = 300)

```

```{r Figure 3 preparation}

AI_CI_data <- read_xlsx("~/SLE/Glycans/Data/AI_CI_data.xlsx") %>% 
  rename(ID = "Patients")

AI_CI_Scores <- AI_CI_data %>% 
  select(ID, Time_point, `NIH AI SCORE`, `NIH IC SCORE`)

AI_CI_data_clean <- AI_CI_data %>% 
  select(-c(`NIH AI SCORE`, `NIH IC SCORE`)) %>% 
  pivot_longer(cols = -c(ID, Time_point), names_to = "Result", values_to = "Result_Value") %>% 
  separate(col = Result, into = c("Category", "Result"), sep = " - ", extra = "merge") %>% 
  mutate(Category = gsub(" ", "_", Category), 
         Result = gsub("[ ,\\-]+", "_", Result),
         Result_Value = na_if(Result_Value, "NA"),
         Result_Value = if_else(is.na(Result_Value), 
                         NA_real_, 
                         if_else(Result_Value > 0, 1, 0))) 

AI_CI_data_joint <- AI_CI_data_clean %>%
  inner_join(Dataframes_Final, by = c("ID", "Time_point"), relationship = "many-to-many") 
  
NIH_Test_Results <- AI_CI_data_joint %>% 
  filter(!is.na(Result_Value)) %>%   
  group_by(Marker, Category, Result, Time_point) %>%
  filter(n_distinct(Result_Value) == 2) %>%
  summarize(NIH_Test = list(wilcox.test(Value ~ factor(Result_Value), 
                                 data = cur_data(), 
                                 exact = FALSE)), 
            
            NIH_Cor_Test = list(cor.test(Value, Result_Value, 
                                   method = "spearman", 
                                   exact = FALSE)),
            
            .groups = "drop") %>% 
  mutate(Wilcox = map(NIH_Test, tidy), 
         Spearman = map(NIH_Cor_Test, tidy)) %>% 
  unnest(c(Wilcox, Spearman), names_sep = "_") %>%
  group_by(Time_point) %>%
  mutate(Wilcox_FDR = p.adjust(Wilcox_p.value, method = "fdr"), 
         Spearman_FDR = p.adjust(Spearman_p.value, method = "fdr")) %>%
  ungroup()

```

```{r Figure 3 Visualisation - MISSING}


```

```{r Delta - Delta correlation}

Glycan_Deltas <- Dataframes_Final_Sign %>% 
  group_by(ID, Marker) %>% 
  mutate(M_Delta = order_by(Time_point, Value - lag(Value)), 
         M_Delta = ifelse(is.na(M_Delta), 0, M_Delta)) %>%
  filter(Time_point == "T12") %>% 
  select(-c(Time_point, Value, Origin)) %>% 
  pivot_wider(id_cols = ID, 
              names_from = Marker, 
              values_from = M_Delta) %>% 
  column_to_rownames(var = "ID")

Comparator_Values_Delta <- Comparator_Values_Long %>% 
  rename(Comp_Value = "Value") %>% 
  # pivot_longer(cols = -c(ID, Time_point), names_to = "Comparator", values_to = "Comp_Value") %>% 
  group_by(ID, Comparator) %>% 
  mutate(Comp_Delta = order_by(Time_point, Comp_Value - lag(Comp_Value)), 
         Comp_Delta = ifelse(is.na(Comp_Delta), 0, Comp_Delta)) %>% 
  filter(Time_point == "T12") %>% 
  select(-c(Time_point, Comp_Value)) %>% 
  pivot_wider(id_cols = ID, 
              names_from = Comparator, 
              values_from = Comp_Delta) %>% 
  column_to_rownames(var = "ID")


DFs_Delta_Combined <- cbind(Glycan_Deltas, Comparator_Values_Delta) 

Correlations_Delta <- expand_grid(Marker = colnames(Glycan_Deltas), 
              Comparator = colnames(Comparator_Values_Delta)) %>% 
  mutate(test = map2(Marker, 
                     Comparator, ~ cor.test(DFs_Delta_Combined[[.x]], 
                                          DFs_Delta_Combined[[.y]], 
                                          method = "spearman", 
                                          exact  = FALSE)),
         rho = map_dbl(test, "estimate"), 
         p.value = map_dbl(test, "p.value", )) %>%
  mutate(P_adjust = p.adjust(p.value, method = "BH")) %>% 
  select(-test) %>% 
  mutate(Origin = sub("_.*$", "", Marker)) %>% 
  inner_join(Directions, by = c("Marker", "Origin")) %>% 
  rename(Correlation = "rho") %>% 
  mutate(Significance = case_when(p.value < 0.05 ~ "*"), 
         Comparator = factor(Comparator, levels = Comparator_Levels))

```

```{r Delta visualisations}

Correlations_Delta_Sign <- Correlations_Delta %>%
  group_by(Marker) %>% 
  filter(any(Significance == "*")) %>% 
  ungroup()

Main_plot <- ggplot(Correlations_Delta_Sign, aes(x = Comparator, y = Marker, fill = Correlation)) +
  geom_tile(color = "white", width = 1, height = 1) +
  scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                       midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                       guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                              title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
  facet_grid(Origin ~ ., scales = "free_y", space = "free_y") +
  # geom_text(aes(label = round(Correlation, 2)), size = 3) +
  geom_text(aes(label = Significance, vjust = 0.5, hjust = 0.5, fontface = "bold")) +
  scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), expand = c(0,0)) +
  scale_x_discrete(labels = function(x) {
    x <- gsub("_", " ", x)
    x <- gsub("Extra Renal", "Extra<br>Renal", x)
    x <- gsub("Renal Impairment", "Renal<br>Impairment", x)
    x }, expand = c(0,0)) +
  labs(title = "Correlations between glycan and marker deltas", x = NULL, y = NULL,
       caption = paste0("Correlation coefficient used: <b>Spearman</b> 
       <br>P value: <b>Not adjusted</b>")) +
  theme_minimal(base_size = 12) +
  theme(strip.placement = "outside",
        strip.text.y.right = element_text(angle = 0, hjust = 0, vjust = 0.5, face  = "bold", margin = margin(l = 10)),
        axis.text.x = element_markdown(angle = 0, hjust = 0.5, face = "bold", colour = "black"), 
        axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
        panel.grid  = element_blank(), 
        panel.spacing = unit(1, "lines"), 
        plot.caption.position = "plot", 
        plot.caption = element_markdown(hjust = 0.9, vjust = 1),
        plot.title = element_markdown(face = "bold"))

n_markers <- Correlations_Delta_Sign %>% 
    distinct(Marker) %>% 
    nrow()

plot_height <- max(n_markers * 0.3, 4)

# ggsave(Main_plot,
#        filename = "~/SLE/Glycans/Plots_2/Figure_4_Delta_Correlations/Delta_vs_Delta_sign_only.jpeg",
#        width = 15, height = plot_height, dpi = 300)



```

```{r Delta - Month 12 Correlation}

Delta_vs_M12 <- Comparator_Values %>% 
  filter(Time_point == "T12") %>% 
  select(-Time_point) %>% 
  inner_join(Glycan_Deltas %>% 
               rownames_to_column(var = "ID"), 
             by = "ID")

Glycan_Deltas_vs_M12_Cor <- expand_grid(Marker = colnames(Glycan_Deltas), 
              Comparator = colnames(Comparator_Values_Delta)) %>% 
  mutate(test = map2(Marker, 
                     Comparator, ~ cor.test(Delta_vs_M12[[.x]], 
                                          Delta_vs_M12[[.y]], 
                                          method = "spearman", 
                                          exact  = FALSE)),
         rho = map_dbl(test, "estimate"), 
         p.value = map_dbl(test, "p.value", )) %>%
  mutate(P_adjust = p.adjust(p.value, method = "BH")) %>% 
  select(-test) %>% 
  mutate(Origin = sub("_.*$", "", Marker)) %>% 
  inner_join(Directions, by = c("Marker", "Origin")) %>% 
  rename(Correlation = "rho") %>% 
  mutate(Significance = case_when(p.value < 0.05 ~ "*"), 
         Comparator = factor(Comparator, levels = Comparator_Levels))

```

```{r Delta vs Month 12 visualisation}

Glycan_Deltas_vs_M12_Cor_Sign <- Glycan_Deltas_vs_M12_Cor %>%
  group_by(Marker) %>% 
  filter(any(Significance == "*")) %>% 
  ungroup()

Main_plot <- ggplot(Glycan_Deltas_vs_M12_Cor_Sign, aes(x = Comparator, y = Marker, fill = Correlation)) +
  geom_tile(color = "white", width = 1, height = 1) +
  scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                       midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                       guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                              title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
  facet_grid(Origin ~ ., scales = "free_y", space = "free_y") +
  # geom_text(aes(label = round(Correlation, 2)), size = 3) +
  geom_text(aes(label = Significance, vjust = 0.5, hjust = 0.5, fontface = "bold")) +
  scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), expand = c(0,0)) +
  scale_x_discrete(labels = function(x) {
    x <- gsub("_", " ", x)
    x <- gsub("Extra Renal", "Extra<br>Renal", x)
    x <- gsub("Renal Impairment", "Renal<br>Impairment", x)
    x }, expand = c(0,0)) +
  labs(title = "Correlations between glycan deltas and month 12 marker values", x = NULL, y = NULL,
       caption = paste0("Correlation coefficient used: <b>Spearman</b> 
       <br>P value: <b>Not adjusted</b>")) +
  theme_minimal(base_size = 12) +
  theme(strip.placement = "outside",
        strip.text.y.right = element_text(angle = 0, hjust = 0, vjust = 0.5, face  = "bold", margin = margin(l = 10)),
        axis.text.x = element_markdown(angle = 0, hjust = 0.5, face = "bold", colour = "black"), 
        axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
        panel.grid  = element_blank(), 
        panel.spacing = unit(1, "lines"), 
        plot.caption.position = "plot", 
        plot.caption = element_markdown(hjust = 0.9, vjust = 1),
        plot.title = element_markdown(face = "bold"))

n_markers <- Glycan_Deltas_vs_M12_Cor_Sign %>% 
    distinct(Marker) %>% 
    nrow()

plot_height <- max(n_markers * 0.3, 4)

# ggsave(Main_plot,
#        filename = "~/SLE/Glycans/Plots_2/Figure_4_Delta_Correlations/Delta_vs_Month_12_sign_only.jpeg",
#        width = 15, height = plot_height, dpi = 300)
```

```{r Figure 5 - Prepare dataframes for regressions}

Glycan_Hist <- read_xlsx("~/SLE/Glycans/Data/Glycan_Outcomes.xlsx") %>% 
  filter(ID %in% Dataframes_Final$ID) %>% 
  mutate(across(starts_with("Histological"), 
                ~ na_if(.x, "NA") %>% 
                  as.numeric())) %>% 
  pivot_longer(cols = -c("ID"), names_to = "Outcome", values_to = "Value_Hist") %>% 
  mutate(Outcome = str_replace_all(Outcome, "\\s*-\\s*", "_"))

Glycans_Data <- Dataframes_Final %>% 
  pivot_wider(id_cols = c(ID, Origin, Marker), names_from = Time_point, values_from = Value) %>% 
  mutate(Delta = T12 - T0, 
         Log2FC = log2(T12/T0))

Models_DF <- Glycans_Data %>% 
  inner_join(Glycan_Hist, by = "ID", relationship = "many-to-many")



```

```{r Non penalised regression}

Reg_Results_Basic <- Models_DF %>% 
  group_by(Marker, Outcome) %>% 
  nest() %>%
  mutate(fit_T0 = map(data, ~ glm(Value_Hist ~ T0, data = .x, family = "binomial")), 
         fit_T12 = map(data, ~ glm(Value_Hist ~ T12, data = .x, family = "binomial")), 
         fit_Delta = map(data, ~ glm(Value_Hist ~ Delta, data = .x, family = "binomial")), 
         fit_Log2FC = map(data, ~ glm(Value_Hist ~ Log2FC, data = .x, family = "binomial")), 
         
         Tidy_T0 = map2(fit_T0, "T0", ~tidy(.x) %>% filter(term == .y)), 
         Tidy_T12 = map2(fit_T12, "T12", ~tidy(.x) %>% filter(term == .y)), 
         Tidy_Delta = map2(fit_Delta, "Delta", ~tidy(.x) %>% filter(term == .y)),
         Tidy_Log2FC = map2(fit_Log2FC, "Log2FC", ~tidy(.x) %>% filter(term == .y))) %>% 
  
  select(Marker, Outcome, starts_with("Tidy_")) %>%
  pivot_longer(cols = starts_with("Tidy_"), 
               names_to = "Model", 
               values_to = "Tidy", 
               names_prefix = "Tidy_") %>% 
  unnest(Tidy) %>% 
  group_by(Model) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr")) %>% 
  ungroup() %>% 
  select(Marker, Outcome, Model, estimate, std.error, statistic, p.value, FDR)

Reg_Results_Basic %>% 
  filter(p.value < 0.05)

```


```{r Firths penalised regression}

Tidy_Firth <- function(fit, term) {
  est <- coef(fit)[term]
  se <- sqrt(diag(vcov(fit)))[term]
  stat <- est/se
  pval <- fit$prob[term]
  
  tibble(term = term, 
          estimate = est, 
          std.error = se,
          statistic = stat, 
          p.value = pval)
}

F_control <- logistf.control(maxit = 500, maxstep = 10)
PL_control <- logistpl.control(maxit = 200, maxstep = 50)

Reg_Results_Firth <- Models_DF %>% 
  group_by(Marker, Outcome) %>% 
  nest() %>%
  mutate(fit_T0 = map(data, ~ logistf(Value_Hist ~ T0, data = .x, 
                                      control = F_control, plcontrol = PL_control)), 
         fit_T12 = map(data, ~ logistf(Value_Hist ~ T12, data = .x, 
                                       control = F_control, plcontrol = PL_control)), 
         fit_Delta = map(data, ~ logistf(Value_Hist ~ Delta, data = .x, 
                                         control = F_control, plcontrol = PL_control)), 
         fit_Log2FC = map(data, ~ logistf(Value_Hist ~ Log2FC, data = .x, 
                                          control = F_control, plcontrol = PL_control)), 
         
         Tidy_T0 = map(fit_T0, ~ Tidy_Firth(.x, "T0")), 
         Tidy_T12 = map(fit_T12, ~ Tidy_Firth(.x, "T12")), 
         Tidy_Delta = map(fit_Delta, ~ Tidy_Firth(.x, "Delta")),
         Tidy_Log2FC = map(fit_Log2FC, ~ Tidy_Firth(.x, "Log2FC"))) %>% 
  
  select(Marker, Outcome, starts_with("Tidy_")) %>%
  pivot_longer(cols = starts_with("Tidy_"), 
               names_to = "Model", 
               values_to = "Tidy", 
               names_prefix = "Tidy_") %>% 
  unnest(Tidy) %>% 
  group_by(Model) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr")) %>% 
  ungroup() %>% 
  select(Marker, Outcome, Model, estimate, std.error, statistic, p.value, FDR)

Reg_Results_Firth %>% 
  filter(p.value < 0.05)

```

```{r Lasso and Ridge regression}

## Function to retrieve the values from the LR penalised regressions ##
Tidy_LR <- function(cvfit, term) {
  if (is.null(cvfit)) {
    return(tibble(term = term,
                  estimate = NA_real_,
                  std.error = NA_real_,
                  statistic = NA_real_,
                  p.value = NA_real_))
  }
  
  coef_mat <- as.matrix(coef(cvfit, s = "lambda.min"))
  est <- coef_mat[term, ]
  tibble(term = term,
         estimate = as.numeric(est),
         std.error = NA_real_,
         statistic = NA_real_,
         p.value = NA_real_)
}

## Lasso regression ##
Reg_Results_Lasso <- Models_DF %>% 
  group_by(Marker, Outcome) %>% 
  nest() %>%
  mutate(
    fit_T0_Lasso = map(data, ~ {
      mf <- model.frame(Value_Hist ~ T0, data = .x, na.action = na.omit)
      y <- model.response(mf)
      tab <- table(y)
      if (length(tab) < 2 || any(tab < 2L)) { return(NULL) }
      x <- model.matrix(Value_Hist ~ T0, data = .x[, -1, drop = FALSE])
      cv.glmnet(x, y, family = "binomial", alpha = 1)}),
    
    fit_T12_Lasso = map(data, ~ {
      mf <- model.frame(Value_Hist ~ T12, data = .x, na.action = na.omit)
      y <- model.response(mf)
      tab <- table(y)
      if (length(tab) < 2 || any(tab < 2L)) { return(NULL) }
      x <- model.matrix(Value_Hist ~ T12, data = .x[, -1, drop = FALSE])
      cv.glmnet(x, y, family = "binomial", alpha = 1)}),
    
    fit_Delta_Lasso = map(data, ~ {
      mf <- model.frame(Value_Hist ~ Delta, data = .x, na.action = na.omit)
      y <- model.response(mf)
      tab <- table(y)
      if (length(tab) < 2 || any(tab < 2L)) { return(NULL) }
      x <- model.matrix(Value_Hist ~ Delta, data = .x[, -1, drop = FALSE])
      cv.glmnet(x, y, family = "binomial", alpha = 1)}),
        
    fit_Log2FC_Lasso = map(data, ~ {
      mf <- model.frame(Value_Hist ~ Log2FC, data = .x, na.action = na.omit)
      y <- model.response(mf)
      tab <- table(y)
      if (length(tab) < 2 || any(tab < 2L)) { return(NULL) }
      x <- model.matrix(Value_Hist ~ Log2FC, data = .x[, -1, drop = FALSE])
      cv.glmnet(x, y, family = "binomial", alpha = 1)}),                        
    
    Tidy_T0_Lasso = map(fit_T0_Lasso, ~ Tidy_LR(.x, "T0")), 
    Tidy_T12_Lasso = map(fit_T12_Lasso, ~ Tidy_LR(.x, "T12")), 
    Tidy_Delta_Lasso = map(fit_Delta_Lasso, ~ Tidy_LR(.x, "Delta")),
    Tidy_Log2FC_Lasso = map(fit_Log2FC_Lasso, ~ Tidy_LR(.x, "Log2FC"))) %>% 
  
  select(Marker, Outcome, starts_with("Tidy_")) %>%
  pivot_longer(cols = starts_with("Tidy_"), 
               names_to = "Model", 
               values_to = "Tidy", 
               names_prefix = "Tidy_") %>% 
  unnest(Tidy) %>% 
  group_by(Model) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr")) %>% 
  ungroup() %>% 
  select(Marker, Outcome, Model, estimate, std.error, statistic, p.value, FDR)


## Ridge regression ##
Reg_Results_Ridge <- Models_DF %>% 
  group_by(Marker, Outcome) %>% 
  nest() %>%
  mutate(
    fit_T0_Ridge = map(data, ~ {
      mf <- model.frame(Value_Hist ~ T0, data = .x, na.action = na.omit)
      y <- model.response(mf)
      if (length(unique(y)) < 2) return(NULL)
      x <- model.matrix(Value_Hist ~ T0, data = .x[, -1, drop = FALSE])
      cv.glmnet(x, y, family = "binomial", alpha = 0)}),
    
    fit_T12_Ridge = map(data, ~ {
      mf <- model.frame(Value_Hist ~ T12, data = .x, na.action = na.omit)
      y <- model.response(mf)
      if (length(unique(y)) < 2) return(NULL)
      x <- model.matrix(Value_Hist ~ T12, data = .x[, -1, drop = FALSE])
      cv.glmnet(x, y, family = "binomial", alpha = 0)}),
    
    fit_Delta_Ridge = map(data, ~ {
      mf <- model.frame(Value_Hist ~ Delta, data = .x, na.action = na.omit)
      y <- model.response(mf)
      if (length(unique(y)) < 2) return(NULL)
      x <- model.matrix(Value_Hist ~ Delta, data = .x[, -1, drop = FALSE])
      cv.glmnet(x, y, family = "binomial", alpha = 0)}),
        
    fit_Log2FC_Ridge = map(data, ~ {
      mf <- model.frame(Value_Hist ~ Log2FC, data = .x, na.action = na.omit)
      y <- model.response(mf)
      if (length(unique(y)) < 2) return(NULL)
      x <- model.matrix(Value_Hist ~ Log2FC, data = .x[, -1, drop = FALSE])
      cv.glmnet(x, y, family = "binomial", alpha = 0)}),                         
    
    Tidy_T0_Ridge = map(fit_T0_Ridge, ~ Tidy_LR(.x, "T0")), 
    Tidy_T12_Ridge = map(fit_T12_Ridge, ~ Tidy_LR(.x, "T12")), 
    Tidy_Delta_Ridge = map(fit_Delta_Ridge, ~ Tidy_LR(.x, "Delta")),
    Tidy_Log2FC_Ridge = map(fit_Log2FC_Ridge, ~ Tidy_LR(.x, "Log2FC"))) %>% 
  
  select(Marker, Outcome, starts_with("Tidy_")) %>%
  pivot_longer(cols = starts_with("Tidy_"), 
               names_to = "Model", 
               values_to = "Tidy", 
               names_prefix = "Tidy_") %>% 
  unnest(Tidy) %>% 
  group_by(Model) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr")) %>% 
  ungroup() %>% 
  select(Marker, Outcome, Model, estimate, std.error, statistic, p.value, FDR)


```

