```{r Libraries}

## Load the libraries ##
library(tidyverse)
library(readxl)
library(purrr)
library(broom)
library(broom.helpers)
library(ggtext)
library(ggplot2)
library(logistf) ## Firth’s logistf() ##
library(glmnet) ## Penalised regression ##
library(patchwork)

library(ggtext)
library(ggrepel)

```

```{r Figure 5 - Prepare dataframes for regressions}

Marker_DF <- read_csv(file = "~/SLE/Glycans/Output_Data/Glycans_marker_data_total.csv")

Glycan_Hist <- read_xlsx("~/SLE/Glycans/Data/Glycan_Outcomes.xlsx") %>% 
  filter(ID %in% Marker_DF$ID) %>% 
  mutate(across(starts_with("Histological"), 
                ~ na_if(.x, "NA") %>% 
                  as.numeric())) %>% 
  pivot_longer(cols = -c("ID"), names_to = "Outcome", values_to = "Value_Hist") %>% 
  mutate(Outcome = str_replace_all(Outcome, "\\s*-\\s*", "_"))

Histological <- Glycan_Hist %>% 
  filter(str_starts(Outcome, "Histological_")) %>%
  group_by(ID) %>%
  summarize(Value_Hist = {
    vals <- Value_Hist
    u <- unique(vals[!is.na(vals)])
    if (length(u)==1) u else NA_real_ },
    .groups = "drop") %>%
  mutate(Outcome = "Histological")

Glycan_Hist_Clean <- Glycan_Hist %>% 
  filter(Outcome == "Clinical") %>% 
  bind_rows(Histological) %>% 
  arrange(parse_number(ID), Outcome)

Glycans_Data <- Marker_DF %>% 
  pivot_wider(id_cols = c(ID, Origin, Marker), names_from = Time_point, values_from = Value) %>% 
  mutate(Delta = T12 - T0, 
         Log2FC = log2(T12/T0))

Models_DF <- Glycans_Data %>% 
  inner_join(Glycan_Hist_Clean, by = "ID", relationship = "many-to-many")

# write_csv(Models_DF, file = "~/SLE/Glycans/Output_Data/Glycans_outcome_data_clean.csv")

```

```{r Non penalised regression}

Reg_Results_Basic <- Models_DF %>% 
  group_by(Marker, Outcome) %>% 
  nest() %>%
  mutate(fit_T0 = map(data, ~ glm(Value_Hist ~ T0, data = .x, family = "binomial")), 
         fit_T12 = map(data, ~ glm(Value_Hist ~ T12, data = .x, family = "binomial")), 
         fit_Delta = map(data, ~ glm(Value_Hist ~ Delta, data = .x, family = "binomial")), 
         fit_Log2FC = map(data, ~ glm(Value_Hist ~ Log2FC, data = .x, family = "binomial")), 
         
         Tidy_T0 = map2(fit_T0, "T0", ~tidy(.x) %>% filter(term == .y)), 
         Tidy_T12 = map2(fit_T12, "T12", ~tidy(.x) %>% filter(term == .y)), 
         Tidy_Delta = map2(fit_Delta, "Delta", ~tidy(.x) %>% filter(term == .y)),
         Tidy_Log2FC = map2(fit_Log2FC, "Log2FC", ~tidy(.x) %>% filter(term == .y))) %>% 
  
  select(Marker, Outcome, starts_with("Tidy_")) %>%
  pivot_longer(cols = starts_with("Tidy_"), 
               names_to = "Model", 
               values_to = "Tidy", 
               names_prefix = "Tidy_") %>% 
  unnest(Tidy) %>% 
  group_by(Model) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr")) %>% 
  ungroup() %>% 
  select(Marker, Outcome, Model, estimate, std.error, statistic, p.value, FDR)

Reg_Results_Basic %>% 
  filter(p.value < 0.05)

Reg_Results_Basic_stats <- Reg_Results_Basic %>% 
  mutate(OR = exp(estimate), 
         log10OR = log10(OR), 
         CI_lower = estimate - 1.96 * std.error,
         CI_upper = estimate + 1.96 * std.error, 
         Significance = if_else(p.value < 0.05, "Significant", "Not Significant"))

# write_csv(Reg_Results_Basic, file = "~/SLE/Glycans/Output_Data/GLM_results_normal.csv")

```

```{r Firths penalised regression}

Tidy_Firth <- function(fit, term) {
  est <- coef(fit)[term]
  se <- sqrt(diag(vcov(fit)))[term]
  stat <- est/se
  pval <- fit$prob[term]
  
  tibble(term = term, 
          estimate = est, 
          std.error = se,
          statistic = stat, 
          p.value = pval)
}

F_control <- logistf.control(maxit = 500, maxstep = 10)
PL_control <- logistpl.control(maxit = 200, maxstep = 50)

Reg_Results_Firth <- Models_DF %>% 
  group_by(Marker, Outcome) %>% 
  nest() %>%
  mutate(fit_T0 = map(data, ~ logistf(Value_Hist ~ T0, data = .x, 
                                      control = F_control, plcontrol = PL_control)), 
         fit_T12 = map(data, ~ logistf(Value_Hist ~ T12, data = .x, 
                                       control = F_control, plcontrol = PL_control)), 
         fit_Delta = map(data, ~ logistf(Value_Hist ~ Delta, data = .x, 
                                         control = F_control, plcontrol = PL_control)), 
         fit_Log2FC = map(data, ~ logistf(Value_Hist ~ Log2FC, data = .x, 
                                          control = F_control, plcontrol = PL_control)), 
         
         Tidy_T0 = map(fit_T0, ~ Tidy_Firth(.x, "T0")), 
         Tidy_T12 = map(fit_T12, ~ Tidy_Firth(.x, "T12")), 
         Tidy_Delta = map(fit_Delta, ~ Tidy_Firth(.x, "Delta")),
         Tidy_Log2FC = map(fit_Log2FC, ~ Tidy_Firth(.x, "Log2FC"))) %>% 
  
  select(Marker, Outcome, starts_with("Tidy_")) %>%
  pivot_longer(cols = starts_with("Tidy_"), 
               names_to = "Model", 
               values_to = "Tidy", 
               names_prefix = "Tidy_") %>% 
  unnest(Tidy) %>% 
  group_by(Model) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr")) %>% 
  ungroup() %>% 
  select(Marker, Outcome, Model, estimate, std.error, statistic, p.value, FDR)

Reg_Results_Firth_stats %>% 
  filter(p.value < 0.05)

Reg_Results_Firth_stats <- Reg_Results_Firth %>% 
  mutate(OR = exp(estimate), 
         log10OR = log10(OR), 
         CI_lower = estimate - 1.96 * std.error,
         CI_upper = estimate + 1.96 * std.error, 
         Significance = if_else(p.value < 0.05, "Significant", "Not Significant"))

# write_csv(Reg_Results_Firth, file = "~/SLE/Glycans/Output_Data/GLM_results_firth.csv")

```

```{r Lasso and Ridge regression}

## Function to retrieve the values from the LR penalised regressions ##
# Tidy_LR <- function(cvfit, term) {
#   if (is.null(cvfit)) {
#     return(tibble(term = term,
#                   estimate = NA_real_,
#                   std.error = NA_real_,
#                   statistic = NA_real_,
#                   p.value = NA_real_))
#   }
#   
#   coef_mat <- as.matrix(coef(cvfit, s = "lambda.min"))
#   est <- coef_mat[term, ]
#   tibble(term = term,
#          estimate = as.numeric(est),
#          std.error = NA_real_,
#          statistic = NA_real_,
#          p.value = NA_real_)
# }
# 
# ## Lasso regression ##
# Reg_Results_Lasso <- Models_DF %>% 
#   group_by(Marker, Outcome) %>% 
#   nest() %>%
#   mutate(
#     fit_T0_Lasso = map(data, ~ {
#       mf <- model.frame(Value_Hist ~ T0, data = .x, na.action = na.omit)
#       y <- model.response(mf)
#       tab <- table(y)
#       if (length(tab) < 2 || any(tab < 2L)) { return(NULL) }
#       x <- model.matrix(Value_Hist ~ T0, data = .x[, -1, drop = FALSE])
#       cv.glmnet(x, y, family = "binomial", alpha = 1)}),
#     
#     fit_T12_Lasso = map(data, ~ {
#       mf <- model.frame(Value_Hist ~ T12, data = .x, na.action = na.omit)
#       y <- model.response(mf)
#       tab <- table(y)
#       if (length(tab) < 2 || any(tab < 2L)) { return(NULL) }
#       x <- model.matrix(Value_Hist ~ T12, data = .x[, -1, drop = FALSE])
#       cv.glmnet(x, y, family = "binomial", alpha = 1)}),
#     
#     fit_Delta_Lasso = map(data, ~ {
#       mf <- model.frame(Value_Hist ~ Delta, data = .x, na.action = na.omit)
#       y <- model.response(mf)
#       tab <- table(y)
#       if (length(tab) < 2 || any(tab < 2L)) { return(NULL) }
#       x <- model.matrix(Value_Hist ~ Delta, data = .x[, -1, drop = FALSE])
#       cv.glmnet(x, y, family = "binomial", alpha = 1)}),
#         
#     fit_Log2FC_Lasso = map(data, ~ {
#       mf <- model.frame(Value_Hist ~ Log2FC, data = .x, na.action = na.omit)
#       y <- model.response(mf)
#       tab <- table(y)
#       if (length(tab) < 2 || any(tab < 2L)) { return(NULL) }
#       x <- model.matrix(Value_Hist ~ Log2FC, data = .x[, -1, drop = FALSE])
#       cv.glmnet(x, y, family = "binomial", alpha = 1)}),                        
#     
#     Tidy_T0_Lasso = map(fit_T0_Lasso, ~ Tidy_LR(.x, "T0")), 
#     Tidy_T12_Lasso = map(fit_T12_Lasso, ~ Tidy_LR(.x, "T12")), 
#     Tidy_Delta_Lasso = map(fit_Delta_Lasso, ~ Tidy_LR(.x, "Delta")),
#     Tidy_Log2FC_Lasso = map(fit_Log2FC_Lasso, ~ Tidy_LR(.x, "Log2FC"))) %>% 
#   
#   select(Marker, Outcome, starts_with("Tidy_")) %>%
#   pivot_longer(cols = starts_with("Tidy_"), 
#                names_to = "Model", 
#                values_to = "Tidy", 
#                names_prefix = "Tidy_") %>% 
#   unnest(Tidy) %>% 
#   group_by(Model) %>% 
#   mutate(FDR = p.adjust(p.value, method = "fdr")) %>% 
#   ungroup() %>% 
#   select(Marker, Outcome, Model, estimate, std.error, statistic, p.value, FDR)
# 
# 
# ## Ridge regression ##
# Reg_Results_Ridge <- Models_DF %>% 
#   group_by(Marker, Outcome) %>% 
#   nest() %>%
#   mutate(
#     fit_T0_Ridge = map(data, ~ {
#       mf <- model.frame(Value_Hist ~ T0, data = .x, na.action = na.omit)
#       y <- model.response(mf)
#       if (length(unique(y)) < 2) return(NULL)
#       x <- model.matrix(Value_Hist ~ T0, data = .x[, -1, drop = FALSE])
#       cv.glmnet(x, y, family = "binomial", alpha = 0)}),
#     
#     fit_T12_Ridge = map(data, ~ {
#       mf <- model.frame(Value_Hist ~ T12, data = .x, na.action = na.omit)
#       y <- model.response(mf)
#       if (length(unique(y)) < 2) return(NULL)
#       x <- model.matrix(Value_Hist ~ T12, data = .x[, -1, drop = FALSE])
#       cv.glmnet(x, y, family = "binomial", alpha = 0)}),
#     
#     fit_Delta_Ridge = map(data, ~ {
#       mf <- model.frame(Value_Hist ~ Delta, data = .x, na.action = na.omit)
#       y <- model.response(mf)
#       if (length(unique(y)) < 2) return(NULL)
#       x <- model.matrix(Value_Hist ~ Delta, data = .x[, -1, drop = FALSE])
#       cv.glmnet(x, y, family = "binomial", alpha = 0)}),
#         
#     fit_Log2FC_Ridge = map(data, ~ {
#       mf <- model.frame(Value_Hist ~ Log2FC, data = .x, na.action = na.omit)
#       y <- model.response(mf)
#       if (length(unique(y)) < 2) return(NULL)
#       x <- model.matrix(Value_Hist ~ Log2FC, data = .x[, -1, drop = FALSE])
#       cv.glmnet(x, y, family = "binomial", alpha = 0)}),                         
#     
#     Tidy_T0_Ridge = map(fit_T0_Ridge, ~ Tidy_LR(.x, "T0")), 
#     Tidy_T12_Ridge = map(fit_T12_Ridge, ~ Tidy_LR(.x, "T12")), 
#     Tidy_Delta_Ridge = map(fit_Delta_Ridge, ~ Tidy_LR(.x, "Delta")),
#     Tidy_Log2FC_Ridge = map(fit_Log2FC_Ridge, ~ Tidy_LR(.x, "Log2FC"))) %>% 
#   
#   select(Marker, Outcome, starts_with("Tidy_")) %>%
#   pivot_longer(cols = starts_with("Tidy_"), 
#                names_to = "Model", 
#                values_to = "Tidy", 
#                names_prefix = "Tidy_") %>% 
#   unnest(Tidy) %>% 
#   group_by(Model) %>% 
#   mutate(FDR = p.adjust(p.value, method = "fdr")) %>% 
#   ungroup() %>% 
#   select(Marker, Outcome, Model, estimate, std.error, statistic, p.value, FDR)


```

```{r Model visualisation}

plot_GLM_results <- function(Dataframe_GLM, Model_Type) {
  
  DF_Plot_clean <- Dataframe_GLM %>% 
    filter(Model != "T0") %>% 
    mutate(Model = sub("Log2FC", "Log<sub>2</sub>FC", Model), 
           Label = gsub("_", " ", Marker), 
           log_p = -log10(p.value))  
    
  top_10_markers <- DF_Plot_clean %>% 
    group_by(Model) %>% 
    slice_min(order_by = p.value, n = 10, with_ties = FALSE) %>% 
    ungroup()
    
    ggplot(DF_Plot_clean, aes(x = log10OR, y = -log10(p.value))) +
    geom_point(aes(color = Outcome, alpha = Significance), size = 2) +
    geom_text_repel(data = top_10_markers, 
                    inherit.aes = FALSE, 
                    aes(x = log10OR, y = log_p, label = Label),
                    color = "black", 
                    size = 3, 
                    force = 2,
                    box.padding = 0.3, 
                    point.padding = 0.1, 
                    segment.color = NA, 
                    max.overlaps = Inf, 
                    min.segment.length = 0) +  
    scale_colour_manual(breaks = c("Clinical", "Histological"), 
                        values = c("midnightblue", "coral1"), 
                        name = "Response") +
    scale_alpha_manual(values = c("Significant" = 1.0, 
                                  "Not Significant" = 0.2), 
                                  guide = "none") +
    scale_x_continuous(limits = c(-10, 10),
                       breaks = seq(-10, 10, by = 5),
                       expand = expansion(mult = c(0.05, 0.05))) +
    labs(title = paste0("Logistic regression results - ", Model_Type," model
                        <br>Marker data vs histological and clinical responses"), 
           x = "Odds Ratio (Log<sub>10</sub>)", 
           y = "P value (-Log<sub>10</sub>)") + 
    geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +  
    geom_vline(xintercept = 0, linetype = "dashed", color = "black") +  
    facet_wrap(~ Model, ncol = 3, scales = "free_x") +
    theme_minimal(base_size = 14) +
    theme(plot.title = element_markdown(hjust = 0, face = "bold", size = 14),
          legend.title = element_markdown(face = "bold"), 
          legend.text = element_markdown(face = "bold"), 
          axis.title.x = element_markdown(face = "bold"), 
          axis.title.y = element_markdown(face = "bold"), 
          strip.text.x.top = element_markdown(hjust = 0.5, vjust = 0.5, face  = "bold"),
          plot.caption.position = "plot", 
          plot.caption = element_markdown(hjust = 0.9, vjust = 1),
          panel.grid.major = element_line(color = "grey90"),
          panel.grid.minor = element_blank())
}

Firth_GLM_Plot <- plot_GLM_results(Reg_Results_Firth_stats, "Firth's penalised")
Normal_GLM_Plot <- plot_GLM_results(Reg_Results_Basic_stats, "non penalised")

# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_5_GLMs/Volcano_Firth_GLM.jpeg"),
#        plot = Firth_GLM_Plot, width = 30, height = 10, dpi = 300, device = "jpeg")
# 
# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_5_GLMs/Volcano_Normal_GLM.jpeg"),
#        plot = Normal_GLM_Plot,width = 30, height = 10, dpi = 300, device = "jpeg")

```

```{r}

Sign_Markers <- Reg_Results_Firth_stats %>% 
  filter(Model != "T0") %>% 
  filter(p.value < 0.05) %>% 
  group_by(Marker) %>%
  summarize(
    clinical_sig   = any(Outcome == "Clinical"),
    histo_sig      = any(Outcome == "Histological"),
    .groups = "drop"
  ) %>%
  
  # 3) keep only those with both TRUE
  filter(clinical_sig & histo_sig) %>% 
  select(Marker) %>% pull()

Double_Sign_Markers <- Reg_Results_Firth_stats %>%
  filter(Model != "T0",
         Marker %in% Sign_Markers) %>%
  pull(Marker)

```

```{r}

plot_GLM_results <- function(Dataframe_GLM, Method, Model_Type, Double_Sign_Markers) {
  
  DF_Plot <- Dataframe_GLM %>% 
    filter(Model == Method) %>% 
    mutate(Title = case_when(Model == "T0" ~ "baseline", 
                             Model == "Delta" ~ "delta", 
                             Model == "T12" ~ "month 12", 
                             Model == "Log2FC" ~ "log<sub>2</sub>FC", 
                             TRUE ~ "Yeet"))

  Current_Title <- DF_Plot %>% 
    select(Title) %>% 
    distinct() %>% 
    pull()
  
  Sign_Markers_current <- DF_Plot %>% 
    filter(p.value < 0.05) %>% 
    group_by(Marker) %>%
    summarize(clinical_sig = any(Outcome == "Clinical"),
              histo_sig = any(Outcome == "Histological"),
              .groups = "drop") %>%
    filter(clinical_sig & histo_sig) %>% 
    select(Marker) %>% pull()
  
    DF_Plot_clean <- DF_Plot %>% 
    mutate(Model = sub("Log2FC", "Log<sub>2</sub>FC", Model)) %>% 
    mutate(Highlight = case_when(Marker %in% Sign_Markers_current ~ "Significant in both<br>response types models", 
                                 Significance == "Significant" ~ "Significant in one model",
                                 TRUE ~ "Not significant"), 
           Label = gsub("_", " ", Marker))

  Double_sign_Plot <- ggplot(DF_Plot_clean, aes(x = log10(OR), y = -log10(p.value))) +
    geom_point(aes(color = Highlight, alpha = Significance), size = 2) +
    geom_text_repel(data = DF_Plot_clean %>% filter(Marker %in% Sign_Markers_current), 
                    aes(label = Label), 
                    color = "black", 
                    size = 3, 
                    force = 2,
                    box.padding = 0.3, 
                    point.padding = 0.1, 
                    segment.color = NA, 
                    max.overlaps = Inf, 
                    min.segment.length = 0) +
    scale_colour_manual(values = c("Significant in both<br>response types models" = "deeppink3", 
                                   "Significant in one model" = "royalblue", 
                                   "Not significant" = "grey")) +
    scale_alpha_manual(values = c("Significant" = 1.0, 
                                  "Not Significant" = 0.2), 
                                  guide = "none") +
    scale_x_continuous(limits = c(-10, 10),
                       breaks = seq(-10, 10, by = 5),
                       expand = expansion(mult = c(0.05, 0.05))) +
  labs(title = paste0("Logistic regression results - ", Model_Type," model
                      <br>Marker data vs histological and clinical responses using ", Current_Title," comparisons"), 
           x = "Odds Ratio (Log<sub>10</sub>)", 
           y = "P value (-Log<sub>10</sub>)") + 
    geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +  
    geom_vline(xintercept = 0, linetype = "dashed", color = "black") +  
    facet_wrap(~ Outcome, ncol = 2, scales = "free_x") +
    theme_minimal(base_size = 14) +
    theme(plot.title = element_markdown(hjust = 0, face = "bold", size = 14),
          # legend.title = element_markdown(face = "bold"), 
          legend.title = element_blank(), 
          legend.text = element_markdown(face = "bold"), 
          axis.title.x = element_markdown(face = "bold"), 
          axis.title.y = element_markdown(face = "bold"), 
          strip.text.x.top = element_markdown(hjust = 0.5, vjust = 0.5, face  = "bold"),
          plot.caption.position = "plot", 
          plot.caption = element_markdown(hjust = 0.9, vjust = 1),
          panel.grid.major = element_line(color = "grey90"),
          panel.grid.minor = element_blank()) 
          
}

Firth_Double_sign_log2 <- plot_GLM_results(Reg_Results_Firth_stats, "Log2FC", "Firth's penalised", Double_Sign_Markers)
Firth_Double_sign_delta <- plot_GLM_results(Reg_Results_Firth_stats, "Delta", "Firth's penalised", Double_Sign_Markers)
Firth_Double_sign_M12 <- plot_GLM_results(Reg_Results_Firth_stats, "T12", "Firth's penalised", Double_Sign_Markers)
Firth_Double_sign_T0 <- plot_GLM_results(Reg_Results_Firth_stats, "T0", "Firth's penalised", Double_Sign_Markers)


# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_5_GLMs/Volcano_Firth_Double_sign_log2.jpeg"),
#        plot = Firth_Double_sign_log2, width = 12, height = 8, dpi = 300, device = "jpeg")
# 
# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_5_GLMs/Volcano_Firth_Double_sign_delta.jpeg"),
#        plot = Firth_Double_sign_delta, width = 12, height = 8, dpi = 300, device = "jpeg")
# 
# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_5_GLMs/Volcano_Firth_Double_sign_M12.jpeg"),
#        plot = Firth_Double_sign_M12, width = 12, height = 8, dpi = 300, device = "jpeg")

```

```{r Volcano plot with T0 instead of log2FC}

plot_GLM_results2 <- function(Dataframe_GLM, Model_Type) {
  
  DF_Plot_clean <- Dataframe_GLM %>% 
    filter(Model != "Log2FC") %>% 
    mutate(Label = gsub("_", " ", Marker), 
           log_p = -log10(p.value), 
           Model = factor(Model, levels = c("T0", "T12", "Delta")))  
    
  top_10_markers <- DF_Plot_clean %>% 
    group_by(Model) %>% 
    slice_min(order_by = p.value, n = 10, with_ties = FALSE) %>% 
    ungroup()
    
    ggplot(DF_Plot_clean, aes(x = log10OR, y = -log10(p.value))) +
    geom_point(aes(color = Outcome, alpha = Significance), size = 2) +
    geom_text_repel(data = top_10_markers, 
                    inherit.aes = FALSE, 
                    aes(x = log10OR, y = log_p, label = Label),
                    color = "black", 
                    size = 4, 
                    force = 2,
                    box.padding = 0.3, 
                    point.padding = 0.1, 
                    segment.color = NA, 
                    max.overlaps = Inf, 
                    min.segment.length = 0) +  
    scale_colour_manual(breaks = c("Clinical", "Histological"), 
                        values = c("midnightblue", "coral1"), 
                        name = "Response") +
    scale_alpha_manual(values = c("Significant" = 1.0, 
                                  "Not Significant" = 0.2), 
                                  guide = "none") +
    scale_x_continuous(limits = c(-10, 10),
                       breaks = seq(-10, 10, by = 5),
                       expand = expansion(mult = c(0.05, 0.05))) +
    labs(title = paste0("Logistic regression results - ", Model_Type," model
                        <br>Marker data vs histological and clinical responses"), 
           x = "Odds Ratio (Log<sub>10</sub>)", 
           y = "P value (-Log<sub>10</sub>)") + 
    geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +  
    geom_vline(xintercept = 0, linetype = "dashed", color = "black") +  
    facet_wrap(~ Model, ncol = 1, nrow = 3, scales = "free_x") +
    theme_minimal(base_size = 14) +
    theme(plot.title = element_markdown(hjust = 0, face = "bold", size = 14),
          legend.title = element_markdown(face = "bold"), 
          legend.text = element_markdown(face = "bold", size = 11), 
          axis.title.x = element_markdown(face = "bold"), 
          axis.title.y = element_markdown(face = "bold"), 
          strip.text.x.top = element_markdown(hjust = 0.5, vjust = 0.5, face  = "bold"),
          plot.caption.position = "plot", 
          plot.caption = element_markdown(hjust = 0.9, vjust = 1),
          panel.grid.major = element_line(color = "grey90"),
          panel.grid.minor = element_blank())
}

Firth_GLM_Plot2 <- plot_GLM_results2(Reg_Results_Firth_stats, "Firth's penalised")

# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_5_GLMs/Volcano_Firth_GLM_with_Baseline_A4.jpeg"),
#        plot = Firth_GLM_Plot2, width = 210, height = 297, units = "mm", scale = 2, dpi = 300, device = "jpeg")
# 
# ggsave(filename = paste0("~/SLE/Glycans/Plots_2/Figure_5_GLMs/Volcano_Firth_GLM_with_Baseline.jpeg"),
#        plot = Firth_GLM_Plot2, width = 330, height = 200, units = "mm", scale = 2, dpi = 300, device = "jpeg")

```









```{r}

plot_GLM_results_final <- function(Dataframe_GLM, Method, Double_Sign_Markers) {

  lgnd_cols <- c("Significant in both<br>response types" = "deeppink3",
                 "Significant in<br>clinical response" = "royalblue", 
                 "Significant in<br>histological response" = "mediumspringgreen",
                 "Not significant" = "grey80")

  legend_df <- tibble(OR = 1,
                      p.value = 1,
                      Highlight = names(lgnd_cols),
                      Significance = "Not Significant")

  DF_Summary <- Dataframe_GLM %>% 
    filter(Model == Method) %>%
    filter(p.value < 0.05) %>%
    group_by(Marker) %>%
    summarize(clinical_sig = any(Outcome == "Clinical"),
              histo_sig = any(Outcome == "Histological"),
              .groups = "drop")
    
  DF_Plot <- Dataframe_GLM %>% 
    filter(Model == Method) %>%
    mutate(Title = case_when(Model == "T0" ~ "baseline", 
                             Model == "Delta" ~ "delta", 
                             Model == "T12" ~ "month 12", 
                             Model == "Log2FC" ~ "log<sub>2</sub>FC", 
                             TRUE ~ "Yeet")) %>% 
    left_join(DF_Summary, by = "Marker") %>%
    mutate(Model = sub("Log2FC", "Log<sub>2</sub>FC", Model), 
             Highlight = case_when(clinical_sig & histo_sig  ~ "Significant in both<br>response types",
                                   clinical_sig & !histo_sig ~ "Significant in<br>clinical response", 
                                   !clinical_sig & histo_sig ~ "Significant in<br>histological response",
                                   TRUE ~ "Not significant"), 
             Label = gsub("_", " ", Marker), 
             Highlight = factor(Highlight, levels = c("Significant in both<br>response types", 
                                                      "Significant in<br>clinical response",
                                                      "Significant in<br>histological response",
                                                      "Not significant")))

  Current_Title <- DF_Plot %>% 
    select(Title) %>% 
    distinct() %>% 
    pull()
  
  Sign_Markers_current <- DF_Plot %>% 
    filter(p.value < 0.05) %>% 
    group_by(Marker) %>%
    filter(clinical_sig & histo_sig) %>% 
    select(Marker) %>% 
    distinct() %>% 
    pull() 

  Double_sign_Plot <- ggplot(DF_Plot, aes(x = log10(OR), y = -log10(p.value))) +
    # geom_point(data = legend_df, aes(x = log10(OR), y = -log10(p.value), size = 0)) +
    geom_point(data = DF_Plot, aes(color = Highlight, alpha = Significance), size = 2, show.legend = TRUE) +
    geom_text_repel(data = DF_Plot %>% filter(Highlight == "Significant in both<br>response types"), 
                    aes(label = Label), 
                    color = "black", 
                    size = 4, 
                    force = 2,
                    box.padding = 0.3, 
                    point.padding = 0.1, 
                    segment.color = NA, 
                    max.overlaps = Inf, 
                    min.segment.length = 0) +
    scale_colour_manual(values = lgnd_cols, 
                        limits = names(lgnd_cols),
                        drop = FALSE) +
    scale_alpha_manual(values = c("Significant" = 1.0, 
                                  "Not Significant" = 0.2), 
                                  guide = "none") +
    scale_x_continuous(limits = c(-10, 10),
                       breaks = seq(-10, 10, by = 5),
                       expand = expansion(mult = c(0.05, 0.05))) +
    facet_wrap(~ Outcome, ncol = 2, scales = "free_x") +
    labs(title = paste0("Comparisons using ", Current_Title, " values"), 
         x = "Odds Ratio (Log<sub>10</sub>)", 
         y = "P value (-Log<sub>10</sub>)") + 
    geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +  
    geom_vline(xintercept = 0, linetype = "dashed", color = "black") +  
    theme_minimal(base_size = 14) +
    theme(plot.title = element_markdown(hjust = 0, face = "bold", size = 14),
          # legend.title = element_markdown(face = "bold"), 
          legend.title = element_blank(), 
          legend.text = element_markdown(face = "bold", padding = unit(1, "lines")), 
          # legend.key.spacing = unit(1.5, "lines"), 
          axis.title.x = element_markdown(face = "bold"), 
          axis.title.y = element_markdown(face = "bold"), 
          strip.text.x.top = element_markdown(size = 11, hjust = 0.5, vjust = 0.5, face  = "bold"),
          plot.caption.position = "plot", 
          plot.caption = element_markdown(hjust = 0.9, vjust = 1),
          panel.grid.major = element_line(color = "grey90"),
          panel.grid.minor = element_blank()) 
  
    # if (Method == "T0") {
    # Double_sign_Plot <- Double_sign_Plot +
    #   theme(legend.position = "none") }
  
  Double_sign_Plot
          
}

Double_log2 <- plot_GLM_results_final(Reg_Results_Firth_stats, "Log2FC", Double_Sign_Markers)
Double_delta <- plot_GLM_results_final(Reg_Results_Firth_stats, "Delta", Double_Sign_Markers)
Double_M12 <- plot_GLM_results_final(Reg_Results_Firth_stats, "T12", Double_Sign_Markers)
Double_T0 <- plot_GLM_results_final(Reg_Results_Firth_stats, "T0", Double_Sign_Markers)

```



```{r}

Yeet <- wrap_plots(Double_delta, Double_M12, Double_T0, 
           ncol = 1, 
           guides = "collect") +
  plot_annotation(tag_levels = "A", 
                  title = "Firth penalised logistic regression 
                  <br>Comparison between marker values and clinical/histological outcomes",
                  theme = theme(plot.title = element_text(face = "bold", size = 23),
                                plot.title.position = "plot", 
                                plot.title.hjust = 0.5,       
                                plot.tag = element_text(face = "bold", 
                                                        colour = "black", 
                                                        size = 30))) +
  plot_layout(axis_titles = "collect") &
  theme(plot.title = element_markdown(face = "bold"), 
        legend.position = "right",
        legend.title = element_text(face = "bold"),
        legend.key.width = unit(2, "lines"),
        legend.key.height = unit(4, "lines"),    
        legend.spacing.y = unit(0.5, "lines"))

Yeet <- Yeet & theme(plot.tag = element_text(color = "black", face = "bold", size = 30))

ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_5_GLMs/Firth_BM12Delta.jpeg",
       plot = Yeet, width  = 210, height = 297, units = "mm", dpi = 300, scale = 2, device = "jpeg")

```

