---
title: "Glycans analysis"
output:
  pdf_document: default
  html_document:
    df_print: kable
---

```{r Libraries, }

## Load the libraries ##
library(tidyverse)
library(readxl)
library(purrr)
library(broom)
library(ggtext)
library(patchwork)
library(caret)
library(jtools)
library(ggplot2)
library(rlang)
library(logistf) ## Firth’s logistf() ##
library(glmnet) ## Penalised regression ##
library(broom.helpers)
library(scales)
library(patchwork)
library(grid)
library(scales)
library(writexl)

```

```{r Load the data}

AGP_Data <- read_xlsx("~/SLE/Glycans/Data/LN_AGP_glycopeptide-data.xlsx")
C3_Data <- read_xlsx("~/SLE/Glycans/Data/LN_C3_glycopeptide_data.xlsx")
Serum_Data <- read_xlsx("~/SLE/Glycans/Data/LN_serum_glycome_data.xlsx")
Decreased_data <- read_xlsx("~/SLE/Glycans/Data/decreased.xlsx")
Increased_data <- read_xlsx("~/SLE/Glycans/Data/increased.xlsx")
IgG_FAB_Data <- read_xlsx("~/SLE/Glycans/Data/LN_total_IgG_Fab_data.xlsx")
IgG_FC_Data <- read_xlsx("~/SLE/Glycans/Data/LN_total_IgG_Fc_data.xlsx")
IgG_Meta <- read_xlsx("~/SLE/Glycans/Data/LN_total_IgG_glycomedata.xlsx")
Glycan_Outcomes <- read_xlsx("~/SLE/Glycans/Data/Glycans_Outcomes.xlsx")

```


```{r Prep slightly}

Comparators <- c("AI", "CI", "S-creatinine", "eGFR", "UPCR", "albumin", "total", "extra-renal", "Renal Impairment", "Clinical")

Comparator_Values <- Increased_data %>%
  rename(ID = `Patient number`, Time_point = `Time point`) %>%
  select(ID, Time_point, any_of(Comparators)) %>%
  rename(Renal_Impairment = `Renal Impairment`,
         Extra_Renal = `extra-renal`,
         S_creatinine = `S-creatinine`, 
         Clinical_Response = Clinical, 
         SLEDAI = total) %>%
  mutate(Identification = paste0(ID, " ", Time_point)) %>%
  select(-c(ID, Time_point)) %>%
  select(Identification, everything()) %>%
  column_to_rownames("Identification") %>%
  mutate(AI = as.numeric(AI),
         CI = as.numeric(CI))

```

```{r Make dtaaframes long}

Dataframes <- list(AGP = AGP_Data, 
                   C3 = C3_Data, 
                   Serum = Serum_Data,
                   Fab = IgG_FAB_Data, 
                   Fc = IgG_FC_Data, 
                   IgG = IgG_Meta)

Process_DFs <- function(df){
  df %>% 
    select(-c(Sample, `ID_St Luc`)) %>% 
    rename(ID = `Patient number`, Time_point = `Time point`) %>% 
    mutate(across(.cols = -c(ID, Time_point), .fns  = as.numeric)) %>% 
    pivot_longer(cols = -c(ID, Time_point), names_to   = "Marker", values_to  = "Value")
}

Long_Dataframes <- map(Dataframes, Process_DFs)

```

```{r Get the direction of each marker}

Directions_List <- imap(Long_Dataframes, ~ {
  df <- .x
  prefix <- .y
  
  df %>% 
    mutate(Marker_Timepoint = paste0(Marker, Time_point)) %>%
    group_by(Marker_Timepoint) %>%
    summarise(Mean = mean(Value, na.rm = TRUE), .groups = "drop") %>%
    extract(col = Marker_Timepoint, 
          into = c("Marker", "Timepoint"), 
          regex = "(.+)(T0|T12)$") %>% 
    pivot_wider(names_from = "Timepoint", values_from = "Mean") %>% 
    mutate(Direction = case_when(T12 > T0 ~ "Increase", 
                                 T12 < T0 ~ "Decrease", 
                                 TRUE ~ NA), 
           Marker = paste0(prefix, "_", Marker),
           Origin = prefix) %>% 
    select(Marker, Direction, Origin)
})

Directions <- bind_rows(Directions_List)

```

```{r Perform the tests}

Paired_Tests <- function(df){ df %>% 
  pivot_wider(names_from = "Time_point", values_from = "Value", names_prefix = "Value_") %>% 
  group_by(Marker) %>% 
  summarise(Pairs = n_distinct(ID),
            Test = list(wilcox.test(Value_T12, 
                                    Value_T0, 
                                    paired = TRUE, 
                                    exact = FALSE)), 
                        .groups = "drop") %>% 
  mutate(Results = map(Test, broom::tidy)) %>% 
  unnest(Results) %>% 
  select(Marker, Pairs, statistic, p.value, method)
}

Test_Results <- imap(Long_Dataframes, ~Paired_Tests(.x) %>% 
                       mutate(Marker = paste0(.y, "_", Marker)))

Test_Results <- bind_rows(Test_Results, .id = "Origin")

```

```{r}

Test_Results %>% 
  mutate(P_adjusted = p.adjust(p.value, method = "BH")) %>% 
  filter(p.value < 0.05)

```


```{r Perform the paired t tests}

Paired_t_Tests <- function(df){ df %>% 
  pivot_wider(names_from = "Time_point", values_from = "Value", names_prefix = "Value_") %>% 
  group_by(Marker) %>% 
  summarise(Pairs = n_distinct(ID),
            Test = list(t.test(Value_T12,
                               Value_T0, 
                               paired = TRUE)), 
                        .groups = "drop") %>% 
  mutate(Results = map(Test, broom::tidy)) %>% 
  unnest(Results) %>% 
  select(Marker, Pairs, statistic, p.value, method)
}

t_Test_Results <- imap(Long_Dataframes, ~Paired_t_Tests(.x) %>% 
                       mutate(Marker = paste0(.y, "_", Marker)))

t_Test_Results <- bind_rows(Test_Results, .id = "Origin")

t_Test_Results %>% 
  filter(p.value < 0.05)

```

```{r Combine the direction with the tests}

Results_Total <- Test_Results %>% inner_join(Directions, by = c("Origin", "Marker"))

Dataframes_Final <- imap(
  Long_Dataframes, ~ .x %>% 
      mutate(Marker = paste0(.y, "_", Marker), 
             Origin = .y)) %>% 
  bind_rows(., .id = "Origin") %>% 
  select(ID, Origin, everything())

Results_Sign <- Results_Total %>% 
  filter(p.value < 0.05)

Dataframes_Final_Sign <- Dataframes_Final %>% 
  filter(Marker %in% Results_Sign$Marker)

```

```{r Correlation analysis}

Dataframes_Final_Sign_Wide <- Dataframes_Final_Sign %>% 
  mutate(ID = paste0(ID, " ", Time_point)) %>% 
  select(-c(Time_point, Origin)) %>% 
  pivot_wider(id_cols = ID, names_from = "Marker", values_from = "Value") %>% 
  column_to_rownames(var = "ID") %>% 
  mutate(across(where(is.numeric), ~ round(., 5)))

# Correlations <- cor(Dataframes_Final_Sign_Wide, 
#                     Comparator_Values, 
#                     method = "spearman", 
#                     use = "pairwise.complete.obs") %>% 
#   as.data.frame() %>%
#   rownames_to_column(var = "Marker") %>% 
#   pivot_longer(cols = -Marker, 
#                names_to = "Variable", 
#                values_to = "Correlation") %>% 
#   mutate(Origin = sub("_.*$", "", Marker)) %>% 
#   inner_join(Directions, by = c("Marker", "Origin"))


DFs_Combined <- cbind(Dataframes_Final_Sign_Wide, Comparator_Values)

Correlations <- expand_grid(Marker = colnames(Dataframes_Final_Sign_Wide), 
              Variable = colnames(Comparator_Values)) %>% 
  mutate(test = map2(Marker, Variable, ~ cor.test(DFs_Combined[[.x]], DFs_Combined[[.y]], 
                                                  method = "spearman", exact  = FALSE)),
         rho     = map_dbl(test, "estimate"), 
         p.value = map_dbl(test, "p.value", )) %>%
  mutate(P_adjust = p.adjust(p.value, method = "BH")) %>% 
  select(-test) %>% 
  mutate(Origin = sub("_.*$", "", Marker)) %>% 
  inner_join(Directions, by = c("Marker", "Origin")) %>% 
  rename(Correlation = "rho") %>% 
  mutate(Significance = case_when(p.value < 0.05 ~ "*"))

Variables_Rename <- c(AI = "AI",
                      CI = "CI",
                      S_creatinine = "Creatinine",
                      eGFR = "eGFR",
                      UPCR = "UPCR",
                      albumin = "Albumin",
                      SLEDAI = "SLEDAI",
                      Extra_Renal = "Extra-renal SLEDAI",
                      Renal_Impairment = "Renal_Impairment", 
                      Clinical_Response = "Clinical_Response")

Correlations <- Correlations %>% 
  mutate(Variable = recode(Variable, !!!Variables_Rename),
         Variable = factor(Variable, levels = Variables_Rename))


```

```{r Correlations visualisation}

Main_plot <- ggplot(Correlations, aes(x = Variable, y = Marker, fill = Correlation)) +
  geom_tile(color = "white", width = 1, height = 1) +
  scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                       midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                       guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                              title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
  facet_grid(Origin ~., scales = "free_y", space = "free_y", switch = "x") +
  # geom_text(aes(label = round(Correlation, 2)), size = 3) +
  geom_text(aes(label = Significance, vjust = 0.5, hjust = 0.5, fontface = "bold")) +
  scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), expand = c(0,0)) +
  scale_x_discrete(labels = function(x) {
    x <- gsub("_", " ", x)
    x <- gsub("Extra-renal SLEDAI", "Extra-renal<br>SLEDAI", x)
    x <- gsub("Renal Impairment", "Renal<br>Impairment", x)
    x <- gsub("Clinical Response", "Clinical<br>Response", x)
    x }, expand = c(0,0)) +
  labs(title = "Heatmap of Glycan Correlations", x = NULL, y = NULL) +
  theme_minimal(base_size = 12) +
  theme(strip.placement = "outside",
        strip.text.y.right = element_blank(),
        axis.text.x = element_markdown(angle = 0, hjust = 0.5, face = "bold", colour = "black"), 
        axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
        panel.grid  = element_blank(), 
        panel.spacing = unit(1, "lines"), 
        plot.title = element_text(face = "bold"))

Dir_plot <- Correlations %>%
  distinct(Origin, Marker, Direction) %>% 
  ggplot(., aes(x = 1, y = Marker, fill = Direction)) +
  geom_tile(color = "white", width = 1, height = 1) +
  facet_grid(Origin ~ ., scales = "free_y", space  = "free_y", switch = "x") +
  scale_fill_manual(values = c("Increase" = "mediumspringgreen",
                               "Decrease" = "purple", 
                               "No change"  = "grey80"), 
                    guide = guide_legend(order = 2, title.position = "top", 
                                         title = "T12 vs T0", title.theme = element_markdown(face = "bold", size = 12), 
                                         title.hjust = 0, label.position = "right", 
                                         keywidth = unit(0.5, "cm"), keyheight = unit(0.4, "cm"))) +
  scale_y_discrete(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  theme_void() +
  theme(strip.text.y.right = element_text(angle = 0, hjust = 0, vjust = 0.5, face  = "bold", margin = margin(l = 10)),
        plot.margin = margin(0, 0, 0, 0), 
        panel.spacing.x = unit(0, "lines"),
        panel.spacing = unit(1, "lines"))

Combined_Plot <- Main_plot + Dir_plot +
  plot_layout(widths = c(0.95, 0.05), 
              # widths = c(length(unique(Correlations$Variable)), 1), 
              guides = "collect") +   
  plot_annotation(theme = theme(plot.margin = margin(0, 0, 0, 0))) &
  theme(legend.box = "vertical", 
        legend.position = "right",
        legend.title.position = "bottom")

# ggsave(Combined_Plot,
#        filename = "~/SLE/Glycans/Plots/Glycans_Correlations_final.jpeg",
#        width = 10, height = 16, dpi = 300)

```


```{r Delta calculation and correlation}

Dataframes_Delta <- Dataframes_Final_Sign %>% 
  group_by(ID, Marker) %>% 
  mutate(Delta = order_by(Time_point, Value - lag(Value))) %>%
  mutate(Delta = ifelse(is.na(Delta), 0, Delta)) %>% 
  filter(Time_point == "T12") %>% 
  select(-c(Time_point, Value, Origin)) %>% 
  pivot_wider(id_cols = ID, 
              names_from = Marker, 
              values_from = Delta) %>% 
  column_to_rownames(var = "ID")

Comparator_Values_Delta <- Increased_data %>%
  rename(ID = `Patient number`, Time_point = `Time point`) %>%
  select(ID, Time_point, any_of(Comparators)) %>%
  rename(Renal_Impairment = `Renal Impairment`,
         Extra_Renal = `extra-renal`,
         S_creatinine = `S-creatinine`, 
         Clinical_Response = Clinical, 
         Albumin = albumin, 
         SLEDAI = total) %>%
  mutate(AI = as.numeric(AI),
         CI = as.numeric(CI)) %>% 
  pivot_longer(cols = -c(ID, Time_point), 
               names_to = "Marker", 
               values_to = "Value") %>% 
  group_by(ID, Marker) %>% 
  mutate(Delta = order_by(Time_point, Value - lag(Value))) %>%
  mutate(Delta = ifelse(is.na(Delta), 0, Delta)) %>% 
  filter(Time_point == "T12") %>% 
  select(ID, Marker, Delta) %>% 
  pivot_wider(id_cols = "ID", 
              names_from = "Marker", 
              values_from = "Delta") %>% 
  column_to_rownames(var = "ID")

DFs_Delta_Combined <- cbind(Dataframes_Delta, Comparator_Values_Delta) 

Correlations_Delta <- expand_grid(Marker = colnames(Dataframes_Delta), 
              Variable = colnames(Comparator_Values_Delta)) %>% 
  mutate(test = map2(Marker, 
                     Variable, ~ cor.test(DFs_Delta_Combined[[.x]], 
                                          DFs_Delta_Combined[[.y]], 
                                          method = "spearman", 
                                          exact  = FALSE)),
         rho = map_dbl(test, "estimate"), 
         p.value = map_dbl(test, "p.value", )) %>%
  mutate(P_adjust = p.adjust(p.value, method = "BH")) %>% 
  select(-test) %>% 
  mutate(Origin = sub("_.*$", "", Marker)) %>% 
  inner_join(Directions, by = c("Marker", "Origin")) %>% 
  rename(Correlation = "rho") %>% 
  mutate(Significance = case_when(p.value < 0.05 ~ "*"))
         
Correlations_Delta <- Correlations_Delta %>% 
  mutate(Variable = recode(Variable, !!!Variables_Rename),
         Variable = factor(Variable, levels = Variables_Rename))


```

```{r Correlations visualisation for the Deltas}

Main_plot_Delta <- ggplot(Correlations_Delta, aes(x = Variable, y = Marker, fill = Correlation)) +
  geom_tile(color = "white", width = 1, height = 1) +
  scale_fill_gradient2(low = "dodgerblue", 
                       mid = "white", 
                       high = "firebrick", 
                       midpoint = 0, 
                       breaks = seq(-1, 1, by = 0.5), 
                       guide = guide_colorbar(order = 1, 
                                              title.position = "top", 
                                              title.hjust = 0, 
                                              title = "Spearman<br>Correlation", 
                                              title.theme = element_markdown(face = "bold"))) +
  facet_grid(Origin ~., 
             scales = "free_y", 
             space = "free_y", 
             switch = "x") +
  # geom_text(aes(label = round(Correlation, 2)), size = 3) +
  geom_text(aes(label = Significance, vjust = 0.8, hjust = 0.5, fontface = "bold")) +
  scale_y_discrete(labels = function(x) gsub("^[^_]*_", "", x), 
                   expand = c(0,0)) +
  scale_x_discrete(labels = function(x) {
    x <- gsub("_", " ", x)
    x <- gsub("Extra-renal SLEDAI", "Extra-renal<br>SLEDAI", x)
    x <- gsub("Renal Impairment", "Renal<br>Impairment", x)
    x <- gsub("Clinical Response", "Clinical<br>Response", x)
    x <- gsub("albumin", "Albumin", x)
    x }, expand = c(0,0)) +
  labs(title = "Heatmap of Glycan Deltas Correlations", 
       x = NULL, 
       y = NULL) +
  theme_minimal(base_size = 12) +
  theme(strip.placement = "outside",
        strip.text.y.right = element_blank(),
        axis.text.x = element_markdown(angle = 0, 
                                       hjust = 0.5, 
                                       face = "bold", 
                                       colour = "black"), 
        axis.text.y = element_text(size = 8, 
                                   face = "bold", 
                                   colour = "black"),
        panel.grid  = element_blank(), 
        panel.spacing = unit(1, "lines"), 
        plot.title = element_text(face = "bold"))

Dir_plot_Delta <- Correlations_Delta %>%
  distinct(Origin, Marker, Direction) %>% 
  ggplot(., aes(x = 1, y = Marker, fill = Direction)) +
  geom_tile(color = "white", 
            width = 1, 
            height = 1) +
  facet_grid(Origin ~ ., 
             scales = "free_y", 
             space  = "free_y", 
             switch = "x") +
  scale_fill_manual(values = c("Increase" = "mediumspringgreen",
                               "Decrease" = "purple", 
                               "No change"  = "grey80"), 
                    guide = guide_legend(order = 2, title.position = "top", 
                                         title = "T12 vs T0", 
                                         title.theme = element_markdown(face = "bold", 
                                                                        size = 12), 
                                         title.hjust = 0, 
                                         label.position = "right", 
                                         keywidth = unit(0.5, "cm"), 
                                         keyheight = unit(0.4, "cm"))) +
  scale_y_discrete(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  theme_void() +
  theme(strip.text.y.right = element_text(angle = 0, 
                                          hjust = 0, 
                                          vjust = 0.5, 
                                          face = "bold", 
                                          margin = margin(l = 10)),
        plot.margin = margin(0, 0, 0, 0), 
        panel.spacing.x = unit(0, "lines"),
        panel.spacing = unit(1, "lines"))

Combined_Delta <- Main_plot_Delta + Dir_plot_Delta +
  plot_layout(widths = c(0.95, 0.05), 
              # widths = c(length(unique(Correlations$Variable)), 1), 
              guides = "collect") +   
  plot_annotation(theme = theme(plot.margin = margin(0, 0, 0, 0))) &
  theme(legend.box = "vertical", 
        legend.position = "right",
        legend.title.position = "bottom")

# ggsave(plot = Combined_Delta,
#        filename = "~/SLE/Glycans/Plots/Glycans_Correlations_Delta_final.jpeg",
#        width = 12, height = 24, dpi = 300)

```

```{r}

Dataframes_Delta_2 <- Dataframes_Final_Sign %>% 
  group_by(ID, Marker) %>% 
  mutate(Delta = order_by(Time_point, Value - lag(Value))) %>%
  mutate(Delta = ifelse(is.na(Delta), 0, Delta)) %>% 
  filter(Time_point == "T12") %>% 
  select(-c(Time_point, Value, Origin)) %>% 
  pivot_wider(id_cols = ID, 
              names_from = Marker, 
              values_from = Delta) %>% 
  column_to_rownames(var = "ID")

Comparator_Values_Delta_2 <- Increased_data %>%
  rename(ID = `Patient number`, Time_point = `Time point`) %>%
  select(ID, Time_point, any_of(Comparators)) %>%
  rename(Renal_Impairment = `Renal Impairment`,
         Extra_renal_SLEDAI = `extra-renal`,
         Creatinine = `S-creatinine`, 
         Clinical_Response = Clinical, 
         Albumin = albumin, 
         SLEDAI = total) %>%
  mutate(AI = as.numeric(AI),
         CI = as.numeric(CI)) 

Outcomes <- Comparator_Values_Delta_2 %>% 
  filter(Time_point == "T12") %>% 
  select(Renal_Impairment, Clinical_Response)

Comparator_Values_Delta_2_clean <- Comparator_Values_Delta_2 %>% 
  select(-c(Renal_Impairment, Clinical_Response)) %>% 
  pivot_longer(cols = -c(ID, Time_point), 
               names_to = "Marker", 
               values_to = "Value") %>% 
  group_by(ID, Marker) %>% 
  mutate(Delta = order_by(Time_point, Value - lag(Value))) %>%
  mutate(Delta = ifelse(is.na(Delta), 0, Delta)) %>% 
  filter(Time_point == "T12") %>% 
  select(ID, Marker, Delta) %>% 
  pivot_wider(id_cols = "ID", 
              names_from = "Marker", 
              values_from = "Delta") %>% 
  column_to_rownames(var = "ID")

DFs_Delta_Combined_2 <- cbind(Dataframes_Delta_2, Comparator_Values_Delta_2_clean, Outcomes) 

```



```{r Data prep and model build}

## Prepare the dataframes again ##
DFs_for_GLMs <- DFs_Delta_Combined_2 %>% 
  rownames_to_column(var = "ID") %>% 
  mutate(ID = str_extract(ID, "\\d+") %>% 
           as.integer(ID)) %>% 
  drop_na()

sapply(DFs_for_GLMs, function(x) sum(is.na(x)))

## Get the names of the Markers for the comparisons ##
Candidates <- setdiff(names(DFs_for_GLMs), c("ID", "Timepoint", "Renal_Impairment", "Clinical_Response"))

Univ_Results <- map_df(Candidates, function(var){
  
  ## Build the outcome ~ variable formulas and fit the models ##
  model_RI <- glm(reformulate(var, "Renal_Impairment"),
              data = DFs_for_GLMs, family = binomial)
  model_CL <- glm(reformulate(var, "Clinical_Response"),
              data = DFs_for_GLMs, family = binomial)
  
  ## Extract the predictor row, add OR and CIs as well as an outcome column ##
  Res_RI <- broom::tidy(model_RI)[2, ] %>%
    transmute(Marker = var,
              Outcome = "Renal_Impairment",
              estimate, std.error, statistic, p.value,
              OR = exp(estimate),
              lower = exp(estimate - 1.96 * std.error),
              upper = exp(estimate + 1.96 * std.error))
  
  Res_CL <- broom::tidy(model_CL)[2, ] %>%
    transmute(Marker = var,
              Outcome = "Clinical_Response",
              estimate, std.error, statistic, p.value,
              OR = exp(estimate),
              lower = exp(estimate - 1.96 * std.error),
              upper = exp(estimate + 1.96 * std.error))
  
  ## Merge the results ##
  bind_rows(Res_RI, Res_CL)
  
})

Univ_Results

```

```{r Sanity check}

table(DFs_for_GLMs$Renal_Impairment)

nzv <- nearZeroVar(DFs_for_GLMs %>% select(-ID, -Renal_Impairment),
                   saveMetrics=TRUE)

nzv[nzv$zeroVar | nzv$nzv, ]

```

```{r Multivariate models}

Responses <- c("Renal_Impairment", "Clinical_Response")

Annotations <- Correlations %>% 
  select(Marker, Significance)

## Choose the top correlated markers from each category ## 
Top_Markers <- Correlations %>%
  filter(Variable == "Renal_Impairment" | Variable == "Clinical_Response") %>% 
  rename(Response = "Variable") %>% 
  group_by(Origin, Response) %>% 
  # arrange(desc(abs(Correlation))) %>% 
  # slice_head(n = 5) %>% 
  summarise(Markers = list(Marker), .groups = "drop") %>%
  group_by(Origin) %>% 
  mutate(Markers = rep(list(unlist(Markers)), 
                       n())) %>% 
  ungroup() %>% 
  mutate(Key = paste(Origin, Response, sep = "_")) %>%
  select(Key, Markers) %>%
  deframe()

## Create the multi models ##
Multi_Models <- imap(Top_Markers, ~{
  # .y corresponds to the subcategory name: "AGP_Renal_Impairment"
  # .x corresponds to the vector of markers: c("AGP_…","AGP_…",…)
  
  ## Get the type of response ##
  response <- sub("^[^_]+_(.*)$", "\\1", .y)
  
  ## Build the formulas ##
  f <- as.formula(paste0(response, " ~ ", paste(.x, collapse = " + ")))
  
  ## Fit and save the models ##
  glm(formula = f, data = DFs_for_GLMs %>% select(-ID), family = binomial)
  
})

## Make it more redable and convert to a dataframe ##
Multi_Results <- Multi_Models %>%
  
  ## Conver to tribble with the models collapsed under the name of each model ##
  enframe(name = "Model", value = "Fit") %>%
  
  ## For each model, tidy, get ORs and CIs ##
  mutate(Tidy = map2(Model, Fit, ~ broom::tidy(.y) %>%
                      filter(term != "(Intercept)") %>%
                      transmute(Marker = term, estimate, std.error,
                      statistic, p.value, OR = exp(estimate),
                      lower = exp(estimate - 1.96 * std.error),
                      upper = exp(estimate + 1.96 * std.error)))) %>%
  
  ## Remove the models ##
  select(-Fit) %>%
  
  ## Unnest the dataframes with the results for each model ##
  unnest(Tidy)

# now Multi_Results has one row per Model×Marker with OR & 95% CI
Multi_Results
# write_xlsx(x = Multi_Results, path = "~/SLE/Glycans/GLM_Results.xlsx")

```

```{r Summ with jtools}

## Using the summ command from jtools it prints out a nice looking table ##
summ(Multi_Models$AGP_Clinical, confint = TRUE)

```

```{r Effect plots}

for(i in seq_len(nrow(Multi_Results))) {
  
  Current_Model_Name <- Multi_Results$Model[i] 
  Current_Marker <- Multi_Results$Marker[i]
  Current_Model <- Multi_Models[[Current_Model_Name]]
  
  ## Clean the marker name ##
  x_lab <- gsub("_", " ", Current_Marker)
  
  ## Clean the model name ##
  y_lab <- names(model.frame(Current_Model))[1] %>% 
    gsub("_", " ", .)
  
  ## Plot the effect ##
  Current_Plot <- effect_plot(Current_Model, 
                              pred = !!sym(Current_Marker),
                              interval = TRUE, 
                              plot.points = TRUE, 
                              jitter = 0) +
    labs(x = x_lab, 
         y = y_lab, 
         title = paste0("GLM: ", y_lab, " - ", x_lab))
  
  Plot_Name <- paste0(Current_Model_Name, 
                      "_", 
                      Current_Marker, 
                      ".jpeg")
  
  # ggsave(filename = paste0("~/SLE/Glycans/Plots/Effect_Plots_Deltas/", Plot_Name),
  #        plot = Current_Plot,
  #        width = 6,
  #        height = 4,
  #        dpi = 300,
  #        device = "jpeg")
  
}

```

```{r Jtools visualisation - Normal GLM}

# Multi_Results <- Multi_Results %>% 
#   mutate(Origin = gsub("_.*", "", Model))
# 
# for (i in unique(Multi_Results$Origin)) {
#   
#   Current_Model_1 <- paste0(i, "_Clinical_Response")
#   Current_Model_2 <- paste0(i, "_Renal_Impairment")
#   
#   # grab the actual model objects
#   Model_1 <- Multi_Models[[Current_Model_1]]
#   Model_2 <- Multi_Models[[Current_Model_2]]
#   
#   Current_Plot_ORs <- plot_summs(Model_1, 
#                                  Model_2,
#                                  exp = TRUE, 
#                                  model.names = c("Clinical Response", 
#                                                  "Renal Impairment")) +
#     labs(x = "Odds Ratio",
#          y = "Predictor",
#          title = paste0("GLM, Odds Ratio: ", i)) +
#     scale_y_discrete(labels = function(txt) gsub("_", " ", txt)) +
#     scale_x_continuous(labels = label_scientific(digits = 2)) +
#     theme(axis.title.x = element_text(face = "bold"),
#           panel.grid.major.y = element_blank(), 
#           axis.text.y = element_text(face = "bold"), 
#           plot.title = element_text(hjust = 0))
#   
#   OR_Plot_Name <- paste0("GLM_", i, "_ORs.jpeg")
#   
#   names(coef(Model_1))
#   Current_Plot_Estimates <- plot_summs(Model_1, 
#                                        Model_2,
#                                        model.names = c("Clinical Response",
#                                                        "Renal Impairment"), 
#                                        coefs = good.coefs,
#                                        plot.distributions = FALSE) +
#     labs(x = "Estimate (Log Odds)",
#          y = "Predictor",
#          title = paste0("GLM, Estimates: ", i)) +
#     scale_y_discrete(labels = function(txt) gsub("_", " ", txt)) +
#     theme(axis.title.x = element_text(face = "bold"),
#           panel.grid.major.y = element_blank(), 
#           axis.text.y = element_text(face = "bold"), 
#           plot.title = element_text(hjust = 0))
#   
#   Estimates_Plot_Name <- paste0("GLM_", i, "_Estimates.jpeg")
#   
  # ggsave(filename = paste0("~/SLE/Glycans/Plots/GLM_Deltas/ORs/", OR_Plot_Name),
  #        plot = Current_Plot_ORs,
  #        width = 10,
  #        height = 6,
  #        dpi = 300,
  #        device = "jpeg")
  # 
  # ggsave(filename = paste0("~/SLE/Glycans/Plots/GLM_Deltas/Estimates/", Estimates_Plot_Name),
  #        plot = Current_Plot_Estimates,
  #        width = 10,
  #        height = 6,
  #        dpi = 300,
  #        device = "jpeg")
# }

```


```{r Other models}

Non_NA_Markers <- Multi_Results %>% 
  drop_na() %>% 
  pull(Marker)

## Choose the top correlated markers from each category ## 
Top_Markers_Clean <- Correlations %>%
  filter(Variable == "Renal_Impairment" | Variable == "Clinical_Response") %>% 
  rename(Response = "Variable") %>% 
  filter(Marker %in% Non_NA_Markers) %>% 
  group_by(Origin, Response) %>% 
  # arrange(desc(abs(Correlation))) %>% 
  # slice_head(n = 5) %>% 
  summarise(Markers = list(Marker), .groups = "drop") %>%
  group_by(Origin) %>% 
  mutate(Markers = rep(list(unlist(Markers)), 
                       n())) %>% 
  ungroup() %>% 
  mutate(Key = paste(Origin, Response, sep = "_")) %>%
  select(Key, Markers) %>%
  deframe()

# Multi_Models_Firth <- imap(Top_Markers_Clean, ~{
#   ## .y is like "AGP_Clinical", .x is the vector of top markers
#   
#   ## extract response and build formula
#   response <- sub("^[^_]+_(.*)$", "\\1", .y)
#   f        <- as.formula(paste0(response, " ~ ", paste(.x, collapse = " + ")))
#   data     <- DFs_for_GLMs %>% select(-ID)
#   
#   ## Firth’s bias‐reduced model ##
#   firth_mod <- logistf(formula = f, 
#                        data = data,
#                        control = logistf.control(maxit = 500, maxstep =  50),    
#                        plcontrol = logistf.control(maxit = 500))
# })

## Safe version ##
Multi_Models_Firth <- imap(Top_Markers_Clean, ~{
  ## .y is like "AGP_Clinical", .x is the vector of top markers
  safe_firth <- possibly(logistf, otherwise = NULL)
  ## extract response and build formula
  response <- sub("^[^_]+_(.*)$", "\\1", .y)
  f        <- as.formula(paste0(response, " ~ ", paste(.x, collapse = " + ")))
  data     <- DFs_for_GLMs %>% select(-ID)
  
  ## Firth’s bias‐reduced model ##
  firth_mod <- safe_firth(formula = f, 
                       data = data,
                       control = logistf.control(maxit = 500, maxstep =  50),    
                       plcontrol = logistf.control(maxit = 500))
  if (is.null(firth_mod)) warning("Firth failed for ", .y)
  firth_mod
})

# Multi_Models_Penalised <- imap(Top_Markers, ~{
#   ## .y is like "AGP_Clinical", .x is the vector of top markers
#   
#   ## extract response and build formula
#   response <- sub("^[^_]+_(.*)$", "\\1", .y)
#   f        <- as.formula(paste0(response, " ~ ", paste(.x, collapse = " + ")))
#   data     <- DFs_for_GLMs %>% select(-ID)
# 
#   X   <- model.matrix(f, data = data)[, -1, drop = FALSE]
#   y   <- data[[response]]
#   cv  <- cv.glmnet(X, y, family = "binomial", alpha = 0)
#   
#   pen_mod <- glmnet(x = X, 
#                     y = y, 
#                     family = "binomial", 
#                     alpha = 0, 
#                     lambda = cv$lambda.min)
# })

```



```{r}

Multi_Results_Firth <- purrr::map_df(Multi_Models_Firth,
                ~ broom.helpers::tidy_with_broom_or_parameters(.x,
                                                               conf.int = TRUE,
                                                               conf.level = 0.95), 
                .id = "Model") %>%
  dplyr::filter(term != "(Intercept)")


# MultiResults_Penalised <- imap_dfr(Multi_Models_Penalised, ~ {
#   cm <- as.matrix(coef(.x))
#     tibble(Model = .y,
#            Method = "penalized",
#            Marker = rownames(cm)[-1],
#            estimate = cm[-1, 1] %>% as.numeric(),
#            OR = exp(cm[-1, 1]))
#   })

Annotate_these <- Correlations %>% 
  filter(Variable == "Renal_Impairment" | Variable == "Clinical_Response") %>% 
  filter(Significance == "*") %>% 
  pull(Marker)

Multi_Results_Firth_Clean <- Multi_Results_Firth %>% 
  select(Model, 
         Marker = term, 
         estimate, 
         lower = conf.low, 
         higher = conf.high, 
         p.value) %>% 
  mutate(Origin = gsub("_.*", "", Model), 
         Model = sub("^[^_]+_", "", Model), 
         Marker_Clean = str_replace_all(Marker, "^[^_]+_", ""), 
         OR = exp(estimate), 
         lowerOR = exp(lower), 
         upperOR = exp(higher), 
         # do_annotate = Marker %in% Annotate_these,
         sig = p.value < 0.05,
         Marker_label = if_else(sig,
                                paste0("<span style='color:red; font-weight:bold; font-size:12pt; vertical-align:-10px;'>*</span>\u2002",
                                       Marker_Clean), 
                                Marker_Clean)) 

```

```{r Function for jtools to work with logistf}

tidy.logistf <- function(x, conf.int = TRUE, conf.level = 0.95, ...) {
  
  coefs <- x$coeff
  ses <- sqrt(diag(x$var))
  z <- coefs / ses
  p <- 2 * pnorm(-abs(z))
  out <- tibble(term = names(coefs),
                estimate = coefs,
                std.error = ses,
                statistic = z,p.value = p)
  
  if (conf.int) {
    crit <- qnorm((1 + conf.level) / 2)
    out <- out %>%
      mutate(conf.low  = estimate - crit * std.error,
             conf.high = estimate + crit * std.error)
  }
}

```

```{r Jtools Visualisation - Firths Penalised GLMs}

for (i in unique(Multi_Results_Firth_Clean$Origin)) {
  
  Current_Model_1 <- paste0(i, "_Clinical_Response")
  Current_Model_2 <- paste0(i, "_Renal_Impairment")
  
  # grab the actual model objects
  Model_1 <- Multi_Models_Firth[[Current_Model_1]]
  Model_2 <- Multi_Models_Firth[[Current_Model_2]]
  
  Current_Plot_ORs <- plot_summs(Model_1, 
                                 Model_2,
                                 exp = TRUE, 
                                 model.names = c("Short term outcome:\nClinical Response", 
                                                 "Long term outcome:\nRenal Impairment")) +
    labs(x = "Odds Ratio (Log10 scale)",
         y = "Predictor",
         title = paste0("Firth's Penalized GLM", i)) +
    scale_y_discrete(labels = function(txt) gsub("_", " ", txt)) +
    scale_x_continuous(labels = label_scientific(digits = 2)) +
    scale_x_log10() +
    theme(axis.title.x = element_text(face = "bold"),
          panel.grid.major.y = element_blank(), 
          axis.text.y = element_text(face = "bold"), 
          plot.title.position = "plot",  
          plot.title = element_text(hjust = 0), 
          legend.title = element_blank(), 
          legend.text = element_text(face = "bold", size = 10))
  
  OR_Plot_Name <- paste0("GLM_", i, "_ORs.jpeg")
  
  Current_Plot_Estimates <- plot_summs(Model_1, 
                                       Model_2,
                                       model.names = c("Short term outcome:\nClinical Response", 
                                                 "Long term outcome:\nRenal Impairment"),
                                       # coefs = good.coefs,
                                       plot.distributions = TRUE, 
                                       rescale.distributions = TRUE) +
    labs(x = "Estimate (Log Odds)",
         y = "Predictor",
         title = paste0("Firth's Penalized GLM", i)) +
    scale_y_discrete(labels = function(txt) gsub("_", " ", txt)) +
    theme(axis.title.x = element_text(face = "bold"),
          panel.grid.major.y = element_blank(), 
          axis.text.y = element_text(face = "bold"), 
          plot.title.position = "plot",  
          plot.title = element_text(hjust = 0), 
          legend.title = element_blank(), 
          legend.text = element_text(face = "bold", size = 10))
  
  Estimates_Plot_Name <- paste0("GLM_", i, "_Estimates.jpeg")
  
  # ggsave(filename = paste0("~/SLE/Glycans/Plots/Firth_GLM_Delta/ORs/", OR_Plot_Name),
  #        plot = Current_Plot_ORs,
  #        width = 10,
  #        height = 6,
  #        dpi = 300,
  #        device = "jpeg")
  # 
  # ggsave(filename = paste0("~/SLE/Glycans/Plots/Firth_GLM_Delta/Estimates/", Estimates_Plot_Name),
  #        plot = Current_Plot_Estimates,
  #        width = 10,
  #        height = 6,
  #        dpi = 300,
  #        device = "jpeg")
}

```

```{r Visualisation manual - Firth - Estimates}

Estimate_Plots <- Multi_Results_Firth_Clean %>%
  mutate(Origin_2 = factor(Origin, levels = c("Fab", "Serum", "AGP", "Fc", "IgG", "C3"))) %>% 
  group_split(Origin_2) %>%
  set_names(map_chr(., ~ unique(.x$Origin))) %>%
  imap(function(df, name) {
    p <- ggplot(df, aes(x = estimate, y = Marker_label, color = Model)) +
      geom_vline(xintercept = 0, linetype = "dashed", colour = "black") +
      geom_point(position = position_dodge(0.6), size = 3) +
      geom_errorbarh(aes(xmin = lower, xmax = higher),
                     position = position_dodge(0.6),
                     height = 0.2) +
      # scale_color_discrete(name = NULL,
      #                      labels = c(expression(atop(bold("Short term outcome:"), "Clinical Response")),
      #                                 expression(atop(bold("Long term outcome:"), "Renal Impairment"))),
      #                      guide = guide_legend(label.hjust = 0, ncol = 1, nrow = 2)) +
      # scale_color_discrete(name = NULL,
      #                      labels = c("**Short term outcome:**<br>Clinical Response",
      #                                 "<br>**Long term outcome:**<br>Renal Impairment")) +
      scale_color_discrete(name = NULL,
                           labels = c("**Short term outcome:**<br>Clinical Response",
                                      "**Long term outcome:**<br>Renal Impairment")) +      
      labs(title = name) +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0, face = "bold"),
            panel.grid.major.y = element_blank(), 
            axis.title.y = element_blank(),
            axis.text.y = element_markdown(),
            axis.title.x = element_blank(), 
            axis.ticks.x = element_blank(), 
            legend.text = element_markdown(size = 10))
    p
  })

# 2) compute relative heights so panels scale with marker counts
Plot_Heights <- map_int(Estimate_Plots, ~ nrow(Multi_Results_Firth_Clean %>% 
                                   filter(Origin == unique(.x$data$Origin))))

# — 3) Wrap them in one column, collect the legend, and inject a gap —
Estimate_Plots_wrap <- wrap_plots(Estimate_Plots, 
                           ncol = 1, 
                           heights = Plot_Heights, 
                           guides  = "collect") 

# — 4) Create the shared x‐axis label with minimal bottom gap —
Plot_x_axis <- ggplot() +
  labs(x = "Estimate (Log-Odds)") +
  theme_void() +
  theme(axis.title.x = element_text(face = "bold", size = 12),
        plot.margin  = margin(t = 0, r = 0, b = 0, l = 10))

Firth_Final_Estimate_Plot <- wrap_plots(list(Estimate_Plots_wrap, Plot_x_axis),
                         ncol = 1,
                         heights = c(sum(Plot_Heights), 1), 
                         guides  = "collect") +
  plot_annotation(title = "Firth-Penalized logistic regression results",
                  theme = theme(plot.title.position = "plot",
                                plot.title = element_text(size = 16, 
                                                          face = "bold", 
                                                          hjust = 0))) &
  theme(legend.position = "right")

# ggsave(plot = Firth_Final_Estimate_Plot,
#        filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_Estimates_Total.jpeg",
#        height = 18, width = 10, dpi = 300, device = "jpeg")

Firth_Final_Estimate_Plot
```

```{r Visualisation manual - Firth - Odds Ratio}

OR_Plots <- Multi_Results_Firth_Clean %>%
  mutate(Origin_2 = factor(Origin, levels = c("Fab", "Serum", "AGP", "Fc", "IgG", "C3"))) %>% 
  group_split(Origin_2) %>%
  set_names(map_chr(., ~ unique(.x$Origin))) %>%
  imap(function(df, name) {
    p <- ggplot(df, aes(x = OR, y = Marker_label, color = Model)) +
      geom_point(position = position_dodge(0.6), size = 3) +
      geom_errorbarh(aes(xmin = lowerOR, xmax = upperOR),
                     position = position_dodge(0.6),
                     height = 0.2) +
      # scale_color_discrete(name = NULL,
      #                      labels = c("**Short term outcome:**<br>Clinical Response",
      #                                 "<br>**Long term outcome:**<br>Renal Impairment")) +
      scale_color_discrete(name = NULL,
                           labels = c("**Short term outcome:**<br>Clinical Response",
                                      "**Long term outcome:**<br>Renal Impairment")) +
      scale_x_continuous(labels = scales::label_scientific(digits = 2)) +
      labs(title = name) +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0, face = "bold"),
            panel.grid.major.y = element_blank(), 
            axis.title.y = element_blank(),
            axis.text.y = element_markdown(),
            axis.title.x = element_blank(), 
            axis.ticks.x = element_blank(), 
            legend.text = element_markdown(size = 10))
    p
  })

# 2) compute relative heights so panels scale with marker counts
Plot_Heights <- map_int(OR_Plots, ~ nrow(Multi_Results_Firth_Clean %>% 
                                           filter(Origin == unique(.x$data$Origin))))

# — 3) Wrap them in one column, collect the legend, and inject a gap —
OR_Plots_wrap <- wrap_plots(OR_Plots, 
                           ncol = 1, 
                           heights = Plot_Heights, 
                           guides  = "collect") 

OR_Plots_wrap <- OR_Plots_wrap &
  scale_x_continuous(labels = scales::label_scientific(digits = 2)) 

# — 4) Create the shared x‐axis label with minimal bottom gap —
Plot_x_axis <- ggplot() +
  labs(x = "Odds Ratio") +
  theme_void() +
  theme(axis.title.x = element_text(face = "bold", size = 12),
        plot.margin  = margin(t = 0, r = 0, b = 0, l = 10))

Firth_Final_OR_Plot <- wrap_plots(list(OR_Plots_wrap, Plot_x_axis),
                         ncol = 1,
                         heights = c(sum(Plot_Heights), 1), 
                         guides  = "collect") +
  plot_annotation(title = "Firth-Penalized logistic regression results",
                  theme = theme(plot.title.position = "plot",
                                plot.title = element_text(size = 16, 
                                                          face = "bold", 
                                                          hjust = 0))) &
  theme(legend.position = "right")

# ggsave(plot = Firth_Final_OR_Plot,
#        filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_ORs_Total.jpeg",
#        height = 18, width = 10, dpi = 300, device = "jpeg")


OR_Plots_wrap_log10 <- OR_Plots_wrap & 
  scale_x_log10(labels = scales::label_scientific(digits = 2))

Plot_x_axis_log10 <- ggplot() +
  labs(x = "Odds Ratio (Log10 scaled)") +
  theme_void() +
  theme(axis.title.x = element_text(face = "bold", size = 12),
        plot.margin  = margin(t = 0, r = 0, b = 0, l = 10))

Firth_Final_log10 <- wrap_plots(list(OR_Plots_wrap_log10, Plot_x_axis_log10),
                         ncol = 1,
                         heights = c(sum(Plot_Heights), 1), 
                         guides  = "collect") &
  plot_annotation(title = "Firth-Penalized logistic regression results",
                  theme = theme(plot.title.position = "plot",
                                plot.title = element_text(size = 16, 
                                                          face = "bold", 
                                                          hjust = 0))) &
  theme(legend.position = "right")

# ggsave(plot = Firth_Final_log10,
#        filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_ORs_Total_log10_scale.jpeg",
#        height = 18, width = 10, dpi = 300, device = "jpeg")

Firth_Final_OR_Plot
Firth_Final_log10
```



```{r Do the same manually for Multi_Results}

Annotate_these <- Correlations %>% 
  filter(Variable == "Renal_Impairment" | Variable == "Clinical_Response") %>% 
  filter(Significance == "*") %>% 
  pull(Marker)

Multi_Results_Clean <- Multi_Results %>% 
  drop_na() %>% 
  select(
    Model, 
    Marker,       # this is still the full name, e.g. "AGP_IIIORM1N4H5S2"
    estimate, 
    std.error,
    p.value,
    OR,      
    lower,    
    upper     
  ) %>% 
  mutate(
    # compute log‐odds CIs
    lower_est = estimate - 1.96 * std.error,
    higher_est = estimate + 1.96 * std.error,
    
    # remember origin and strip off prefix for display
    Origin      = sub("_.*",       "", Model),
    Model       = sub("^[^_]+_",   "", Model),
    Marker_Clean = sub("^[^_]+_",  "", Marker),
    
    # rename your OR‐scale CIs
    lowerOR = lower,
    upperOR = upper,
    
    # flag exactly those in your Annotate_these list
    # do_annotate = Marker %in% Annotate_these,
    sig = p.value < 0.05,
    Marker_label = if_else(sig,
                           paste0("<span style='color:red; font-weight:bold; font-size:12pt; vertical-align:-10px;'>*</span>\u2002",
                                  Marker_Clean), 
                           Marker_Clean)) %>% 
  select(Origin, Model, Marker = Marker_Clean, Marker_label, sig,
         estimate, lower_est, higher_est, lowerOR, upperOR, OR, p.value)






```

```{r Jtools Visualisation -  Normal GLMs Cleaned}

# for (i in unique(Multi_Results_Clean$Origin)) {
#   
#   Current_Model_1 <- paste0(i, "_Clinical_Response")
#   Current_Model_2 <- paste0(i, "_Renal_Impairment")
#   
#   # grab the actual model objects
#   Model_1 <- Multi_Models[[Current_Model_1]]
#   Model_2 <- Multi_Models[[Current_Model_2]]
#   
#   Current_Plot_ORs <- plot_summs(Model_1, 
#                                  Model_2,
#                                  exp = TRUE, 
#                                  model.names = c("Short term outcome:\nClinical Response", 
#                                                  "Long term outcome:\nRenal Impairment")) +
#     labs(x = "Odds Ratio (Log10 scale)",
#          y = "Predictor",
#          title = paste0("Logistic Regression results:", i)) +
#     scale_y_discrete(labels = function(txt) gsub("_", " ", txt)) +
#     scale_x_continuous(labels = label_scientific(digits = 2)) +
#     scale_x_log10() +
#     theme(axis.title.x = element_text(face = "bold"),
#           panel.grid.major.y = element_blank(), 
#           axis.text.y = element_text(face = "bold"), 
#           plot.title.position = "plot",  
#           plot.title = element_text(hjust = 0), 
#           legend.title = element_blank(), 
#           legend.text = element_text(face = "bold", size = 10))
#   
#   OR_Plot_Name <- paste0("GLM_", i, "_ORs.jpeg")
#   
#   Current_Plot_Estimates <- plot_summs(Model_1, 
#                                        Model_2,
#                                        model.names = c("Short term outcome:\nClinical Response", 
#                                                  "Long term outcome:\nRenal Impairment"),
#                                        # coefs = good.coefs,
#                                        plot.distributions = TRUE, 
#                                        rescale.distributions = TRUE) +
#     labs(x = "Estimate (Log Odds)",
#          y = "Predictor",
#          title = paste0("Firth's Penalized GLM", i)) +
#     scale_y_discrete(labels = function(txt) gsub("_", " ", txt)) +
#     theme(axis.title.x = element_text(face = "bold"),
#           panel.grid.major.y = element_blank(), 
#           axis.text.y = element_text(face = "bold"), 
#           plot.title.position = "plot",  
#           plot.title = element_text(hjust = 0), 
#           legend.title = element_blank(), 
#           legend.text = element_text(face = "bold", size = 10))
#   
#   Estimates_Plot_Name <- paste0("GLM_", i, "_Estimates.jpeg")
#   
#   ggsave(filename = paste0("~/SLE/Glycans/Plots/GLM/ORs/", OR_Plot_Name),
#          plot = Current_Plot_ORs,
#          width = 10,
#          height = 6,
#          dpi = 300,
#          device = "jpeg")
# 
#   ggsave(filename = paste0("~/SLE/Glycans/Plots/GLM/Estimates/", Estimates_Plot_Name),
#          plot = Current_Plot_Estimates,
#          width = 10,
#          height = 6,
#          dpi = 300,
#          device = "jpeg")
# }

```

```{r Visualisation manual - Estimates}

# options(scipen = 999)

Estimate_Plots <- Multi_Results_Clean %>%
  group_split(Origin) %>%
  set_names(map_chr(., ~ unique(.x$Origin))) %>%
  imap(function(df, name) {
    p <- ggplot(df, aes(x = estimate, y = Marker_label, color = Model)) +
      geom_vline(xintercept = 0, linetype = "dashed", colour = "black") +
      geom_point(position = position_dodge(0.6), size = 3) +
      geom_errorbarh(aes(xmin = lower_est, xmax = higher_est),
                     position = position_dodge(0.6),
                     height = 0.2) +
      # scale_color_discrete(name = NULL,
      #                      labels = c(expression(atop(bold("Short term outcome:"), "Clinical Response")),
      #                                 expression(atop(bold("Long term outcome:"), "Renal Impairment"))),
      #                      guide = guide_legend(label.hjust = 0, ncol = 1, nrow = 2)) +
      scale_color_discrete(name = NULL,
                           labels = c("**Short term outcome:**<br>Clinical Response",
                                      "<br>**Long term outcome:**<br>Renal Impairment")) +
      labs(title = name) +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0, face = "bold"),
            panel.grid.major.y = element_blank(), 
            axis.title.y = element_blank(),
            axis.text.y = element_markdown(),
            axis.title.x = element_blank(), 
            axis.ticks.x = element_blank(), 
            legend.text = element_markdown(size = 10))
    p
  })

# 2) compute relative heights so panels scale with marker counts
Plot_Heights <- map_int(Estimate_Plots, ~ nrow(Multi_Results_Firth_Clean %>% 
                                   filter(Origin == unique(.x$data$Origin))))

# — 3) Wrap them in one column, collect the legend, and inject a gap —
Estimate_Plots_wrap <- wrap_plots(Estimate_Plots, 
                           ncol = 1, 
                           heights = Plot_Heights, 
                           guides  = "collect") 

# — 4) Create the shared x‐axis label with minimal bottom gap —
Plot_x_axis <- ggplot() +
  labs(x = "Estimate (Log-Odds)") +
  theme_void() +
  theme(axis.title.x = element_text(face = "bold", size = 12),
        plot.margin  = margin(t = 0, r = 0, b = 0, l = 10))

GLM_Final_Estimate_Plot <- wrap_plots(list(Estimate_Plots_wrap, Plot_x_axis),
                         ncol = 1,
                         heights = c(sum(Plot_Heights), 1), 
                         guides  = "collect") +
  plot_annotation(title = "Logistic regression results",
                  theme = theme(plot.title.position = "plot",
                                plot.title = element_text(size = 16, 
                                                          face = "bold", 
                                                          hjust = 0))) &
  theme(legend.position = "right")

# ggsave(plot = GLM_Final_Estimate_Plot,
#        filename = "~/SLE/Glycans/Plots/GLM/Normal_GLM_Estimates_Total_2.jpeg",
#        height = 18, width = 10, dpi = 300, device = "jpeg")

GLM_Final_Estimate_Plot

```

```{r Visualisation manual - Odds Ratio}

options(scipen = 999)

OR_Plots <- Multi_Results_Clean %>%
  group_split(Origin) %>%
  set_names(map_chr(., ~ unique(.x$Origin))) %>%
  imap(function(df, name) {
    p <- ggplot(df, aes(x = OR, y = Marker_label, color = Model)) +
      geom_point(position = position_dodge(0.6), size = 3) +
      geom_errorbarh(aes(xmin = lowerOR, xmax = upperOR),
                     position = position_dodge(0.6),
                     height = 0.2) +
      scale_color_discrete(name = NULL,
                           labels = c("**Short term outcome:**<br>Clinical Response",
                                      "<br>**Long term outcome:**<br>Renal Impairment")) +
      scale_x_continuous(labels = scales::label_scientific(digits = 2)) +
      labs(title = name) +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0, face = "bold"),
            panel.grid.major.y = element_blank(), 
            axis.title.y = element_blank(),
            axis.text.y = element_markdown(),
            axis.title.x = element_blank(), 
            axis.ticks.x = element_blank(), 
            legend.text = element_markdown(size = 10))
    p
  })

# 2) compute relative heights so panels scale with marker counts
Plot_Heights <- map_int(OR_Plots, ~ nrow(Multi_Results_Clean %>% 
                                           filter(Origin == unique(.x$data$Origin))))

# — 3) Wrap them in one column, collect the legend, and inject a gap —
OR_Plots_wrap <- wrap_plots(OR_Plots, 
                           ncol = 1, 
                           heights = Plot_Heights, 
                           guides  = "collect") 

OR_Plots_wrap <- OR_Plots_wrap &
  scale_x_continuous(labels = scales::label_scientific(digits = 2)) 

# — 4) Create the shared x‐axis label with minimal bottom gap —
Plot_x_axis <- ggplot() +
  labs(x = "Odds Ratio") +
  theme_void() +
  theme(axis.title.x = element_text(face = "bold", size = 12),
        plot.margin  = margin(t = 0, r = 0, b = 0, l = 10))

GLM_Final_OR_Plot <- wrap_plots(list(OR_Plots_wrap, Plot_x_axis),
                         ncol = 1,
                         heights = c(sum(Plot_Heights), 1), 
                         guides  = "collect") +
  plot_annotation(title = "Logistic regression results",
                  theme = theme(plot.title.position = "plot",
                                plot.title = element_text(size = 16, 
                                                          face = "bold", 
                                                          hjust = 0))) &
  theme(legend.position = "right")

# ggsave(plot = GLM_Final_OR_Plot,
#        filename = "~/SLE/Glycans/Plots/GLM/Normal_GLM_ORs_Total.jpeg",
#        height = 18, width = 10, dpi = 300, device = "jpeg")


OR_Plots_wrap_log10 <- OR_Plots_wrap & 
  scale_x_log10(labels = scales::label_scientific(digits = 2))

Plot_x_axis_log10 <- ggplot() +
  labs(x = "Odds Ratio (Log10 scaled)") +
  theme_void() +
  theme(axis.title.x = element_text(face = "bold", size = 12),
        plot.margin  = margin(t = 0, r = 0, b = 0, l = 10))

GLM_Final_log10 <- wrap_plots(list(OR_Plots_wrap_log10, Plot_x_axis_log10),
                         ncol = 1,
                         heights = c(sum(Plot_Heights), 1), 
                         guides  = "collect") +
  plot_annotation(title = "Logistic regression results - Odds Ratio",
                  theme = theme(plot.title.position = "plot",
                                plot.title = element_text(size = 16, 
                                                          face = "bold", 
                                                          hjust = 0))) &
  theme(legend.position = "right")

# ggsave(plot = GLM_Final_log10,
#        filename = "~/SLE/Glycans/Plots/GLM/Normal_GLM_ORs_Total_log10_scale.jpeg",
#        height = 18, width = 10, dpi = 300, device = "jpeg")

GLM_Final_OR_Plot
GLM_Final_log10

```

```{r Firth - Estimates - Horizontal}

Firth_Estimate_Grid_H <- wrap_plots(Estimate_Plots,
                                  ncol = 3,
                                  nrow = 2,         
                                  guides = "collect")   +
  plot_annotation(title = "Firth-Penalized Logistic Regression\nEstimates (Log Odds)", 
                  theme = theme(plot.title.position = "plot",
                  plot.title = element_text(face = "bold",
                                            size = 16, 
                                            hjust = 0))) &
  theme(legend.position = "bottom", 
        legend.justification = c("center", "bottom"),        
        legend.box = "horizontal",      
        legend.direction = "horizontal", 
        plot.margin = margin(t = 5, r = 20, b = 5, l = 5))

# ggsave(Firth_Estimate_Grid_H,
#        filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_Estimates_2x3.jpeg",
#        width = 14, height = 10, dpi = 300)

Firth_Estimate_Grid_H

```

```{r Firth - Estimates - Vertical}

Plot_x_label_Est <- ggplot() +
  labs(x = "Estimates (Log Odds)") +
  theme_void() +
  theme(axis.title.x  = element_text(face = "bold", size = 12),
        plot.margin   = margin(t = 0, r = 0, b = 0, l = 10))

Firth_Estimate_Grid_V <- wrap_plots(
  wrap_plots(Estimate_Plots, ncol = 3, nrow = 2, guides = "collect"),
  Plot_x_label_Est,
  ncol = 1,
  heights = c(10, 1),    
  guides = "collect") +
  plot_annotation(title = "Firth-Penalized Logistic Regression", 
                  theme = theme(plot.title.position = "plot",
                  plot.title = element_text(face = "bold",
                                            size = 16, 
                                            hjust = 0))) &
  theme(legend.position = "right")

# ggsave(Firth_Estimate_Grid_V,
#   filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_Estimates_3x2.jpeg",
#   width = 14, height = 10, dpi = 300)

Firth_Estimate_Grid_V

```

```{r}

Firth_OR_Grid_H <- wrap_plots(OR_Plots,
                                  ncol = 3,
                                  nrow = 2,         
                                  guides = "collect")   +
  plot_annotation(title = "Firth-Penalized Logistic Regression\nOdds Ratio", 
                  theme = theme(plot.title.position = "plot",
                  plot.title = element_text(face = "bold",
                                            size = 16, 
                                            hjust = 0))) &
  theme(legend.position = "bottom", 
        legend.justification = c("center", "bottom"),        
        legend.box = "horizontal",      
        legend.direction = "horizontal", 
        plot.margin = margin(t = 5, r = 20, b = 5, l = 5))

# ggsave(Firth_OR_Grid_H,
#   filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_OR_2x3.jpeg",
#   width = 14, height = 10, dpi = 300)

Firth_OR_Grid_H

```


```{r}

Plot_x_label_OR <- ggplot() +
  labs(x = "Odds Ratio") +
  theme_void() +
  theme(axis.title.x  = element_text(face = "bold", size = 12),
        plot.margin   = margin(t = 0, r = 0, b = 0, l = 10))

Firth_OR_Grid_V <- wrap_plots(
  wrap_plots(OR_Plots, ncol = 2, nrow = 3, guides = "collect"),
  Plot_x_label_OR,
  ncol = 1,
  heights = c(10, 1),    
  guides = "collect") +
  plot_annotation(title = "Firth-Penalized Logistic Regression", 
                  theme = theme(plot.title.position = "plot",
                  plot.title = element_text(face = "bold",
                                            size = 16, 
                                            hjust = 0))) &
  theme(legend.position = "right")

# ggsave(Firth_OR_Grid_V,
#   filename = "~/SLE/Glycans/Plots/Firth_GLM_Delta/Firth_OR_3x2.jpeg",
#   width = 14, height = 10, dpi = 300)

Firth_OR_Grid_V

```
