```{r Libraries}

## Load the libraries ##
library(tidyverse)
library(readxl)
library(purrr)
library(broom)
library(ggtext)
library(ggplot2)
library(broom.helpers)
library(writexl)

```

```{r Figure 3 preparation}

Dataframes_Final <- read_csv(file = "~/SLE/Glycans/Output_Data/Glycans_marker_data_total.csv") 

AI_CI_data <- read_xlsx("~/SLE/Glycans/Data/AI_CI_data.xlsx") %>% 
  rename(ID = "Patients")

AI_CI_Scores <- AI_CI_data %>% 
  select(ID, Time_point, `NIH AI SCORE`, `NIH IC SCORE`)

AI_CI_data_clean <- AI_CI_data %>% 
  select(-c(`NIH AI SCORE`, `NIH IC SCORE`)) %>% 
  pivot_longer(cols = -c(ID, Time_point), names_to = "Result", values_to = "Result_Value") %>% 
  separate(col = Result, into = c("Category", "Result"), sep = " - ", extra = "merge") %>% 
  mutate(Category = gsub(" ", "_", Category), 
         Result = gsub("[ ,\\-]+", "_", Result),
         Result_Value = na_if(Result_Value, "NA"),
         Result_Value = if_else(is.na(Result_Value), 
                         NA_real_, 
                         if_else(Result_Value > 0, 1, 0))) 

AI_CI_data_joint <- AI_CI_data_clean %>%
  inner_join(Dataframes_Final, by = c("ID", "Time_point"), relationship = "many-to-many") 
  
NIH_Test_Results <- AI_CI_data_joint %>%
  filter(!is.na(Result_Value)) %>%
  group_by(Marker, Category, Result, Time_point) %>%
  filter(n_distinct(Result_Value) == 2) %>%
  summarize(NIH_Test = list(wilcox.test(Value ~ factor(Result_Value),
                                        data = cur_data(),
                                        exact = FALSE)),
            .groups = "drop") %>%
  mutate(Wilcox = map(NIH_Test, tidy)) %>%
  unnest(Wilcox, names_sep = "_") %>%
  group_by(Time_point) %>%
  mutate(Wilcox_FDR = p.adjust(Wilcox_p.value, method = "fdr")) %>%
  ungroup() 

Markers_with_sign <- NIH_Test_Results %>%
  group_by(Marker) %>%
  filter(any(Wilcox_p.value < 0.05)) %>%
  pull(Marker) %>%
  unique()

# write_csv(AI_CI_data_clean, file = "~/SLE/Glycans/Output_Data/Histology_data.csv")

```


```{r}

NIH_Marker_DF <- Dataframes_Final %>% 
  filter(Marker %in% Markers_with_sign)

Comparisons <- tribble(~Time_1, ~Time_2, ~Label, 
                       "T0", "T0", "Baseline vs Baseline", 
                       "T12", "T12", "Month 12 vs Month 12",
                       "T0", "T12", "Baseline vs Month 12")

Run_Cor_Hist <- function(Time_1, Time_2, Label) {
  joined <- NIH_Marker_DF %>%
    filter(Time_point == Time_1) %>%
    select(ID, Marker, Value) %>%
    inner_join(AI_CI_data_clean %>% 
                 filter(Time_point == Time_2) %>% 
                 select(ID, Category, Result, Result_Value),
               by = "ID", relationship = "many-to-many")
  
  joined %>%
    group_by(Marker, Result) %>%
    summarize(broom::tidy(cor.test(Value, Result_Value, 
                                   method = "spearman", 
                                   exact = FALSE)),
              .groups = "drop") %>%
    mutate(Comparison = Label)
}

NIH_Corr_Res_Sign_only <- Comparisons %>%
  pmap_dfr(~ Run_Cor_Hist(..1, ..2, ..3)) 

NIH_mapping <- c(Cellular_crescents = "Cellular/Fibrocellular_crescents",
                 Cellular_proliferation = "Endocapillary_hypercellularity",
                 Fibrinoid_necrosis_karyorrhexis = "Fibrinoid_necrosis",
                 Hyaline_thrombi_wire_loops = "Hyaline_deposits",
                 Leukocyte_infiltration = "Neutrophiles/Karyorrhexis",
                 Mononuclear_cell_infiltration = "Interstitial_inflammation")

NIH_Corr_Res_Sign_only_Clean <- NIH_Corr_Res_Sign_only %>% 
  group_by(Comparison) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr"), 
         Significance = case_when(p.value < 0.05 ~ "*"), 
         Origin = sub("_.*$", "", Marker), 
         Comparison = factor(Comparison, levels = c("Baseline vs Baseline", "Month 12 vs Month 12", "Baseline vs Month 12"))) %>% 
  rename(Correlation = "estimate") %>% 
  inner_join(AI_CI_data_clean %>% select(Result, Category), by = c("Result"), relationship = "many-to-many") %>% 
  group_by(Marker) %>% 
  mutate(Origin = sub("_.*$", "", Marker), 
         Marker = sub("^[^_]*_", "", Marker), 
         Result = recode(Result, !!!NIH_mapping), 
         Result = sub("_", "<br>", Result), 
         Result = gsub("_", " ", Result), 
         # Result = sub("/", "/<br>", Result),
         Category = factor(Category, levels = c("NIH_AI", "NIH_CI")),
         Category = gsub("_", " ", Category)) 

# write_csv(NIH_Corr_Res_Sign_only, file = "~/SLE/Glycans/Output_Data/Figure_3_NIH_cors/Glycan_NIH_Correlations.csv")

```


```{r}

NIH_Corr_Res_Sign_only_Clean_Sign <- NIH_Corr_Res_Sign_only_Clean %>%
  group_by(Marker) %>% 
  filter(any(Significance == "*")) %>% 
  ungroup()

Sub_Correlation_plots_NIH <- function(orig) {

  Cor_df_current <- NIH_Corr_Res_Sign_only_Clean_Sign %>% 
    filter(Origin == orig) 
  
  Current_Title <- if (orig == "Serum") {"Serum proteome"} 
  else { orig }
  
  n_markers <- Cor_df_current %>% 
    distinct(Marker) %>% 
    nrow()
  
  n_comp <- Cor_df_current %>% 
    distinct(Result) %>% 
    nrow()
    
  Main_plot_current <- ggplot(Cor_df_current, aes(x = Result, y = Marker, fill = Correlation)) +
    geom_tile(color = "white", width = 1, height = 1) +
    scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                         midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                         guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                                title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
    facet_wrap(~ Comparison, nrow = 1) +
    scale_x_discrete(expand = c(0, 0), drop = TRUE, labels = function(x) str_wrap(x, width = 6)) +
    scale_y_discrete(expand = c(0, 0)) +
    geom_text(aes(label = Significance, vjust = 0.7, hjust = 0.5, fontface = "bold")) +
    labs(title = paste0("Heatmap of marker - clinical/histopathological feature correlations<br>Group: ", Current_Title), x = NULL, y = NULL, 
         caption = paste0("Only markers with significant Wilcoxon test results are shown
         <br><b>Correlation coefficient used:</b> Spearman")) +
    theme_minimal(base_size = 12, base_family = "sans") +
    theme(strip.placement = "outside",
          strip.text.y.right = element_text(angle = 0, hjust = 0.5, vjust = 0.5, face  = "bold"),
          strip.text.x.top = element_text(angle = 0, hjust = 0.5, vjust = 0.5, face  = "bold"),
          axis.text.x = element_markdown(size = 9, angle = 60, hjust = 1, vjust = 1, 
                                         # face = "bold", 
                                         colour = "black"), 
          axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
          panel.grid  = element_blank(), 
          panel.spacing = unit(1, "lines"),
          aspect.ratio = n_markers/n_comp * 0.3,
          plot.caption.position = "plot", 
          plot.caption = element_markdown(hjust = 0.9, vjust = 1, lineheight = 1.3),
          plot.title = element_markdown(face = "bold", lineheight = 1.2))
  
  plot_height <- max(n_markers * 0.4, 4)
  
  # ggsave(Main_plot_current,
  #      filename = paste0("~/SLE/Glycans/Plots_2/Figure_3_Correlations_NIH/Correlations_NIH_", orig,".jpeg"),
  #      width = 23,
  #      height = 12,
  #      dpi = 300)
  
  # Main_plot_current
  
}

plots_by_origin <- map(unique(NIH_Corr_Res_Sign_only_Clean$Origin), Sub_Correlation_plots_NIH)

```


```{r NIH Correlations combined}

Glycan_Annotations_clean <- read_xlsx("~/SLE/Glycans/Output_Data/Gl_annotations_clean.xlsx") %>% 
  mutate(Glycan_Annotation = gsub(pattern = " - Multiple Structures", replacement = "", x = Glycan_Annotation)) %>% 
  select(Origin, Marker, Glycan_Annotation) 

NIH_Corr_Res_Sign_only_Clean_2 <- NIH_Corr_Res_Sign_only_Clean %>% 
  inner_join(Glycan_Annotations_clean, by = c("Origin", "Marker"))

max_len <- NIH_Corr_Res_Sign_only_Clean_2 %>%
  pull(Glycan_Annotation) %>%
  nchar() %>%
  max(na.rm = TRUE)

NIH_Corr_Res_Sign_only_Clean_2 <- NIH_Corr_Res_Sign_only_Clean_2 %>% 
  mutate(Marker = str_pad(Marker, width = max_len, side = "left", pad = "\u00A0"), 
         Glycan_Annotation = str_pad(Glycan_Annotation, width = max_len, side = "left", pad = "\u00A0")) 

DF <- NIH_Corr_Res_Sign_only_Clean_2 %>%
  mutate(RowKey = interaction(Marker, Glycan_Annotation, sep = " | ", drop = TRUE, lex.order = TRUE)) %>% 
  ungroup()

row_levels <- DF %>%
  arrange(Origin, Comparison, Marker) %>%     
  pull(RowKey) %>% 
  unique()

lab_map <- DF %>%
  distinct(RowKey, Glycan_Annotation) %>%
  tibble::deframe()

DF <- DF %>%
  mutate(RowKey = factor(RowKey, levels = row_levels), 
         Marker = str_pad(Marker, width = max_len, side = "left", pad = "\u00A0"), 
         Glycan_Annotation = str_pad(Glycan_Annotation, width = max_len, side = "left", pad = "\u00A0"), 
         RowKey = str_pad(RowKey, width = max_len, side = "left", pad = "\u00A0")) 

```


```{r NIH Correlations plot A4}

Main_plot_current_combined <- ggplot(DF, aes(x = Result, y = RowKey, fill = Correlation)) +
    geom_tile(color = "white", width = 1, height = 1) +
    scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                         midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                         guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                                title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
    facet_grid(Origin ~ Comparison, scales = "free_y", space = "free_y") +
    scale_x_discrete(expand = c(0, 0), drop = TRUE, labels = function(x) str_wrap(x, width = 6)) +
    # scale_y_discrete(expand = c(0, 0)) +
    scale_y_discrete(labels = lab_map, drop = TRUE, expand = c(0,0)) +
    geom_text(aes(label = Significance), vjust = 0.7, hjust = 0.5, fontface = "bold", size = 7) +
  ## Again, vjust is behaving wierd. Mosat likely due to scale = 2 ##
    labs(title = paste0("Heatmap of marker - clinical/histopathological feature correlations"), x = NULL, y = NULL, 
         caption = paste0("Only markers with significant Wilcoxon test results are shown")) +
    theme_minimal(base_size = 12, base_family = "sans") +
    theme(strip.placement = "outside",
          strip.text.y.right = element_markdown(size = 11, angle = 0, hjust = 0.5, vjust = 0.5, face  = "bold"),
          strip.text.x.top = element_text(size = 11, angle = 0, hjust = 0.5, vjust = 0.5, face  = "bold"),
          axis.text.x = element_markdown(size = 11, angle = 60, hjust = 1, vjust = 1,
                                         # face = "bold", 
                                         colour = "black"), 
          axis.text.y = element_text(size = 11, face = "bold", colour = "black"),
          panel.grid  = element_blank(), 
          panel.spacing = unit(1, "lines"),
          # aspect.ratio = n_markers/n_comp * 0.3,
          plot.caption.position = "plot", 
          plot.caption = element_markdown(hjust = 0.9, vjust = 1, lineheight = 1.3),
          plot.title = element_markdown(face = "bold", lineheight = 1.2))

# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_3_Correlations_NIH/Correlations_NIH_Combined_Glycans_A4.jpeg",
#        plot = Main_plot_current_combined, width = 210, height = 297, units = "mm", scale = 2, dpi = 300)

## Save the excels ##
# write_xlsx(x = NIH_Corr_Res_Sign_only_Clean_2,
#            path = "~/SLE/Glycans/Output_Data/Figure_3_NIH_cors/Figure_3_Glycan_NIH_Correlations.xlsx")

# NIH_Corr_Res_Sign_only_Clean_2 %>%
#   filter(Comparison == "Baseline vs Baseline") %>%
#   write_xlsx(x = .,
#              path = "~/SLE/Glycans/Output_Data/Figure_3_NIH_cors/Figure_3_Glycan_NIH_Correlations_BvsB.xlsx")
# 
# NIH_Corr_Res_Sign_only_Clean_2 %>%
#   filter(Comparison == "Month 12 vs Month 12") %>%
#   write_xlsx(x = .,
#              path = "~/SLE/Glycans/Output_Data/Figure_3_NIH_cors/Figure_3_Glycan_NIH_Correlations_M12vsM12.xlsx")
# 
# NIH_Corr_Res_Sign_only_Clean_2 %>%
#   filter(Comparison == "Baseline vs Month 12") %>%
#   write_xlsx(x = .,
#              path = "~/SLE/Glycans/Output_Data/Figure_3_NIH_cors/Figure_3_Glycan_NIH_Correlations_BvsM12.xlsx")
```

