```{r Load the libraries}

library(tidyverse)
library(ggplot2)
library(readxl)
library(survival)
# library(ranger)
library(ggplot2)
library(dplyr)
library(ggfortify)
library(scales)
library(broom)
library(coxphf)
library(ggtext)
library(timereg)

```

```{r Load event times for renal impairment}

Patients <- read_csv("~/SLE/Glycans/Output_Data/Glycans_marker_data_total.csv") %>% 
  select(ID) %>% 
  distinct()

Survival_Dataframe <- read_xlsx("~/SLE/Glycans/Data/Survival_Data.xlsx") %>% 
  mutate(Biopsy_Date = dmy(Date_Biopsy), 
         imp_date = case_when(`Renal Impairment` %in% c("0","1", NA) ~ NA_character_, TRUE ~ `Renal Impairment`),
         imp_date = dmy(imp_date))

Survival_Data <- Survival_Dataframe %>% group_by(Patients) %>% 
    summarise(Start = Biopsy_Date[Timing_Biopsy == "T0"], 
              Last = Biopsy_Date[Timing_Biopsy == "T12"], 
              Event_Date = imp_date %>% 
                na.omit() %>% 
                first(),
              Event = if_else(!is.na(Event_Date) & Event_Date <= Last, 1L, 0L),
              End = if_else(Event == 1L, Event_Date, Last),
              Time = as.numeric(difftime(End, Start, units = "days"))) %>% 
    ungroup() %>% 
  rename(ID = Patients)

```

```{r Load glycans and join}

Marker_DF <- read_csv(file = "~/SLE/Glycans/Output_Data/Glycans_marker_data_total.csv")

Glycans_Data <- Marker_DF %>%
  group_by(Time_point, Marker) %>%
  
  ## Since we have four samples with NA values we will replace them with the median value for each marker ##
  ## Too few samples too drop (19 total, so 4 is quite a large amount) ##
  
  mutate(Marker_Median = median(Value, na.rm = TRUE), 
         Value = if_else(is.na(Value), Marker_Median, Value)) %>% 
  select(-Marker_Median) %>% 
  ungroup() %>% 
  pivot_wider(id_cols = c(ID, Origin, Marker), names_from = Time_point, values_from = Value) %>% 
  mutate(Delta = T12 - T0, 
         Log2FC = log2(T12/T0))

Joint_DF <- Survival_Data %>% 
  inner_join(Glycans_Data, by = "ID")

Markers <- Joint_DF %>% 
  distinct(Marker) %>% 
  pull()

```

```{r Perform the Cox regressions - Univariate}

Cox_formula_all <- reformulate(Markers, response = "Surv(Time, Event)")

Cox_Results_Uni_Total <- Joint_DF %>% 
  select(ID, Time, Event, Marker, T0, T12, Delta) %>% 
  pivot_longer(cols = -c(ID, Time, Event, Marker), names_to = "Comparison", values_to = "Value") %>% 
  group_by(Comparison, Marker) %>% 
  nest() %>% 
  mutate(Fit = map(data, ~ coxph(Surv(Time, Event) ~ Value, data = .x)),
         Tidy = map(Fit, ~ tidy(.x, exponentiate = TRUE, conf.int = TRUE))) %>%
  unnest(Tidy) %>%
  select(Comparison, Marker, estimate, std.error, statistic, p.value, conf.low, conf.high, hazard_ratio = estimate) %>%
  arrange(Comparison, p.value) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr")) %>% 
  ungroup() 

# Multi_Cox_Firth_Strict <- coxphf(reformulate(Top_Markers_T0_strict, response = "Surv(Time, Event)"), 
#                           data = Joint_imp, maxit = 200, maxstep = 0.2)
# 

```

```{r Perform the Cox regressions - Multivariate}

Top_Markers_strict <- Cox_Results_Uni_Total %>% 
  filter(p.value < 0.05) 

Top_Markers_lax <- Cox_Results_Uni_Total %>% 
  filter(p.value < 0.1) 

Run_multi_cox <- function(Top_Markers) {
Joint_DF %>% 
  select(ID, Time, Event, Marker, T0, T12, Delta) %>% 
  pivot_longer(cols = -c(ID, Time, Event, Marker), names_to = "Comparison", values_to = "Value") %>% 
  group_by(Comparison) %>% 
  nest() %>% 
  mutate(Markers = map(Comparison, ~ Top_Markers %>% 
                         filter(Comparison == .x) %>% 
                         pull(Marker)), 
         
         Data = map2(data, Markers, ~ .x %>% 
                       filter(Marker %in% .y) %>% 
                       select(ID, Time, Event, Marker, Value) %>% 
                       pivot_wider(id_cols = c(ID, Time, Event), names_from = Marker, values_from = Value)), 
         
         Formula = map(Markers, ~ reformulate(.x, response = "Surv(Time, Event)")), 
         
         Fit = map2(Formula, Data, ~ coxph(.x, data = .y)), 
         
         Tidy = map(Fit, ~ tidy(.x, exponentiate = TRUE, conf.int = TRUE))) %>% 
    unnest(Tidy) %>% 
    select(Comparison, Marker = term, estimate, std.error, statistic, 
           p.value, conf.low, conf.high, hazard_ratio = estimate) %>% 
    group_by(Comparison) %>% 
    mutate(FDR = p.adjust(p.value, method = "fdr")) %>% 
    ungroup()
    
}

Cox_Results_Multi_Total_strict <- Run_multi_cox(Top_Markers_strict)

# Multi_Cox_Firth_Strict <- coxphf(reformulate(Top_Markers_T0_strict, response = "Surv(Time, Event)"), 
#                           data = Joint_imp, maxit = 200, maxstep = 0.2)

```

```{r Visualise normal Cox results}

Plot_Cox_Results <- function(Plot, Type, Filter) {
 Plot %>% 
  separate(Marker, c("Origin", "Marker"), sep = "_", extra = "merge") %>% 
  mutate(Origin = factor(Origin, levels = c("AGP", "C3", "Fab", "Fc", "IgG", "Serum")), 
         Origin = gsub("Serum", "Serum<br>proteome", Origin), 
         Marker = if_else(p.value < 0.05, paste0("<span style='font-size:18px'>* </span>", Marker), Marker)) %>% 
    { if (Filter) filter(., p.value < 0.05) else . } %>% 
  ggplot(., aes(x = hazard_ratio, y = Marker, colour = Comparison)) +
      geom_point(position = position_dodge(0.6), size = 3) +
      geom_errorbarh(aes(xmin = conf.low, xmax = conf.high),
                     position = position_dodge(0.6),
                     height = 0.2) +
    geom_vline(xintercept = 1, linetype = 2, colour = "black") +
    scale_color_manual(values = c(T0 = "cyan3", T12 = "coral1", Delta = "mediumspringgreen"), 
                       name = "Glycan values tested for<br>the cox regression") +
      scale_x_log10() +
      facet_grid(Origin ~ ., scales = "free_y", space = "free_y") +
      labs(title = paste0(Type, " Cox regression: Hazard ratios with 95% CI"), 
           caption = paste0("Only markers which were significant in the univariate analysis shown"), 
           x = "Hazard ratio") +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0, face = "bold"),
            panel.grid.major.y = element_blank(), 
            axis.title.y = element_blank(),
            axis.text.y = element_markdown(face = "bold"),
            axis.title.x = element_markdown(), 
            axis.ticks.x = element_blank(), 
            legend.text = element_markdown(size = 10), 
            plot.caption = element_markdown(), 
            strip.text.y.right = element_markdown(angle = 0, 
                                                  hjust = 0.5, 
                                                  vjust = 0.5, 
                                                  face  = "bold"), 
            legend.title = element_markdown(face = "bold"))

}

Cox_Uni_plot <- Plot_Cox_Results(Cox_Results_Uni_Total, "Univariate", Filter = TRUE)
Cox_Multi_plot <- Plot_Cox_Results(Cox_Results_Multi_Total_strict, "Multivariate", Filter = FALSE)

# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_6_Survival/Cox_Uni_Sign.jpeg", 
#        plot = Cox_Uni_plot, height = 10, width = 15, dpi = 300, device = "jpeg")
# 
# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_6_Survival/Cox_Multi.jpeg", 
#        plot = Cox_Multi_plot, height = 10, width = 15, dpi = 300, device = "jpeg")

```


```{r Visualise normal Cox results - Manual}


 Cox_Results_Multi_Total_strict %>% 
  filter(Comparison == "T12") %>% 
  separate(Marker, c("Origin", "Marker"), sep = "_", extra = "merge") %>% 
  mutate(Origin = factor(Origin, levels = c("AGP", "C3", "Fab", "Fc", "IgG", "Serum")), 
         Origin = gsub("Serum", "Serum<br>proteome", Origin), 
         Marker = if_else(p.value < 0.05, paste0("<span style='font-size:18px'>* </span>", Marker), Marker)) %>% 
    # { if (Filter) filter(., p.value < 0.05) else . } %>% 
  ggplot(., aes(x = hazard_ratio, y = Marker, colour = Comparison)) +
      geom_point(position = position_dodge(0.6), size = 3) +
      geom_errorbarh(aes(xmin = conf.low, xmax = conf.high),
                     position = position_dodge(0.6),
                     height = 0.2) +
      geom_vline(xintercept = 1, linetype = 2, colour = "black") +
      scale_color_manual(values = c(T0 = "cyan3", T12 = "coral1", Delta = "mediumspringgreen"), 
                       name = "Glycan values tested for<br>the cox regression") +
      scale_x_log10(limits = c(0.2, 5), oob = oob_squish) +
      facet_grid(Origin ~ ., scales = "free_y", space = "free_y") +
      labs(title = "Multivariate Cox regression: Hazard ratios with 95% CI", 
           caption = "Only markers which were significant in the univariate analysis shown", 
           x = "Hazard ratio") +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0, face = "bold"),
            panel.grid.major.y = element_blank(), 
            axis.title.y = element_blank(),
            axis.text.y = element_markdown(face = "bold"),
            axis.title.x = element_markdown(), 
            axis.ticks.x = element_blank(), 
            legend.text = element_markdown(size = 10), 
            plot.caption = element_markdown(), 
            strip.text.y.right = element_markdown(angle = 0, 
                                                  hjust = 0.5, 
                                                  vjust = 0.5, 
                                                  face  = "bold"), 
            legend.title = element_markdown(face = "bold"))

# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_6_Survival/Cox_Uni_Sign.jpeg", 
#        plot = Cox_Uni_plot, height = 10, width = 15, dpi = 300, device = "jpeg")
# 
# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_6_Survival/Cox_Multi.jpeg", 
#        plot = Cox_Multi_plot, height = 10, width = 15, dpi = 300, device = "jpeg")

```

```{r Kaplan meier plot}

cox <- coxph(Surv(Time, Event) ~ 1, data = Survival_Data)
km_fit <- survfit(cox)

Survival_plot <- autoplot(km_fit, surv.geom = "step", 
         censor.geom = "point", 
         censor.shape = 3, 
         censor.size = 2, 
         censor.colour = "firebrick",
         conf.int = TRUE, 
         conf.int.fill = "royalblue", 
         conf.int.colour = "midnightblue",
         conf.int.style = "ribbon", 
         conf.int.alpha = 0.2) +
  theme_minimal(base_size = 14, base_family = "sans") +
  labs(title = "Kaplan Meier curve",
       subtitle = "Renal impairment probability over time",
       x = "Days since baseline", 
       y = "Renal impairment probability") +
  scale_y_continuous(labels = percent_format(accuracy = 1),
                     limits = c(0, 1), 
                     expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "grey90"),
        plot.title = element_text(face = "bold", size = 16),
        plot.subtitle = element_text(size = 12))

# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_6_Survival/Survival_Plot_Basic.jpeg",
#        plot = Survival_plot, width = 10, height = 6, dpi = 300, device = "jpeg")

```

```{r Cox - Firth}

Run_multi_coxf <- function(Top_Markers) {
Joint_DF %>% 
  select(ID, Time, Event, Marker, T0, T12, Delta) %>% 
  pivot_longer(cols = -c(ID, Time, Event, Marker), names_to = "Comparison", values_to = "Value") %>% 
  group_by(Comparison) %>% 
  nest() %>% 
  mutate(Markers = map(Comparison, ~ Top_Markers %>% 
                         filter(Comparison == .x) %>% 
                         pull(Marker)), 
         
         Data = map2(data, Markers, ~ .x %>% 
                       filter(Marker %in% .y) %>% 
                       select(ID, Time, Event, Marker, Value) %>% 
                       pivot_wider(id_cols = c(ID, Time, Event), names_from = Marker, values_from = Value)), 
         
         Formula = map(Markers, ~ reformulate(.x, response = "Surv(Time, Event)")), 
         
         Fit = map2(Formula, Data, ~ coxphf(.x, data = .y, firth = TRUE, maxit = 200, maxstep = 0.2)), 
         
         Tidy = map(Fit, ~ {
           fit <- .x
           est <- coef(fit)
           term <- names(coef(fit))
           se <- sqrt(diag(vcov(fit)))
           stat <- est/se
           lower <- fit$ci.lower
           upper <- fit$ci.upper
           pval <- fit$prob
         
         tibble(Marker = term, 
                estimate = est, 
                std.error = se,
                statistic = stat, 
                p.value = pval, 
                CI_lower = lower,
                CI_upper = upper) } )) %>% 
    unnest(Tidy) %>% 
    select(Comparison, Marker, hazard_ratio = estimate, std.error, CI_lower, CI_upper, statistic, p.value) %>% 
    group_by(Comparison) %>% 
    mutate(FDR = p.adjust(p.value, method = "fdr")) %>%
    ungroup() %>% 
    mutate(Model = "Firth penalised")
    
}

Cox_Results_Multi_firth <- Run_multi_coxf(Top_Markers_strict)

```

```{r Cox - Firth - Visualisation}

Cox_Results_Multi_firth_clean <- Cox_Results_Multi_firth %>% 
  mutate(Annotation = case_when(p.value < 0.05 ~ "Significant", 
                                is.na(p.value) ~ "Model did not converge",
                                TRUE ~ "Not significant"))

Cox_Multi_firth_plot <- Cox_Results_Multi_firth_clean %>%
  filter(Comparison == "Delta") %>%
  separate(Marker, c("Origin", "Marker"), sep = "_", extra = "merge") %>% 
  mutate(Origin = factor(Origin, levels = c("AGP", "C3", "Fab", "Fc", "IgG", "Serum")), 
         Origin = gsub("Serum", "Serum<br>proteome", Origin), 
         Marker = factor(Marker, levels = c(unique(Marker))), 
         Marker = if_else(p.value < 0.05, paste0("<span style='font-size:18px'>* </span>", Marker), Marker)) %>% 
  ggplot(., aes(x = hazard_ratio, y = Marker, colour = Comparison)) +
  geom_point(position = position_dodge(0.6), size = 3, na.rm = TRUE) +
  geom_errorbarh(data = . %>% filter(!is.na(CI_lower) & !is.na(CI_upper)),
                 aes(xmin = CI_lower, xmax = CI_upper),
                 position = position_dodge(0.6),
                 height = 0.2) +
  scale_color_manual(values = c(T0 = "cyan3", T12 = "coral1", Delta = "mediumspringgreen"), 
                   name = "Glycan values tested for<br>the cox regression") +
  scale_x_log10() +
  scale_y_discrete(drop = FALSE) +
  facet_grid(Origin ~ ., scales = "free_y", space = "free_y", drop = FALSE) +
  labs(title = "Cox regression results - Firth penalised: Hazard ratios with 95% CI", 
       caption = paste0("Only markers which were significant in the non-penalised univariate analysis shown
                        <br>T0 and T12 values did not converge and were ommited"),
       x = "Hazard ratio") +
  theme_minimal(base_size = 11, base_family = "sans") +
  theme(plot.title = element_text(hjust = 0, face = "bold"),
        panel.grid.major.y = element_blank(), 
        axis.title.y = element_blank(),
        axis.text.y = element_markdown(face = "bold"),
        axis.title.x = element_markdown(), 
        axis.ticks.x = element_blank(), 
        legend.text = element_markdown(size = 10), 
        plot.caption = element_markdown(lineheight = 1.3, hjust = 1), 
        strip.text.y.right = element_markdown(angle = 0, 
                                              hjust = 0.5, 
                                              vjust = 0.5, 
                                              face  = "bold"), 
        strip.text.x.top = element_blank(), 
        legend.title = element_markdown(face = "bold"))

# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_6_Survival/Cox_Multi_Firth.jpeg",
#        plot = Cox_Multi_firth_plot, height = 10, width = 15, dpi = 300, device = "jpeg")

```

```{r Cox regression - Additive model}

Run_multi_aalen <- function(Top_Markers) {
Joint_DF %>% 
  select(ID, Time, Event, Marker, T0, T12, Delta) %>% 
  pivot_longer(cols = -c(ID, Time, Event, Marker), names_to = "Comparison", values_to = "Value") %>% 
  group_by(Comparison) %>% 
  nest() %>% 
  mutate(Markers = map(Comparison, ~ Top_Markers %>% 
                         filter(Comparison == .x) %>% 
                         pull(Marker)), 
         
         Data = map2(data, Markers, ~ .x %>% 
                       filter(Marker %in% .y) %>% 
                       select(ID, Time, Event, Marker, Value) %>% 
                       pivot_wider(id_cols = c(ID, Time, Event), names_from = Marker, values_from = Value)), 
         
         Formula = map(Markers, ~ reformulate(.x, response = "Surv(Time, Event)")), 
         
         Fit = map2(Formula, Data, ~ aalen(.x, data = .y, gamma = 1e-3)), 
         
         Tidy = map(Fit, function(fit) {
           cum_mat <- fit$cum       
           var_mat <- fit$var.cum    
           last_cum <- tail(cum_mat, 1)     
           last_var <- tail(var_mat, 1)      
           terms <- colnames(cum_mat)[-1]   
           est <- as.numeric(last_cum[-1]) 
           se <- sqrt( as.numeric(last_var[-1]))
           z <- est / se
           pval <- 2 * pnorm(-abs(z))
           ci_lo <- est - qnorm(0.975) * se
           ci_hi <- est + qnorm(0.975) * se
          
           tibble(Marker = terms,
                  estimate = est,
                  std.error = se,
                  statistic = z,
                  p.value = pval,
                  CI_lower = ci_lo,
                  CI_upper = ci_hi) })) %>% 
    
    unnest(Tidy) %>% 
    select(Comparison, Marker, estimate, std.error, CI_lower, CI_upper, statistic, p.value) %>% 
    group_by(Comparison) %>% 
    mutate(FDR = p.adjust(p.value, method = "fdr")) %>%
    ungroup() %>% 
    mutate(Model = "Aalen additive") %>% 
    filter(Marker != "(Intercept)")
    
}

Aalen_Results_Multi <- Run_multi_aalen(Top_Markers_strict)


```

```{r Join the Cox - Delta multi models}

Select_Columns <- c("Model", "Comparison", "Marker", 
                    "hazard_ratio", "std.error", "CI_lower", 
                    "CI_upper", "statistic", "p.value")

Cox_multi <- Cox_Results_Multi_Total_strict %>% 
  filter(Comparison == "Delta") %>% 
  rename(CI_lower = conf.low, 
         CI_upper = conf.high) %>% 
  mutate(Model = "Cox regression") %>% 
  select(any_of(Select_Columns))

Coxf_multi <- Cox_Results_Multi_firth %>% 
  filter(Comparison == "Delta") %>% 
  mutate(estimate = hazard_ratio, 
         hazard_ratio = exp(hazard_ratio)) %>% 
  select(any_of(Select_Columns))

Coxa_multi <- Aalen_Results_Multi %>% 
  filter(Comparison == "Delta") %>% 
  mutate(hazard_ratio = exp(estimate)) %>% 
  select(any_of(Select_Columns))

Multi_models_delta <- rbind(Cox_multi, Coxf_multi, Coxa_multi)

```

```{r Cox - Delta multi models - Visualisation}

Model_Pallete <- c(`Cox regression` = "cyan3",
                   `Firth penalised` = "coral1", 
                   `Aalen additive` = "mediumspringgreen")

Marker_annotation <- Multi_models_delta %>%
  group_by(Marker) %>%
  summarise(Annotation = {Sig_models <- unique(Model[p.value < 0.05])
  
      if (length(Sig_models) == 0) {
        ""
      } else {
        paste0(map_chr(Sig_models, ~ sprintf("<span style='color:%s; font-size:18px'>*</span>", 
                                             Model_Pallete[.x])), collapse = " ") 
        } }, .groups = "drop") %>% 
  mutate(Marker = gsub("^[^_]+_", "", Marker))

Multi_models_delta_clean <- Multi_models_delta %>% 
  separate(Marker, c("Origin", "Marker"), sep = "_", extra = "merge") %>% 
  mutate(Origin = factor(Origin, levels = c("AGP", "C3", "Fab", "Fc", "IgG", "Serum")), 
         Origin = gsub("Serum", "Serum<br>proteome", Origin), 
         Marker = factor(Marker, levels = c(unique(Marker))), 
         Significance = case_when(p.value < 0.05 ~ "Significant", 
                                  TRUE ~ "Not significant")) %>% 
  inner_join(Marker_annotation, by = "Marker") %>% 
  mutate(Marker_annotation = paste0(Annotation, Marker))


Multi_model_plot_strict <- Multi_models_delta_clean %>%
  ggplot(., aes(x = hazard_ratio, y = Marker_annotation, colour = Model)) +
  geom_point(position = position_dodge(0.6), size = 3,  na.rm = TRUE) +
  geom_errorbarh(data = . %>% filter(!is.na(CI_lower) & !is.na(CI_upper)),
                 aes(xmin = CI_lower, xmax = CI_upper),
                 position = position_dodge(0.6),
                 height = 0.2) +
  geom_vline(xintercept = 1, linetype = 2, colour = "black") +
  scale_color_manual(values = Model_Pallete, 
                     name = "Models tested") +
  scale_x_log10() +
  scale_y_discrete(drop = FALSE) +
  facet_grid(Origin ~ ., scales = "free_y", space = "free_y", drop = FALSE) +
  labs(title = "Cox regression results - Model comparison: Hazard ratios with 95% CI", 
       caption = paste0("Only markers which were significant in the non-penalised univariate analysis shown
                        <br>T0 and T12 values did not converge and were ommited"),
       x = "Hazard ratio") +
  theme_minimal(base_size = 11, base_family = "sans") +
  theme(plot.title = element_text(hjust = 0, face = "bold"),
        panel.grid.major.y = element_blank(), 
        axis.title.y = element_blank(),
        axis.text.y = element_markdown(face = "bold"),
        axis.title.x = element_markdown(), 
        axis.ticks.x = element_blank(), 
        legend.text = element_markdown(size = 11), 
        plot.caption.position = "plot",
        plot.caption = element_markdown(lineheight = 1.3, hjust = 1), 
        strip.text.y.right = element_markdown(angle = 0, 
                                              hjust = 0.5, 
                                              vjust = 0.5, 
                                              face  = "bold"), 
        strip.text.x.top = element_blank(), 
        legend.title = element_markdown(face = "bold"))
  

# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_6_Survival/Multi_models_strict.jpeg",
#        plot = Multi_model_plot_strict, height = 10, width = 15, dpi = 300, device = "jpeg")

```


```{r Alternative Multivariate Cox visualisation}

Cox_Results_Multi_firth_clean <- Cox_Results_Multi_firth %>% 
  mutate(Annotation = case_when(p.value < 0.05 ~ "Significant", 
                                is.na(p.value) ~ "Model did not converge",
                                TRUE ~ "Not significant"))

Cox_Multi_firth_plot2 <- Cox_Results_Multi_firth_clean %>%
  filter(Comparison == "Delta") %>%
  separate(Marker, c("Origin", "Marker"), sep = "_", extra = "merge") %>% 
  mutate(Origin = factor(Origin, levels = c("AGP", "C3", "Fab", "Fc", "IgG", "Serum")), 
         Origin = gsub("Serum", "Serum<br>proteome", Origin), 
         Marker = factor(Marker, levels = c(unique(Marker))), 
         Marker = if_else(p.value < 0.05, paste0("<span style='font-size:18px'>* </span>", Marker), Marker)) %>% 
  ggplot(., aes(x = hazard_ratio, y = Marker, colour = Comparison)) +
  geom_point(position = position_dodge(0.6), size = 3, na.rm = TRUE) +
  geom_errorbarh(data = . %>% filter(!is.na(CI_lower) & !is.na(CI_upper)),
                 aes(xmin = CI_lower, xmax = CI_upper),
                 position = position_dodge(0.6),
                 height = 0.2) +
  geom_vline(xintercept = 1, linetype = 2, colour = "black") +
  scale_color_manual(values = c(T0 = "cyan3", T12 = "coral1", Delta = "mediumspringgreen"), 
                   name = "Glycan values tested for<br>the cox regression") +
  scale_x_log10() +
  scale_y_discrete(drop = FALSE) +
  facet_grid(Origin ~ ., scales = "free_y", space = "free_y", drop = FALSE) +
  labs(title = "Multivariate Cox regression - Firth penalised: Hazard ratios with 95% CI", 
       caption = paste0("Only markers which were significant in the non-penalised univariate analysis shown
                        <br>T0 and T12 values did not converge and were ommited"),
       x = "Hazard ratio") +
  theme_minimal(base_size = 11, base_family = "sans") +
  theme(plot.title = element_text(hjust = 0, face = "bold"),
        panel.grid.major.y = element_blank(), 
        axis.title.y = element_blank(),
        axis.text.y = element_markdown(face = "bold", size = 11),
        axis.title.x = element_markdown(), 
        axis.ticks.x = element_blank(), 
        legend.text = element_markdown(size = 11), 
        plot.caption = element_markdown(lineheight = 1.3, hjust = 1), 
        strip.text.y.right = element_markdown(angle = 0, 
                                              hjust = 0.5, 
                                              vjust = 0.5, 
                                              face  = "bold", size = 11), 
        strip.text.x.top = element_blank(), 
        legend.title = element_markdown(face = "bold"))

# ggsave(filename = "~/SLE/Glycans/Plots_2/Figure_6_Survival/Cox_Multi_Firth.jpeg",
#        plot = Cox_Multi_firth_plot, height = 10, width = 15, dpi = 300, device = "jpeg")

```

```{r Combined plots}

library(patchwork)


Combined_Uni_Multi_all <- wrap_plots(Cox_Uni_plot, Multi_model_plot_strict, nrow = 2)  +
  plot_layout(heights = c(2, 1))

Combined_Uni_Multi_firth <- wrap_plots(Cox_Uni_plot, Cox_Multi_firth_plot2, nrow = 2)  +
  plot_layout(heights = c(2, 1)) + 
  plot_annotation(tag_levels = "A") & 
  theme(plot.tag = element_text(color = "black", face = "bold", size = 30), 
        axis.text = element_markdown(size = 11), 
        plot.caption = element_blank(), 
        text = element_text(size = 11, family = "sans"),
        axis.text.x = element_markdown(size = 11),
        axis.text.y = element_markdown(size = 11, face = "bold"),
        strip.text = element_markdown(size = 11, face = "bold"),
        strip.text.y.right = element_markdown(size = 11, face = "bold", hjust = 0),
        plot.title = element_markdown(size = 16, face = "bold"))

# ggsave(plot = Combined_Uni_Multi_firth,
#        filename = "~/SLE/Glycans/Plots_2/Figure_6_Survival/Combined_firth.jpeg",
#        width = 210, height = 297, units = "mm", dpi = 300, device = "jpeg", scale = 2)

```

```{r Tidy tables}

library(gtsummary)

theme_gtsummary_compact()
theme_gtsummary_journal(journal = "lancet")

dat <- Joint_DF %>% 
  select(ID, Time, Event, Marker, Delta) %>% 
  tidyr::pivot_wider(id_cols = c(ID, Time, Event),
                     names_from = Marker, values_from = Delta) 

bad <- dat %>% 
  dplyr::select(-ID, -Time, -Event) %>% 
  summarise(dplyr::across(everything(), ~ sd(.x, na.rm = TRUE))) %>% 
  tidyr::pivot_longer(everything(), names_to = "var", values_to = "sd") %>% 
  filter(!is.finite(sd) | sd == 0) %>% 
  pull(var)

dat <- dplyr::select(dat, -dplyr::any_of(bad))

markers <- setdiff(names(dat), c("ID","Time","Event"))

tbl_uni_cox <- tbl_uvregression(data = dat, 
                                method = survival::coxph,
                                y = Surv(Time, Event),
                                include = all_of(markers),
                                exponentiate = TRUE, 
                                method.args = list(ties = "efron",
                                                   control = survival::coxph.control(iter.max = 100, eps = 1e-8)))

```


