```{r Correlation plots by Origin but combine them}

Correlation_Results_Clean_Sign <- Correlation_Results_Clean %>%
  group_by(Marker) %>% 
  filter(any(Significance == "*")) %>% 
  ungroup()

Cor_Range <- Correlation_Results_Clean_Sign %>% 
  summarise(min_corr = min(Correlation, na.rm = TRUE), 
            max_corr = max(Correlation, na.rm = TRUE))

Correlation_Results_Clean_Sign <- Correlation_Results_Clean_Sign %>% 
  separate(col = Marker, into = c("Origin", "Marker"), sep = "_", extra = "merge", fill = "right") 

max_len <- Correlation_Results_Clean_Sign %>%
  pull(Marker) %>%
  nchar() %>%
  max(na.rm=TRUE)

Correlation_Results_Clean_Sign <- Correlation_Results_Clean_Sign %>% 
  mutate(Marker = str_pad(Marker, width = max_len, side = "left", pad = "\u00A0")) 

Sub_Correlation_plots <- function(orig) {

  max_len <- max(nchar(Correlation_Results_Clean_Sign$Marker))
  
  Cor_df_current <- Correlation_Results_Clean_Sign %>% 
    filter(Origin == orig)

  Current_Title <- if (orig == "Serum") {"Serum Proteome"} 
  else { orig }
  
  n_markers <- Cor_df_current %>% 
    distinct(Marker) %>% 
    nrow()
  
  n_comp <- Cor_df_current %>% 
    distinct(Comparator) %>% 
    nrow()
  
  Main_plot_current <- ggplot(Cor_df_current, aes(x = Comparator, y = Marker, fill = Correlation)) +
    geom_tile(color = "white", width = 1, height = 1) +
    scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                         limits = c(Cor_Range$min_corr, Cor_Range$max_corr), 
                         midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                         guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                                title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
    facet_wrap(~Comparison, nrow = 1) +
    geom_text(aes(label = Significance, vjust = 0.5, hjust = 0.5, fontface = "bold")) +
    scale_y_discrete(expand = c(0,0)) +
    scale_x_discrete(expand = c(0,0)) +
    labs(title = paste0("Origin: ", Current_Title), x = NULL, y = NULL,
         # caption = paste0("Correlation coefficient used: <b>Spearman</b> ")
         ) +
    theme_minimal(base_size = 12, base_family = "sans") +
    theme(strip.placement = "outside",
          strip.text.y.left = element_blank(),
          strip.text.x.top = element_text(size = 11, face = "bold", colour = "black"),
          axis.text.x = element_markdown(size = 9, angle = 0, hjust = 0.5, 
                                         face = "bold", colour = "black", 
                                         margin = margin(t = 10, unit = "pt")), 
          axis.text.y = element_text(size = 11, face = "bold", colour = "black", margin = margin(r = 10, unit = "pt"), hjust = 1),
          panel.grid  = element_blank(), 
          panel.spacing = unit(1, "lines"), 
          plot.title = element_markdown(face = "bold", lineheight = 1.2),
          aspect.ratio = n_markers/n_comp * 0.3,
          plot.caption.position = "plot", 
          plot.caption = element_markdown(size = 10, hjust = 0.9, vjust = 1),
          plot.margin = margin(10, 10, 10, 10, "pt")) + 
    coord_fixed()

  plot_height <- max(n_markers * 0.3, 4)
  
  ggsave(Main_plot_current,
       filename = paste0("~/SLE/Glycans/Plots_2/Figure_2_Correlations_Total/Correlations_", orig,"_2.jpeg"),
       width = 15,
       height = 10,
       dpi = 300)
  
  Main_plot_current
}

plots_by_origin <- map(unique(Correlation_Results_Clean$Origin), Sub_Correlation_plots)

## Removed from caption: <br>P value: <b>Not adjusted</b> ##
```

```{r}

plots_by_origin <- map(origins, Sub_Correlation_plots)

order_idx     <- c(1, 6, 3, 4, 2, 5)
plots_reorder <- plots_by_origin[order_idx]

## Pull them out into named objects ##
p1 <- plots_reorder[[1]]  # origin 1
p6 <- plots_reorder[[2]]  # origin 6
p3 <- plots_reorder[[3]]  # origin 3
p4 <- plots_reorder[[4]]  # origin 4
p2 <- plots_reorder[[5]]  # origin 2
p5 <- plots_reorder[[6]]  # origin 5

p1 <- p1 + theme(plot.title.position = "panel")
p2 <- p2 + theme(plot.title.position = "panel")
p3 <- p3 + theme(plot.title.position = "panel")
p4 <- p4 + theme(plot.title.position = "panel")
p5 <- p5 + theme(plot.title.position = "panel")
p6 <- p6 + theme(plot.title.position = "panel")

# 1) compute row‐counts for p1 and p2:
n1 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[1]) %>%     # or whatever origin gives p1
  distinct(Marker) %>% nrow()

n2 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[2]) %>%     # origin for p2
  distinct(Marker) %>% nrow()

n3 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[3]) %>%     # origin for p2
  distinct(Marker) %>% nrow()

n4 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[4]) %>%     # or whatever origin gives p1
  distinct(Marker) %>% nrow()

n5 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[5]) %>%     # origin for p2
  distinct(Marker) %>% nrow()

n6 <- Correlation_Results_Clean_Sign %>%
  filter(Origin == origins[6]) %>%     # origin for p2
  distinct(Marker) %>% nrow()


```



```{r}

library(patchwork)
library(grid)   # for unit()

# assume p1…p6 and n1…n6 are already defined

final_plot <- wrap_plots(
  wrap_plots(p1, p2, p3, ncol = 1, heights = c(n1, n2, n3)),
  wrap_plots(p4, p5, p6, ncol = 1, heights = c(n4, n5, n6)),
  ncol = 2,
  guides = "collect") +
  plot_annotation(
    title = "Heatmap of Marker Correlations compared to Clicinal Indexes",
    tag_levels = "A",   
    tag_prefix = "[",        
    tag_suffix = "]", 
  theme = theme(
    plot.title = element_text(face = "bold", size = 23),
    plot.title.position = "plot", 
    plot.title.hjust = 0.5,       
    plot.tag = element_text(face = "bold", colour = "black", size = 13))) &
  theme(
    legend.position = "right",
    legend.title = element_text(face = "bold"),
    legend.key.width = unit(2, "lines"),
    legend.key.height = unit(4, "lines"),    
    legend.spacing.y = unit(0.5, "lines"))

ggsave(
  "~/Downloads/combined_total_with_title.jpeg",
  final_plot,
  width  = 30,
  height = 20,
  dpi    = 300
)

```
