
```{r Libraries}

library(tidyverse)
library(ggplot2)
library(patchwork)
library(readxl)
library(ggtext)

```

```{r}

NIH_Corr_Res_Sign_only <- read_csv("~/SLE/Glycans/Output_Data/Histology_Marker_Correlations.csv")

AI_CI_data <- read_xlsx("~/SLE/Glycans/Data/AI_CI_data.xlsx") %>% 
  rename(ID = "Patients")

AI_CI_data_clean <- AI_CI_data %>% 
  select(-c(`NIH AI SCORE`, `NIH IC SCORE`)) %>% 
  pivot_longer(cols = -c(ID, Time_point), names_to = "Result", values_to = "Result_Value") %>% 
  separate(col = Result, into = c("Category", "Result"), sep = " - ", extra = "merge") %>% 
  mutate(Category = gsub(" ", "_", Category), 
         Result = gsub("[ ,\\-]+", "_", Result),
         Result_Value = na_if(Result_Value, "NA"),
         Result_Value = if_else(is.na(Result_Value), 
                         NA_real_, 
                         if_else(Result_Value > 0, 1, 0))) 

NIH_mapping <- c(Cellular_crescents = "Cellular/Fibrocellular_crescents",
                 Cellular_proliferation = "Endocapillary_hypercellularity",
                 Fibrinoid_necrosis_karyorrhexis = "Fibrinoid_necrosis",
                 Hyaline_thrombi_wire_loops = "Hyaline_deposits",
                 Leukocyte_infiltration = "Neutrophiles/Karyorrhexis",
                 Mononuclear_cell_infiltration = "Interstitial_inflammation")

NIH_Corr_Res_Sign_only_Clean <- NIH_Corr_Res_Sign_only %>% 
  group_by(Comparison) %>% 
  mutate(FDR = p.adjust(p.value, method = "fdr"), 
         Significance = case_when(p.value < 0.05 ~ "*"), 
         Origin = sub("_.*$", "", Marker), 
         Comparison = factor(Comparison, levels = c("Baseline vs Baseline", "Month 12 vs Month 12", "Baseline vs Month 12"))) %>% 
  rename(Correlation = "estimate") %>% 
  inner_join(AI_CI_data_clean %>% select(Result, Category), by = c("Result"), relationship = "many-to-many") %>% 
  group_by(Marker) %>% 
  mutate(Origin = sub("_.*$", "", Marker), 
         Marker = sub("^[^_]*_", "", Marker), 
         Result = recode(Result, !!!NIH_mapping), 
         Result = sub("_", "<br>", Result), 
         Result = gsub("_", " ", Result), 
         # Result = sub("/", "/<br>", Result),
         Category = factor(Category, levels = c("NIH_AI", "NIH_CI")),
         Category = gsub("_", " ", Category)) 

```

```{r}

NIH_Corr_Res_Sign_only_Clean_Sign <- NIH_Corr_Res_Sign_only_Clean %>%
  group_by(Marker) %>% 
  filter(any(Significance == "*")) %>% 
  ungroup()

Corr_scale <- NIH_Corr_Res_Sign_only_Clean_Sign %>% 
  summarise(min_corr = min(Correlation, na.rm = TRUE),
            max_corr = max(Correlation, na.rm = TRUE))

Sub_Correlation_plots_NIH <- function(orig) {

  Cor_df_current <- NIH_Corr_Res_Sign_only_Clean_Sign %>% 
    filter(Origin == orig) 
  
  Current_Title <- if (orig == "Serum") {"Serum proteome"} 
  else { orig }
  
  n_markers <- Cor_df_current %>% 
    distinct(Marker) %>% 
    nrow()
  
  n_comp <- Cor_df_current %>% 
    distinct(Result) %>% 
    nrow()
    
  Main_plot_current <- ggplot(Cor_df_current, aes(x = Result, y = Marker, fill = Correlation)) +
    geom_tile(color = "white", width = 1, height = 1) +
    scale_fill_gradient2(low = "dodgerblue", mid = "white", high = "firebrick", 
                         limits = c(Corr_scale$min_corr, Corr_scale$max_corr),
                         midpoint = 0, breaks = seq(-1, 1, by = 0.5), 
                         guide = guide_colorbar(order = 1, title.position = "top", title.hjust = 0, 
                                                title = "Spearman<br>Correlation", title.theme = element_markdown(face = "bold"))) +
    facet_wrap(~ Comparison, nrow = 1) +
    scale_x_discrete(expand = c(0, 0), drop = TRUE, labels = function(x) str_wrap(x, width = 6)) +
    scale_y_discrete(expand = c(0, 0)) +
    geom_text(aes(label = Significance, vjust = 0.7, hjust = 0.5, fontface = "bold")) +
    labs(title = paste0("Origin: ", Current_Title), 
         x = NULL, y = NULL) +
    theme_minimal(base_size = 12, base_family = "sans") +
    theme(strip.placement = "outside",
          strip.text.y.right = element_text(angle = 0, hjust = 0.5, vjust = 0.5, face  = "bold"),
          strip.text.x.top = element_text(angle = 0, hjust = 0.5, vjust = 0.5, face  = "bold"),
          axis.text.x = element_markdown(size = 9, angle = 60, hjust = 1, vjust = 1, 
                                         # face = "bold", 
                                         colour = "black"), 
          axis.text.y = element_text(size = 8, face = "bold", colour = "black"),
          panel.grid  = element_blank(), 
          panel.spacing = unit(1, "lines"),
          aspect.ratio = n_markers/n_comp * 0.4,
          plot.caption.position = "plot", 
          plot.caption = element_markdown(hjust = 0.9, vjust = 1, lineheight = 1.3),
          plot.title = element_markdown(face = "bold"), 
          plot.margin = margin(5, 5, 5, 5, "pt")) +
    coord_fixed()
  
  Main_plot_current
  
}

plots_by_origin <- map(unique(NIH_Corr_Res_Sign_only_Clean$Origin), Sub_Correlation_plots_NIH)

```

```{r}

p1 <- plots_by_origin[[1]]
p2 <- plots_by_origin[[2]] 
p3 <- plots_by_origin[[3]] 
p4 <- plots_by_origin[[4]]
p5 <- plots_by_origin[[5]] 
p6 <- plots_by_origin[[6]]

m_top <- margin(t = 0, r = 5, b = 5, l = 5)
m_mid <- margin(t = 5, r = 5, b = 5, l = 5)  
m_bottom <- margin(t = 5, r = 5, b = 0, l = 5)

p1 <- p1 + labs(tag = "A") # + theme(plot.title.position = "panel")
p2 <- p2 + labs(tag = "F") #+ theme(plot.title.position = "panel")
p3 <- p3 + labs(tag = "C") #+ theme(plot.title.position = "panel")
p4 <- p4 + labs(tag = "D") #+ theme(plot.title.position = "panel")
p5 <- p5 + labs(tag = "E") #+ theme(plot.title.position = "panel")
p6 <- p6 + labs(tag = "B") #+ theme(plot.title.position = "panel")

origins <- NIH_Corr_Res_Sign_only_Clean_Sign %>% 
  distinct(Origin) %>% 
  pull(Origin)

# 1) compute row‐counts for p1 and p2:
n1 <- NIH_Corr_Res_Sign_only_Clean_Sign %>%
  filter(Origin == origins[1]) %>%     # or whatever origin gives p1
  distinct(Marker) %>% nrow()

n2 <- NIH_Corr_Res_Sign_only_Clean_Sign %>%
  filter(Origin == origins[2]) %>%     # origin for p2
  distinct(Marker) %>% nrow()

n3 <- NIH_Corr_Res_Sign_only_Clean_Sign %>%
  filter(Origin == origins[3]) %>%     # origin for p2
  distinct(Marker) %>% nrow()

n4 <- NIH_Corr_Res_Sign_only_Clean_Sign %>%
  filter(Origin == origins[4]) %>%     # or whatever origin gives p1
  distinct(Marker) %>% nrow()

n5 <- NIH_Corr_Res_Sign_only_Clean_Sign %>%
  filter(Origin == origins[5]) %>%     # origin for p2
  distinct(Marker) %>% nrow()

n6 <- NIH_Corr_Res_Sign_only_Clean_Sign %>%
  filter(Origin == origins[6]) %>%     # origin for p2
  distinct(Marker) %>% nrow()

left_col <- wrap_plots(p1, p6, p2, ncol = 1, heights = c(n1, n6, n2), widths = c(1, 1, 1))

right_col <- wrap_plots(p3, p4, p5, ncol = 1, heights = c(n3, n4, n5), widths = c(1, 1, 1))

left_col <- wrap_plots(
  left_col,
  plot_spacer(),
  ncol    = 1,
  heights = c(0.95, 0.05)
) & 
  theme(
    # 10pt padding on the right of every left‐column plot
    plot.margin = margin(t = 0, r = 10, b = 0, l = 0, unit = "pt")
  )

right_col <- wrap_plots(
  right_col,
  plot_spacer(),
  ncol    = 1,
  heights = c(1, 0.02)
)

Gabagool <- wrap_plots(left_col, right_col,
                       ncol = 2, 
                       guides = "collect", 
                       widths = c(1, 1)
                       ) +
  plot_annotation(title = "Heatmap of marker - clinical/histopathological feature correlations", 
                  theme = theme(plot.title = element_markdown(face = "bold", 
                                                              size = 23, 
                                                              hjust = 0.5, 
                                                              margin = margin(t = 10, b = 5, unit = "pt")),
                                plot.tag = element_text(face = "bold", size = 30))) &
  theme(
    plot.margin = margin(2, 2, 2, 2, "pt"),
    panel.spacing = unit(0.2, "lines"),
    # strip.text = element_text(margin = margin(t = 1, b = 1, "pt")),
    legend.position = "right",
    legend.title = element_text(face = "bold"),
    legend.key.width = unit(2, "lines"),
    legend.key.height = unit(4, "lines"),    
    legend.spacing.y = unit(0.5, "lines"))

Gabagool <- Gabagool & theme(plot.tag = element_text(color = "black", face = "bold", size = 30))

ggsave(plot = Gabagool,
       filename = "~/SLE/Glycans/Plots_2/Figure_3_Correlations_NIH/NIH_Correlations_Combined.jpeg",
       width = 297, height = 210, units = "mm", dpi = 300, device = "jpeg", scale = 2)

```
